### ISSUE TITLE
Why diverge from the Construct convention with builders?

### ISSUE THREAD

**Issue by sam-goodwin** [aws-quickstart/cdk-eks-blueprints#1002]
### Describe the documentation issue

I just found this project and it seems super useful, but I can't help but notice how weird it is compared to most CDK Constructs:

```ts
const blueprint = blueprints.EksBlueprint.builder()
  .version(KubernetesVersion.V1_28)
  .addOns(karpenterAddOn)
  .build(app, 'my-stack-name');
```

1. why always recommend the builder pattern instead of a Construct? Builders are not common practice in TypeScript and it diverges far from CDK's conventions.
```ts
// this would be canonical
new EksBlueprintCluster(app, "my-stack-name", {
  version: KubernetesVersion.V1_28,
  addOns: [karpenterAddOn],
});
```
2. Why is it a Stack? I'm in a situation where I already have a Stack. I find this library (or at least the documented way of doing things) too opinionated.
3. I already have a `aws-cdk-lib/aws-eks.Cluster` deployed. Am i forced to use this builder? Can I install AddOns without it? 

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/

**Comment by sam-goodwin** [comment]
I think what would be ideal for someone like me who wants to migrate and adopt this library is the following pattern:

I already have a cluster:
```ts
const cluster = new Cluster(this, "Cluster", {
  ..
});
```

Let me swap in the `BlueprintCluster` and pass in add-ons
```ts
const cluster = new BlueprintCluster(this, "Cluster", {
  addons: [ new KarpenterAddOn() ]
  ..
});
```

**Comment by shapirov103** [comment]
CDK has an imperative style of constructing resources and for the most part developers are limited to a constructor to add their logic. Blueprints on the other hand facilitates a declarative style of defining a blueprint when customers can construct a blueprint as an abstract builder and instantiate at will with the build method. That enables declarative pipelines and simplifies the logic.

Builder pattern is a common way of handling complexity when constructing objects. You can view it as a DSL that enables pluggable components. it produces a stack. It is "too opinionated" as you mentioned, and does not pursue the goal of fitting into existing CDK stacks as a library of addons. 

For your task, we have a concept of a cluster provider. You can wrap your cluster creation as the `ClusterProvider` interface and inject into the blueprint.  Most people use generic cluster provider or derive from it. 
More info [here](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/).

For a custom cluster you can do something like this.

```ts
class MyClusterProvider implements ClusterProvider {
    createCluster(scope: Construct, vpc: IVpc, key, version...): ClusterInfo {
        const cluster = new Cluster(scope, "Cluster", {
          ...
          });
          return new ClusterInfo(cluster, version);
    }
}

const blueprint = blueprints.EksBlueprint.builder()
  .version(KubernetesVersion.V1_28)
  .clusterProvider(new MyClusterProvider())
  .addOns(karpenterAddOn)
  .build(app, 'my-stack-name');
```

I will think about your use case, such as allowing case of an existing stack to be used with blueprints.

**Comment by sam-goodwin** [comment]
Not sure what you mean by CDK being an imperative style. The Construct pattern was designed to model declarative infrastructure as code as closely as possible. The `props` is effectively typed JSON/YAML. Arguably, using builders is the imperative style.

This is effectively declarative config:
```ts
const blueprint = new EksBlueprintStack(app, "my-stack-name", {
  version: KubernetesVersion.V1_28,
  addOns: [ karpenterAddOn ]
});
```

What benefit does the builder bring? The only effect I see it having is making this library feel weird to all CDK Construct library users. 

I wouldn't mind if it was an option, but to have a "Stack builder" as the only way to consume these valuable add-ons is unfortunately limiting.

**Comment by shapirov103** [comment]
I disagree with you, you can read up on using builder patters in any language including typescript by running a google search: 
https://www.google.com/search?q=builder+pattern+in+typescript

EKS blueprints is not strictly CDK - it uses CDK behind the scenes but it can also use SDKs and other mechanism including GitOps to configure clusters. 

To address your question about instantiation of a blueprint without a buider, you still have a choice to just invoke a constructor on EKSblueprint passing your attributes as `EksBlueprintProps` to it. It produces a stack.

**Comment by shapirov103** [comment]
EKSBlueprint  stack is derived from https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/stacks/eks-blueprint-construct.ts - you can use it with your stack if that is your use case.

**Comment by shapirov103** [comment]
@joelcox22 id not being explicitly passed is an issue, and will be addressed.
