### ISSUE TITLE
[aws-mountpoint-s3-csi-driver] Addon support

### ISSUE THREAD

**Issue by Shellmode** [aws-quickstart/cdk-eks-blueprints#1008]
### Describe the feature

Since cdk-eks-blueprints has supported [EbsCsiDriverAddOn](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/ebs-csi-driver/) and [EfsCsiDriverAddOn](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/efs-csi-driver/), it will be good to support [aws-mountpoint-s3-csi-driver](https://docs.aws.amazon.com/eks/latest/userguide/s3-csi.html).

So that customer will have more storage options with cdk-eks-blueprints, and aws-mountpoint-s3-csi-driver is a great feature for eks nodes to write to S3.

### Use Case

EKS nodes write to S3 just like filesystem.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.139.0

### Node.js Version

v20.9.0

### Environment details (OS name and version, etc.)

MacOS 14.5 (23F79)

**Comment by yubingjiaocn** [comment]
For now, you can use `HelmAddon` to install Mountpoint for S3 CSI driver. See https://github.com/aws-solutions-library-samples/guidance-for-asynchronous-inference-with-stable-diffusion-on-aws/blob/main/lib/addons/s3CSIDriver.ts for demo implementation.
