### ISSUE TITLE
(dependency upgrade) Update CDK to v2.145.0 with Support for Kubernetes v1.30 in EKS

### ISSUE THREAD

**Issue by jgreenbow** [aws-quickstart/cdk-eks-blueprints#1016]
### Describe the feature

Now that [aws-cdk v2.145.0](https://github.com/aws/aws-cdk/releases/tag/v2.145.0) has released with support for Kubernetes v1.30 in EKS, a dependency upgrade for cdk-eks-blueprints would enable support for Kubernetes v1.30. 

### Use Case

By promptly supporting the most up to date Kubernetes version in EKS, users will be given more time to upgrade their staging environments and prepare their production upgrade. This improves the proportion of users for this project to stay current with the EKS lifecycle. This maintains/increases the relevancy of this project in the infrastructure provisioning landscape.

### Proposed Solution

Possible tasks (I'm not a contributor, but this is what I imagine is required)

- [ ] update pinned dependencies
- [ ] update tests
- [ ] validate and remediate test results
- [ ] update documentation
- [ ] prepare release

### Other Information

(Both untested at this time)
Users may override the CDK version to achieve this result for testing purposes
Users may use `KubernetesVersion.of('v1.30')` to override the version on a cluster-by-cluster basis

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

v2.145.0

### EKS Blueprints Version

v1.14.1

### Node.js Version

v20 LTS

### Environment details (OS name and version, etc.)

Linux

**Comment by shapirov103** [comment]
Please see release notes for [1.15.0](https://github.com/aws-quickstart/cdk-eks-blueprints/releases/tag/blueprints-1.15.0).

CDK was upgraded and we handle kubectl layer properly, however since ADOT does not support 1.30 yet, the default EKS version remained at 1.29. 

Please let me know if the latest 1.15.1 addresses your issue. Otherwise I will close it shortly.

**Comment by shapirov103** [comment]
Closing based on the comment above.
