### ISSUE TITLE
Change in logical IDs and resource paths between 1.14.0 and 1.15.0, and also not able to fix in 1.15.1

### ISSUE THREAD

**Issue by UlaJiang** [aws-quickstart/cdk-eks-blueprints#1037]
### Describe the bug

Hello Team

When upgrading from 1.14.0 to 1.15.0 the logical IDs and aws:cdk:path of resources created by the blueprint change.

previous version 1.14.0
```
“aws:cdk:path”: “wallet-eks-prod-infra/prod-app-cluster/kubectllayer28/Resource”
```

now version 1.15.0
```
“aws:cdk:path”: “wallet-eks-prod-infra/prod-app-cluster/prod-app-cluster-ct/kubectllayer28/Resource”
```

After we trying to update the version to 1.151.1, the “aws:cdk:path” is still the same as what being generated in 1.15.0. Also tried to revert the version back to 1.14.0 still not help. 

We noticed that the newly generated cdk path is not only duplicate the `prod-app-cluster` but also with `-ct` surfix appened. 

I can see that 4 days ago, there is some commit in [`lib/stacks/eks-blueprint-construct.ts`](https://github.com/aws-quickstart/cdk-eks-blueprints/blame/main/lib/stacks/eks-blueprint-construct.ts#L211-L212C51) with `-ct` appended, not sure if this is related

```
    constructor(parent: Construct, blueprintProps: EksBlueprintProps) {
        super(parent, blueprintProps.id + "-ct" );        <<<--- HERE
```

Not sure if something related to https://github.com/aws-quickstart/cdk-eks-blueprints/issues/1033. Thanks for any help ;) 

### Expected Behavior

Resource paths do not change between versions

### Current Behavior

Logical IDs and resource paths for 100s of resources have changed resulting in resource replacement and deployment failure

### Reproduction Steps

as above

### CDK CLI Version

2.147.3

### EKS Blueprints Version

1.15.1

### Node.js Version

v20.14.0

### Environment details (OS name and version, etc.)

mac

**Comment by shapirov103** [comment]
@UlaJiang how does it affect your deployment, are you getting failures because of that?
The #1033 was related to the change in path that caused the deployment failure and prevented upgrade.

For reference: the "-ct" postfix (abbreviated "construct") was added to the blueprint construct to avoid duplicate id.

**Comment by shapirov103** [comment]
@UlaJiang, `EKSBlueprint` takes `EKSBlueprintProps` into constructor, which has `compatibilityMode` [attribute](https://aws-quickstart.github.io/cdk-eks-blueprints/api/classes/stacks.EksBlueprintProps.html#compatibilityMode), which you can set to true.

**Comment by UlaJiang** [comment]
thanks so much @shapirov103 for share the link, really helpful

**Comment by shapirov103** [comment]
@UlaJiang glad it helped. Do I assume correctly that this issue is addressed and can be closed?

**Comment by UlaJiang** [comment]
@shapirov103  Yes, please close this issue. Your suggestion helps me resolve the issue ;)

Really appreciate for your quick reply. Thanks again!
