### ISSUE TITLE
Does Calico Operator Add-on support Egress Gateway?

### ISSUE THREAD

**Issue by NinoSkopac** [aws-quickstart/cdk-eks-blueprints#1049]
### Describe the documentation issue

Looking at https://aws-quickstart.github.io/cdk-eks-blueprints/addons/calico-operator/ I'm not sure if it's Calico open source or Calico Enterprise - it seems the former?

This page https://docs.tigera.io/calico-cloud/about/product-comparison tells me I need Calico Enterprise for an Egress Gateway.

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/calico-operator/

**Comment by NinoSkopac** [comment]
I believe I have found the answer: https://github.com/projectcalico/calico/issues/7338

**Comment by shapirov103** [comment]
@NinoSkopac with support of Network Policies natively by VPC-CNI, what is your use case to use Calico? Are you trying to work around the issue of IPv4 exhaustion, by using an overlay network?
We do have an [approach](https://aws.amazon.com/blogs/containers/automating-custom-networking-to-solve-ipv4-exhaustion-in-amazon-eks/) for IPv4 exhaustion with secondary CIDRs and VPC-CNI configuration if that is what you are after.

**Comment by NinoSkopac** [comment]
Dear @shapirov103 ,

My use case is as follows. I have a container that requires full cone NAT. To achieve that I give the container an elastic IP using the EIP controller: https://github.com/aws-samples/aws-pod-eip-controller. An EIP allows unsolicited connections to come in on a set port, which is basically the definition of full cone NAT. 

The problem is as you say IPv4 exhaustion. I want to have hundreds of these containers running in the same time and each of them needs an elastic IP, which is impossible due to AWS limits.

I want to use an egress gateway and give it an elastic IP and then route the traffic from the previously mentioned hundreds of containers through the egress gateway. 

I'd put those hundreds of containers in the namespace and configure Cilium rather than Calico due to former being FOSS to do the routing. 

I'll look into the link you gave me, thank you very much and have a great day!

**Comment by xiaosuiba** [comment]
> Dear @shapirov103 ,
> 
> My use case is as follows. I have a container that requires full cone NAT. To achieve that I give the container an elastic IP using the EIP controller: https://github.com/aws-samples/aws-pod-eip-controller. An EIP allows unsolicited connections to come in on a set port, which is basically the definition of full cone NAT.
> 
> The problem is as you say IPv4 exhaustion. I want to have hundreds of these containers running in the same time and each of them requires an elastic IP, which is impossible due to AWS limits.
> 
> I want to use an egress gateway and give it an elastic IP and then route the traffic from the previously mentioned hundreds of containers through the egress gateway. Will it work? I don't know.
> 
> I'd put those hundreds of containers in a namespace and configure Cilium rather than Calico due to former being FOSS to do the routing.
> 
> I'll look into the link you gave me, thank you very much and have a great day!

I found this egressgateway which can work with calico: [egressgateway](https://github.com/spidernet-io/egressgateway/tree/main?tab=readme-ov-file)

**Comment by NinoSkopac** [comment]
Dear @xiaosuiba ,

thank you so much for that link.

However, I have decided not to use Calico, I'm going to use Cilium. [GKE went from Calico to Cilium](https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/What-CNI-plugin-is-used-in-GKE-and-are-there-alternatives/m-p/671169). Calico is not FOSS, Cilium is. I hope I can pull it off using Cilium Egress Gateway: https://docs.cilium.io/en/stable/network/egress-gateway/egress-gateway/

**Comment by lukasmrtvy** [comment]
@NinoSkopac Cilium Egress Gateway is not HA, it allows You to use only one egress node
