### ISSUE TITLE
MngClusterProvider: Can't add security group to managed node group

### ISSUE THREAD

**Issue by Kang3498** [aws-quickstart/cdk-eks-blueprints#1054]
### Describe the bug

I created a security group and attached it to my cluster, but it's attached as a additional security group.
So it didn't be applied to managed node groups.
How I can add my security group to instances in managed node group?

### Expected Behavior

My security group has been attached to instances in managed node group.

### Current Behavior

My security group has not been attached to instances in managed node group.
It's attached just as additional security group

### Reproduction Steps

```

const clusterSecurityGroup = new ec2.SecurityGroup(scope, id + "-eks-sg", {
	vpc,
	allowAllOutbound: true
});
const clusterProvider = new blueprints.MngClusterProvider({
        version: eks.KubernetesVersion.V1_30,
        clusterName: nameRule("eks-cluster"),
        minSize: 1,
        desiredSize: 1,
        securityGroup: clusterSecurityGroup
});

const blueprint = new blueprints.EksBlueprintConstruct(scope, {
	id: id + "-cluster",
	addOns,
	resourceProviders,
	clusterProvider
});
```

### CDK CLI Version

2.147.3

### Node.js Version

20.15.1

### Environment details (OS name and version, etc.)

MAC OS

**Comment by shapirov103** [comment]
@Kang3498 
The blueprints is leveraging the CDK functionality to create the cluster. We are passing the securityGroup directly to the [CDK Cluster construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html). I confirm that it is indeed treated as additional security group that does not seem to have impact, however this more of a CDK issue. Here is what the docs say about this group:

> Additional cluster security groups control communications from the Kubernetes control plane to compute resources in your account.

You have two options to affect the node level networking.

1. Specify security group in the launch template for the node group. Example of setting a launch template  [here] (has securityGroup attribute)(https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/examples/blueprint-construct/index.ts#L367). Launchtemplate doc [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.LaunchTemplate.html).
2. You can modify the cluster security group (top level). It is create by EKS automatically. To modify you need an addon with the rules that you should add to the list of addons. Here is an example:

```ts
class SecurityGroupForNodesAddon implements bp.ClusterAddOn {
    deploy(clusterInfo: bp.ClusterInfo): void {
        const sg = ec2.SecurityGroup.fromSecurityGroupId(clusterInfo.cluster, 'ClusterSecurityGroupForNodesId', clusterInfo.cluster.clusterSecurityGroupId, {
            allowAllOutbound : false // this disallows all outbound, remove if it is not your intention
        });
        // the rules below are necessary for the EKS CP comms
        sg.addEgressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(443));
        sg.addEgressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(10250));
        sg.addEgressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(53));
        sg.addEgressRule(ec2.Peer.anyIpv4(), ec2.Port.udp(53));
        // optional output the id of security group
        new cdk.CfnOutput(clusterInfo.cluster.stack, 'clusterSg', { value: sg.securityGroupId });
    }
}
```

**Comment by Kang3498** [comment]
@shapirov103  I understand your explanation well. Thank you for your comment :)
