### ISSUE TITLE
(Addon's): addon's with version Auto not deployed

### ISSUE THREAD

**Issue by FonsBiemans** [aws-quickstart/cdk-eks-blueprints#1086]
### Describe the bug

i have the following Addon's: CoreDNS, Kube-proxy, EBS CSI Driver, and the VPC CNI 
it the version of these addon's is set to Auto, they are not deployed to the cluster. when i set them to a specific version they are deployed. 

### Expected Behavior

when the version is set to auto, it should deploy the latest version.

### Current Behavior

not deploying the addon, no errors, synth and deploy is going without error's but when you check the cluster, there are no addon's.

### Reproduction Steps

            new blueprints.addons.CoreDnsAddOn(
               'v1.11.1-eksbuild.8'

            ),
            new blueprints.addons.KubeProxyAddOn(
              'v1.30.0-eksbuild.3'

            ),

### Possible Solution

not found yet.

### CDK CLI Version

2.161.1

### EKS Blueprints Version

1.15.1

### Node.js Version

v18.18.2

### Environment details (OS name and version, etc.)

mac os, and github action ubuntu.

**Comment by shapirov103** [comment]
Accepted, most likely related to lack of version registered for 1.30 EKS version. When running synth, do you mind making sure that you have AWS credentials configured that allow access to the `aws eks describe-addon-versions` API/CLI? 
To detect the version we make the API call, if fails, then we make a static lookup in the internal dictionary. 
I will also look into lack of diagnostics that you mentioned, you should get errors in the stdout/stderr.

**Comment by shapirov103** [comment]
You can set the log level like and see if you get any descriptive messages:

```ts
import { utils } from "@aws-quickstart/eks-blueprints";
import { HelmAddOn } from '@aws-quickstart/eks-blueprints';


    blueprints.HelmAddOn.validateHelmVersions = true;
    blueprints.HelmAddOn.failOnVersionValidation = false;
    utils.logger.settings.minLevel = 3; // info
    utils.userLog.settings.minLevel = 2; // debug
    
    builder...
```
if it works, I can enable these by default
