### ISSUE TITLE
Support aws-cdk version 2.165.0 or newer 

### ISSUE THREAD

**Issue by yaakov-khodorkovski-lendbuzz** [aws-quickstart/cdk-eks-blueprints#1105]
### Describe the bug

The `@aws-quickstart/eks-blueprints` package currently requires `aws-cdk` version `2.162.1`. However, our project is using `aws-cdk` version `2.165.0`, which causes a dependency conflict.

### Expected Behavior

The `@aws-quickstart/eks-blueprints` package should support the latest version of `aws-cdk`. 

### Current Behavior

The installation fails with the following error:
npm error Could not resolve dependency:
npm error peer aws-cdk@"2.162.1" from @aws-quickstart/eks-blueprints@1.16.2
npm error node_modules/@aws-quickstart/eks-blueprints
npm error   @aws-quickstart/eks-blueprints@"1.16.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error 

### Reproduction Steps

1. Set `aws-cdk` version to `2.165.0` in `package.json`.
2. Install dependencies using `npm install`.
3. See the dependency conflict error.

### CDK CLI Version

2.165.0

### Node.js Version

v23.4.0

### Environment details (OS name and version, etc.)

Mac os

### Other information

If not will be updated soon. Can I possibly get an ETA?

**Comment by shapirov103** [comment]
@yaakov-khodorkovski-lendbuzz we are planning to create a patch release with the latest CDK version.

However, it should not be an issue for you to move to the latest version of the CDK now. We pinned the version to the one we tested against using `peerDependencies`.  Please see this doc: https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#configure-your-project.

here is an extract that may be relevant for you:

> Note: after the initial installation, upgrading the version of CDK to an incompatible higher/lower version will produce a warning, but will succeed. For community support (submitting GitHub issues) please make sure you have a matching version configured.

This will be the preferred method. 

You can also use an npm override mechanism similar to the one we used here: https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/package.json#L50.

In both cases you can run `npm install -f` to force the version that is different from the one we tested against.

**Comment by yaakov-khodorkovski-lendbuzz** [comment]
Okay , Thank you for your fast response 🙏
