### ISSUE TITLE
[PROVIDER] - EMR on EKS

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#113]
[EMR on EKS](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html) allows customers to run spark jobs on EKS (ec2 or fargate). We can easily add a provider for EMR and expose a "job" api to let developers submit spark jobs without having to worry about how to provision EKS infrastructure.

A reference implementation already exists [here](https://github.com/aws-samples/aws-cdk-for-emr-on-eks).

**Comment by askulkarni2** [comment]
@kcoleman731 @shapirov103 thoughts on adding this provider?

**Comment by youngjeong46** [comment]
This is provided as addon per PR #522 (big thanks to @Imouhib). Will close the issue as complete.
