### ISSUE TITLE
[FEATURE] - Add support to set up one managed node group per AZ

### ISSUE THREAD

**Issue by starchx** [aws-quickstart/cdk-eks-blueprints#138]
As recommended [here](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html#ca-deployment-considerations), we should add support to allocate one node group per AZ. With one node group across 3 AZs, Cluster Autoscaler has no control over which AZ the new node will be launched from.

**Comment by starchx** [comment]
Yep. Spot on.

**Comment by shapirov103** [comment]
@starchx I assume with mixed node group support it should be possible now. as long as you pass the right VPC subnet selection to each node group you can make it happen. 
See https://github.com/aws-quickstart/ssp-amazon-eks/pull/307 for details. 

Please let me know what you think about it and if there is anything else we need to do. 

I can address it by adding a pattern to the patterns repo.

**Comment by starchx** [comment]
@shapirov103 , yes, that will do. Great feature 👍 ! We can close this issue.

**Comment by elamaran11** [comment]
Closing this issue.
