### ISSUE TITLE
[ADDON] - EKS Managed Add-ons

### ISSUE THREAD

**Issue by starchx** [aws-quickstart/cdk-eks-blueprints#139]
AWS EKS supports managed addons for VPC CNI, kube-proxy and CoreDNS. It simplifies the maintenance and we should add option for user to enabled EKS managed addons.

[ ] CoreDNS
[ ] kube-proxy
[ ] Amazon VPC CNI

Reference: https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html

**Comment by kcoleman731** [comment]
Agree. Are thinking of building addon support for this into the framework?

**Comment by starchx** [comment]
I haven't figured out how to implement this yet, but yes, the idea is to add this support to the framework.

**Comment by starchx** [comment]
@anjaniye

**Comment by AnjanaVaidyanathaIyer** [comment]
I gave it a try using cfnAddon [https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.CfnAddon.html#resolveconflicts](url).
Eg : 
`new CfnAddon(scope, "vpc-cni-addon", {
            addonName: "vpc-cni",
            addonVersion: "v1.9.0-eksbuild.1",
            clusterName: cluster.clusterName,
            resolveConflicts:  "OVERWRITE"
        });`
It seems to be working.

**Comment by kcoleman731** [comment]
@AnjanaVaidyanathaIyer awesome. Any idea when you will have. PR ready?

**Comment by AnjanaVaidyanathaIyer** [comment]
@kcoleman731 I will raise the PR by next week.

**Comment by AnjanaVaidyanathaIyer** [comment]
Hi @kcoleman731 , I have raised the Pull Request - https://github.com/aws-quickstart/ssp-amazon-eks/pull/194
Appreciate your feedback.

**Comment by youngjeong46** [comment]
All three have been implemented as add-on. Closing the issue.
