### ISSUE TITLE
CDKv2 support

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#201]
CDKv2 is in developer preview. We should start baking in the v2 support in the SSP for customers who have started or will be adopting v2 at launch.

**Comment by shapirov103** [comment]
I looked at it a few months ago, and unfortunately I was not able to get a clear understanding on when it is going to GA. It was in the preview for a long time and I recall they were targeting an RC back then. Do you have any info on GA date for it?

**Comment by askulkarni2** [comment]
I don't know of a date. Thoughts on maintaining a parallel `v2-main` branch?

**Comment by jpxd** [comment]
CDKv2 is now the new default version in the CDK documentation

**Comment by youngjeong46** [comment]
Blueprints now support v2.20. Closing the issue.
