### ISSUE TITLE
EKs Cluster with Mix Compute Type

### ISSUE THREAD

**Issue by allamand** [aws-quickstart/cdk-eks-blueprints#203]
We often see EKS users having different kinds of compute in one cluster.

They can have a mix with Fargate, on-demand, Spot, dedicated nodegroups for specific workloads and so one.

SSP provide a very nice way to pick/choose which add-ons to install in the cluster.

It would be great to have similar approach for compute as well in order to create Fargate profiles, on-demand node groups, spot nodegroups with specific size, taints, labels, and other with different configuration

**Comment by terrell-r** [comment]
I'd also like to see this enhancement, as well as self-managed Windows node groups, and an option to specify node group names.

**Comment by shapirov103** [comment]
@allamand please see the changes in https://github.com/aws-quickstart/ssp-amazon-eks/pull/307.
Does it address your issue? If yes, then I will close it.

**Comment by shapirov103** [comment]
@terrell-r for self-managed Windows support, let's create a separate issue.

**Comment by allamand** [comment]
@shapirov103 yes i think this exactly what I needed. Thanks 🙏
