### ISSUE TITLE
[TASK] - Use GitHub ISSUE_TEMPLATES for creating new issues.

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#204]
Create `ISSUE_TEMPLATES` under `.github`. Issues can be classified into bugs, enhancements, questions, etc. and we can use templates to pre-configure the information we would like customers to provide to reduce some of the back and forth. See [SDLF](https://github.com/awslabs/aws-serverless-data-lake-framework/tree/master/.github/ISSUE_TEMPLATE) for example. More info on templates [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Comment by edgarsilva948** [comment]
I would like to contribute to this task :)

**Comment by youngjeong46** [comment]
Closing the issue as this is now implemented (PR #371 ).
