### ISSUE TITLE
[ADDON] - AWS Node Termination Handler

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#209]
See https://github.com/aws/aws-node-termination-handler.

**Comment by askulkarni2** [comment]
NTH is not required for MNG as per https://github.com/aws/containers-roadmap/issues/608#issuecomment-974176427. I will update the PR.

**Comment by youngjeong46** [comment]
Closing the issue as NTH is implemented.
