### ISSUE TITLE
Role.fromRoleArn issue

### ISSUE THREAD

**Issue by jasonamyers** [aws-quickstart/cdk-eks-blueprints#214]
I've tried using the docs version of this 
```
const adminTeam = new PlatformTeam( {
    name: "second-adminteam", // make sure this is unique within organization
    userRole: Role.fromRoleArn(`${YOUR_ROLE_ARN}`);
})
```
and also using
```
      const role = iam.Role.fromRoleArn(
        scope,
        "second-adminteam",
        "arn:aws:iam::195775481909:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_854c6fece4229187",
        {
          mutable: false,
        }
      )
      console.log(JSON.stringify(role));
        const adminTeam = new ssp.PlatformTeam({
          name: "second-adminteam", // make sure this is unique within organization
          userRole:  role
        });
```
I don't seem to know where to import the first one, and the second one results in it complaining about not being in a stack.

`App at '' should be created in the scope of a Stack, but no Stack found`

Anyone got any updated guidance here? We use cross account roles and don't have any users in our dev accounts.

**Comment by shapirov103** [comment]
Looking into it. I will provide an example and most likely code change to deal with resources like this.

**Comment by shapirov103** [comment]
@jasonamyers question: when supplying your role (assuming you want to pass ARN) do you expect the role to be modified to include policies that allow listing the cluster and getting access to workload in the UI?

**Comment by shapirov103** [comment]
Workaround in the current state:

```typescript
export class SSOTeam extends ApplicationTeam {
    constructor(private readonly roleArn: string) {
        super( {
            name: 'my-sso-team',
        })
    }

    protected getOrCreateRole(clusterInfo: ClusterInfo, users: Array<iam.ArnPrincipal>, role?: iam.IRole): iam.IRole | undefined {
        const importedRole = iam.Role.fromRoleArn(clusterInfo.cluster.stack, "sso-team-role", this.roleArn);
        // you can return super.getOrCreateRole or role as is
        return importedRole;
    }
}
```

We will be addressing the convenience to allow passing ARN directly, but would like to better understand your requirements (see my previous question).

**Comment by jasonamyers** [comment]
It would be awesome if it added the proper policies to the role. We're testing this in conjunction with our usage of control tower and aws signing, which gives us a bunch of roles that we want to leverage in several different accounts.

**Comment by shapirov103** [comment]
@jasonamyers  this has been resolved by allowing to pass userRoleArn directly. We stayed away for now from granting eks:describe type roles. 
I will be closing it soon.
