### ISSUE TITLE
[Enhancement] Nginx addon should not have hard order depdency to be after AWSLoadBalancerController addon

### ISSUE THREAD

**Issue by danilko** [aws-quickstart/cdk-eks-blueprints#225]
### Short description:
As part of https://github.com/aws-quickstart/ssp-amazon-eks/pull/224#discussion_r731469718

It is discussed that Nginx Add-on ***SHOULD NOT*** have hard order dependency (always need to be placed after AWSLoadBalancerController Add-on) for it to work.
It is okay to depend (i.e. require AWSLoadBalancer addon to be present), but the order should not matter

### Reproduce:
Create a simple eks-ssp requirement by declaring addon in following order, notice NginxAddOn is before AwsLoadBalancerControllerAddOn()

```
const addOns: Array<ssp.ClusterAddOn> = [
   new ssp.addons.NginxAddOn,
    new ssp.addons.ArgoCDAddOn,
    new ssp.addons.CalicoAddOn,
    new ssp.addons.MetricsServerAddOn,
    new ssp.addons.ContainerInsightsAddOn,
    new ssp.addons.AwsLoadBalancerControllerAddOn(),
    new ssp.addons.VpcCniAddOn(),
    new ssp.addons.CoreDnsAddOn(),
    new ssp.addons.KubeProxyAddOn()
];
```

### Expectation:
The stack created without issue

### Actual Happen:
During `cdk deploy` (able to pass `npm run build`), error out with following:
```
Assertion failed: Missing a dependency for AwsLoadBalancerControllerAddOn
```

### Analyze:
The reason is because within [Nginx AddOn](https://github.com/aws-quickstart/ssp-amazon-eks/blob/main/lib/addons/nginx/index.ts), there is a hard requirement on AwsLoadBalancerControllerAddOn with the `@depdency`

```
@dependable('AwsLoadBalancerControllerAddOn')
    deploy(clusterInfo: ClusterInfo): Promise<Construct> {
```

From the code logic perspective, it will allow the code to detect and error out if it cannot detect necessary addon (which it successfully detect). 

The problem through is current addon initialize logic seem initialize by:
1. [The order addons comes in (strict order)](https://github.com/aws-quickstart/ssp-amazon-eks/blob/main/lib/utils/addon-utils.ts)
```
        for (let addOn of (blueprintProps.addOns ?? [])) { // must iterate in the strict order
            const result = addOn.deploy(this.clusterInfo);
            if (result) {
                const addOnKey = getAddOnNameOrId(addOn);
                this.clusterInfo.addScheduledAddOn(addOnKey, result);
            }
            const postDeploy: any = addOn;
            if ((postDeploy as spi.ClusterPostDeploy).postDeploy !== undefined) {
                postDeploymentSteps.push(<spi.ClusterPostDeploy>postDeploy);
            }
        }
```
2. Then [ Nginx's dependable code will trigger assert, which cause the problem (as the awsloadbalancer will not be loaded at this point according to this order)](https://github.com/aws-quickstart/ssp-amazon-eks/blob/main/lib/utils/addon-utils.ts) as that dependency is not being initialized yet, but code believe then it is not met

Note the `addOns` in this case is what being declared within Nginx addon, which is `@dependable('AwsLoadBalancerControllerAddOn')`
The error message maybe slightly better if changed to missing a dependency addon ${requiredAddOn}  for ${sourceAddOn class} for ${stack}, as it is not really AwsLoadBalancerControllerAddOn missed the depdency, but AwsLoadBalancerControllerAddOn itself is a missing depdency

```
export function dependable(...addOns: string[]) {
...
      addOns.forEach( (addOn) => { 
        const dep = clusterInfo.getScheduledAddOn(addOn);
        console.assert(dep, `Missing a dependency for ${addOn} for ${stack}`);
        dependencies.push(dep!);
      });
```

### Possible Fix
Following fix is to preserve the dependable method to ensure correct ordering during addon Intilaize (basically reorder the addon order for the user)

0. Update the addOn logic, so each addOn's depdency can be extracted as className (maybe expend the dependable on method?)

Before
```
        for (let addOn of (blueprintProps.addOns ?? [])) { // must iterate in the strict order
```

1. Created an order array to track addOnOrdering
2. Loop through the addOns:
```
If addon.depdency has a dependency
    Try to loop through addOnOrdering array to find the dependency with classname or id
        if not found, inject dependency to end
        if found, skip this dependency
                Do same for this dependency addon's dependency until all there is no more dependency
Perform until all dependencies are in array
Then inject addon itself after the last dependency's entry in the array
```
3. Instead of initializing based on `blueprintProps.addOns` , will instead using the ordered array `addOnOrdering` to initalize stuff in correct order

In theory, above loop will construct an addOnOrdering array with correct ordering
However, it will not avoid all conflict if A depends on C and D, but B depend on D and C and that order matters (but even in current code, this logic will not work). 

Not sure if above case need to be considered, or we can assume that from code perspective, there should not be circular dependency 

Also, this above code only check base on classname or id , it did not really check whatever that dependency addon really can initialized, which kind conflict current code (the reason current code might work as this way is it is using an after initialized result before add that into cluster for later code to call)

**Comment by askulkarni2** [comment]
@danilko this is a very interesting approach. We could raise an exception for circular dependency (we should probably do that anyway). What is the impact to`postDeploy()`?

Would like to get @shapirov103's thoughts.
