### ISSUE TITLE
[FEATURE] - Upgrade Container Insights to leverage FluentBit

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#242]
Currently leveraging FluentD and outdated

**Comment by sunnygoel87** [comment]
@shapirov103 - Just curious, If someone is using **optimized version** of FluentBit agent and CloudWatch agent on EKS cluster to offload application/dataplane/host logs and metrics on CloudWatch, then where does FluentD come into the picture ?

**Comment by shapirov103** [comment]
@sunnygoel87 this issue was created to address the previous approach used in Container Insights as it was leveraging FluentD. This issue is now addressed with https://github.com/aws-quickstart/ssp-amazon-eks/pull/307 container insights add-on refactoring to leveraging AWS distro for open telemetry (adot) and fluentbit for logging. Please let me know if you have any follow-up questions. I will be closing this issue in a bit.
