### ISSUE TITLE
[Design] Utilize IPv6 feature for EKS 

### ISSUE THREAD

**Issue by parkand1** [aws-quickstart/cdk-eks-blueprints#264]
Leverage IPv6 to avoid IP address exhaustion, minimize latency at scale, and simplify routing configuration moving forward.

**Comment by youngjeong46** [comment]
cdk currently has no IPv6 support (to which I've raised an issue [here](https://github.com/aws/aws-cdk/issues/18423)); this may have to be custom resource creation in the mean time.

**Comment by elamaran11** [comment]
Currently the VPC CNI Addon does not support env variables such as IPV6 etc so we are working with support team on this. Once they support these vars as part of advanced features of VPC CNI addon. We will work on a a pattern too along with upgrading our VPC CNI addon.
