### ISSUE TITLE
[TASK] - Create a `custom-resources` construct for Tags

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#272]
There are a few utils now that leverage the CDK `custom-resources` to apply Tags post facto. We should create a construct so that we can reuse the custom resource and not create multiple instances of it.

**Comment by vumdao** [comment]
@askulkarni2 @shapirov103 
Can we have custom-resource tags for `NodegroupOptions` interface of `managed-nodegroup` like 👇🏼  ?
![image](https://user-images.githubusercontent.com/37215642/215057973-bce72a91-da18-454f-8960-03db09e60eb0.png)

**Comment by vumdao** [comment]
Look like this https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatetagspecification.html
```
{
  "ResourceType" : String,
  "Tags" : [ Tag, ... ]
}
```
