### ISSUE TITLE
[BUG] Pipeline throws error when trying to register webhook

### ISSUE THREAD

**Issue by camba1** [aws-quickstart/cdk-eks-blueprints#279]
When adding a pipeline to a blueprint, the pipeline throws an error on first execution indicating that it does not have enough enough permissions to create the webhook:

`east-test-1 |  3/39 | 12:26:14 AM | UPDATE_FAILED        | AWS::CodePipeline::Webhook  | ssp-amazon-sample-eks/Pipeline/Source/camba1_ssp-amazon-eks-sample/WebhookResource (sspamazonsampleeksPipelineSourcecamba1sspamazonekssampleWebhookResource44753262) Webhook could not be registered with GitHub. Error cause: Invalid credentials [StatusCode: 401, Body: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 9d4ba50a-e10b-4218-a9ef-6c967f475c07; Proxy: null)`

I checked the Personal Access Token and it seemed to have the correct access as can be seen in the attached screenshot:

![Screen Shot 2022-01-25 at 7 23 27 PM](https://user-images.githubusercontent.com/7367366/151223872-0e15363e-3d53-48f8-8b5a-f141fcfa0cca.png)

If I give the token all permissions, redeploye the application and the pipeline was able to setup the web hooks normally. I have not had the time yet to figure out which is the exact permission that is required and that caused it to work properly

It is interesting to note that the permissions in the screenshot were enough to get through the workshop, but apparently not enough to create the web hooks in my repo.

**Comment by camba1** [comment]
I was able to get it running reliably using the following token permissions:
![Screen Shot 2022-01-26 at 5 11 20 PM](https://user-images.githubusercontent.com/7367366/151262868-cec521b3-a7c4-4c84-8aa3-c9a53eaa8528.png)

After which I ran into issues with the pipeline failing in the build stage as it was not able to assume some of the necessary roles. I added the following to the pipeline -> Build -> details -> Environment -> Service Role:

```
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
	   "Action": ["iam:PassRole", "sts:AssumeRole"],
            "Resource": [
                "arn:aws:iam::*:role/cdk-readOnlyRole",
                "arn:aws:iam::*:role/cdk-hnb659fds-deploy-role-*",
                "arn:aws:iam::*:role/cdk-hnb659fds-file-publishing-*",
                "arn:aws:iam::*:role/cdk-hnb659fds-lookup-role-*"
            ]
        },
```
After that it works normally.

**Comment by shapirov103** [comment]
Juan, thank you for bringing it up.  I checked my personal token that I use with the pipeline and I use the following permission:
<img width="945" alt="Screen Shot 2022-01-27 at 10 06 51 AM" src="https://user-images.githubusercontent.com/60622975/151387078-0fdbfaf9-58e9-446c-83de-40b46e3ba5dc.png">


@parkand1  I know you were working on defining the exact permissions, so  you might to test it out. The

**Comment by youngjeong46** [comment]
@camba1 @shapirov103 I had the following permissions on mine that worked both on a standard AWS account and workshop-specific accounts:

![github-personal-access-token-scope](https://user-images.githubusercontent.com/2121226/151391344-65434214-d25b-4e9e-be71-5cc4642f4de1.png)

So mirroring Juan's with the exception of admin:org_hook. We will run another test so will keep that in mind.

**Comment by shapirov103** [comment]
Seems to be addressed. Please reopen if there is a particular change needed.
