### ISSUE TITLE
[ADDON] - Flux

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/cdk-eks-blueprints#29]
Add support for Flux.

https://fluxcd.io/
https://github.com/fluxcd/flux
https://docs.fluxcd.io/en/latest/tutorials/get-started-helm/

**Comment by shapirov103** [comment]
It is in the active backlog now, we should have this in a couple of weeks. That is fluxcd v2 addon with bootstrapping capabilities. It won't have full feature parity with ArgoCD just yet, for example ArgoCD add-on allows GitOps add-on management, FluxCD initially won't have that.

**Comment by danielloader** [comment]
Glad to see the PR is up already https://github.com/aws-quickstart/cdk-eks-blueprints/pull/627

Looking forward to the point where you can do the bootstrapping from CDK via addon params! 

Good work all.
