### ISSUE TITLE
[BUG] Fargate only cluster creates "default" fargate profile without asking/configuring it

### ISSUE THREAD

**Issue by tsahiduek** [aws-quickstart/cdk-eks-blueprints#324]
Trying to create a Fargate only cluster with single fargate profile, results in 2 fargate profiles that are being created: the configured one, and another one called `default` targeting `kube-system` and `default` namespaces

Configurations snippet
```ts

        const fargateProfiles: Map<string, eks.FargateProfileOptions> = new Map([
            ["base-profile", { selectors: [{ namespace: "kube-system" }, { namespace: "karpenter" }] }],

        ]);
        const fargateClusterProvider = new ssp.FargateClusterProvider({
            fargateProfiles,
            version: clusterVersion
        });

        const blueprint = ssp.EksBlueprint.builder()
            .account(PIPELINE_ENV.account)
            .region(PIPELINE_ENV.region)
            .withBlueprintProps({
                version: clusterVersion,
            })
            .clusterProvider(fargateClusterProvider)
```

**Comment by maxritter** [comment]
Same happened to me..

**Comment by shapirov103** [comment]
This works as designed. The behavior is similar to ekscstl --fargate behavior. See more [here](https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#:~:text=AWS%20Fargate%20profile.-,Note,any%20other%20namespaces%20you%20would%20like%20to%20use%20with%20Fargate.,-You%20can%20create).

You can leverage the [generic cluster provider](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/generic-cluster-provider/) to configure arbitrary fargate profiles.

**Comment by javydekoning** [comment]
I was facing the same today. I don't want a default Fargate profile (Only one for the Karpenter namespace). Using the generic Cluster Provider it's easy to solve this: 

```ts
    const clusterProvider = new blueprints.GenericClusterProvider({
      version: eks.KubernetesVersion.V1_21,
      fargateProfiles: {
        karpenter: {
          fargateProfileName: 'karpenter',
          selectors: [{ namespace: 'karpenter' }],
        },
      },
    });
```

However, we might want to explicitly call out the 'default' behaviour in the documentation when leveraging. `FargateClusterProvider`
