### ISSUE TITLE
[DOC] - Pipelines

### ISSUE THREAD

**Issue by youngjeong46** [aws-quickstart/cdk-eks-blueprints#327]
Several doc updates are needed under [pipelines](https://aws-quickstart.github.io/cdk-eks-blueprints/pipelines/):

- https://aws-quickstart.github.io/cdk-eks-blueprints/pipelines/#defining-your-blueprint-to-use-with-pipeline - "Pipeline support requires enabling a setting for modern stack synthesis. This setting should be enabled for blueprints that leverage CDKv1 explicitly, for CDKv2 it is enabled by default." should be provided with links to the official documentation, and should be moved to the latter section called "Deploying Pipelines"
- https://aws-quickstart.github.io/cdk-eks-blueprints/pipelines/#creating-a-pipeline - under `repository`, it should be `targetRevision` and not `branch`.
-

**Comment by shapirov103** [comment]
@youngjeong46  what is the issue with the first paragraph? We could drop the mention of the CDKv1 but CDKv2 is covered.

Second item: great catch 
It was fixed indirectly in [this PR](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/340/files#diff-778db8afe943ee8b2b7f3acf5ec1eb68d7bf0c926a1ddb46866125d1a4c0ce7f).

**Comment by youngjeong46** [comment]
I think we are okay with the first point, since it looks like the actual bootstrap commands are described in the latter section.

I'm good with closing the issue when the PR is merged.

**Comment by youngjeong46** [comment]
PR is Merged. Closing the issue.
