### ISSUE TITLE
[DOC][ADDON] - Addons Overview

### ISSUE THREAD

**Issue by youngjeong46** [aws-quickstart/cdk-eks-blueprints#328]
The following addons appear on the [official documentation addons page](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/), but not on the left Nav Bar: 

- EBS CSI Driver
- Keptn
- Kubecost
- Kubevious
- Karpenter
- Velero

**Comment by youngjeong46** [comment]
The following addons have documentations that are not published to the official site:

- Fluent Bit
- Node Termination Handler
- OPA

Nested Stacks Addon is missing documentations

**Comment by shapirov103** [comment]
addressed with https://github.com/aws-quickstart/cdk-eks-blueprints/pull/341

**Comment by youngjeong46** [comment]
Addressed in PR #345 . Closing the issue.
