### ISSUE TITLE
[BUG] teamManifestDir not working?

### ISSUE THREAD

**Issue by CarmenAPuccio** [aws-quickstart/cdk-eks-blueprints#333]
Reading the documentation for [teams](https://aws-quickstart.github.io/cdk-eks-blueprints/teams/), it doesn't seem like I can get the teamManifestDir working based off the instructions or copying the [patterns example](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/teams/team-riker/restrict-ingress-egress-riker.yaml)

My repo is [here](https://github.com/CarmenAPuccio/puccio-test-cluster/blob/main/lib/puccio-test-cluster-stack.ts). The namespace is created for the team but the [manifest](https://github.com/CarmenAPuccio/puccio-test-cluster/tree/main/lib/teams/team-puccio/manifests) is never applied.

**Comment by youngjeong46** [comment]
@CarmenAPuccio I was able to replicate the issue. I'm taking a look at the bug to ensure we are reading in the path correctly. Will let you know when the fix is in.

**Comment by shapirov103** [comment]
@CarmenAPuccio this is fixed in https://github.com/aws-quickstart/cdk-eks-blueprints/pull/365  and released.

**Comment by CarmenAPuccio** [comment]
Confirming it works now. Thanks so much!
