### ISSUE TITLE
[FEATURE] - Control Plane Logging Configuration

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/cdk-eks-blueprints#34]
Enable control plane logging by default.

**Comment by starchx** [comment]
@kcoleman731 ,  @AnjanaVaidyanathaIyer from our team is working on this and making good progress :)

**Comment by kcoleman731** [comment]
Awesome @starchx !

**Comment by youngjeong46** [comment]
This was completed on PR #267. Closing the issue.
