### ISSUE TITLE
[FEATURE] Support EKS 1.22

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#350]

**Comment by aceat64** [comment]
I tried testing this out myself but ran into problems with CDK.

Unfortunately CDK's lambda-layer-kubectl is not yet compatible with EKS/Kubernetes v1.22, so as of right now CDK has had to rollback support for v1.22. See https://github.com/aws/aws-cdk/pull/20000 for more info.

**Comment by shcherbak** [comment]
release date of eks 1.22 is April 4, 2022, 1.23 is planned for August, but we still can not upgrade using cdk

**Comment by shapirov103** [comment]
Is there an update for this or an issue for better tracking? We have requests for EKS 1.22 as part of [EKS Blueprints](https://github.com/aws-quickstart/cdk-eks-blueprints). Getting too close to 1.23.

**Comment by nthienan** [comment]
do we have any updates on this? @aceat64

**Comment by nthienan** [comment]
seems like there is not much progress on this

**Comment by vumdao** [comment]
@shapirov103 I see this PR was merged, any news for cdk-eks-blueprints?

**Comment by shapirov103** [comment]
> @shapirov103 I see this PR was merged, any news for cdk-eks-blueprints?

Indeed, it only took half a year to address the PR. However, while it is merged, it is not released yet. Here is the actual [released docs for 2.47](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.KubernetesVersion.html). You can see there is no latest EKS versions in the list. I expected the next release 2.48 to happen by end of this week to include it. Then we can test the blueprints.

**Comment by zxkane** [comment]
EKS 1.23 is supported by [CDK 2.49.0](https://github.com/aws/aws-cdk/releases/tag/v2.49.0). Hope this be resolved soon!

**Comment by vumdao** [comment]
@shapirov103 hope we will have release to cover CDK 2.49.0 soon ^^

**Comment by shapirov103** [comment]
@vumdao working on it.

**Comment by shapirov103** [comment]
This issue is resolved. I will keep it open for a bit to allow testing. Will close it out shortly.

**Comment by shapirov103** [comment]
Supporting 1.23 and 1.24 atm. closing.
