### ISSUE TITLE
[FEATURE][ADDONS][Cluster-Autoscaler] - Cluster Autoscaler should migrate to use IRSA and not instance profile

### ISSUE THREAD

**Issue by tsahiduek** [aws-quickstart/cdk-eks-blueprints#367]
Currently cluster-autoscaler rely on instance-profile to interact with AWS resources (autoscaling & ec2). 
Per Amazon EKS [docs](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html), the preferred method is to use IRSA (IAM Roles for ServiceAccount)

**Comment by youngjeong46** [comment]
PR is merged. Closing the issue.
