### ISSUE TITLE
Existing Cluster Constructs

### ISSUE THREAD

**Issue by gbvanrenswoude** [aws-quickstart/cdk-eks-blueprints#370]
Is the blueprints.ClusterAddOn usable on existing cdk eks.Cluster Constructs / ICluster interfaces? It would be awesome to be able to ship ClusterAddOns to existing clusters deployed using aws-cdk. I'm not sure if that is the point of the blueprints, but it would extend very nicely on top of people who code their own Clusters or have them already running.

**Comment by shapirov103** [comment]
I will add an example of importing an existing cluster and applying add-ons to them.

**Comment by gbvanrenswoude** [comment]
@shapirov103 Is it also possible to provide an example in the documentation on how to use blueprints in combination with existing eks.Cluster constructs?

e.g.

```ts
import { Cluster } from 'aws-cdk-lib/aws-eks';
<...>

export class InfrastructureStack extends Stack {
    private cluster: Cluster;

    constructor(scope: Construct, id: string, uniqueName: string, owner: nnOwner, featureBranchToggle: boolean, props?: StackProps) {
        super(scope, id, props);

        this.cluster = new eks.Cluster(this, 'eks', {...});
        <...use blueprint 'Construct' ClusterAddOn to build on top...>
```

**Comment by shapirov103** [comment]
Will add an item to show leveraging existing cluster and add add-ons / teams.
