### ISSUE TITLE
Provide examples to launch clusters with EC2 Spot Instances

### ISSUE THREAD

**Issue by chrismld** [aws-quickstart/cdk-eks-blueprints#379]
### Describe the feature

There are no explicit examples on how to create clusters using EC2 Spot Instances.

### Use Case

A set of examples with Spot instances when using managed node groups, self-managed node groups, and Karpenter.

### Other Information

I'm already working in the Terraform blueprint, so I plan to use similar examples for CDK.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.24.0

### Node.js Version

v16.13.2

### Environment details (OS name and version, etc.)

Mac Monterey

**Comment by shapirov103** [comment]
Great, we definitely need those. They may be more suitable for the patterns repo. We have a small example [here](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/generic-cluster-construct/index.ts#L30). But nothing with Karpenter and self-managed.

**Comment by christianhxc** [comment]
@shapirov103 should I create the examples in the pattern repository then? I'll need to change a few things in this repository so I'll keep this one.

**Comment by shapirov103** [comment]
@christianhxc yes, the example should be in the patterns repo, but should definitely document it better. So doc update here with the link to the pattern. Also please let me know what changes you would like to apply to the framework. I have just refactored both mng and asg nodegroup support to include more options, this will be merged very soon.

**Comment by christianhxc** [comment]
@shapirov103 I haven't looked in depth at this repo but I can tell you the changes I made for ASGs in the Terraform one: add support for mixed instance group policies, replicate Kubernetes labels into ASGs labels (cluster-autoscaler needs those to downscale to zero nodes if needed), a flag to enable capacity rebalance, and a variable to define the Spot allocation strategy.
