### ISSUE TITLE
Node Exporter Add-On

### ISSUE THREAD

**Issue by otterley** [aws-quickstart/cdk-eks-blueprints#380]
### Describe the feature

Create an add-on that installs Node Exporter on selected nodes.

### Use Case

Node metrics are valued both by cluster maintainers and developers.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

-

### Node.js Version

-

### Environment details (OS name and version, etc.)

-

**Comment by elamaran11** [comment]
We have implemented Node Exporter Addon. Closing this issue. Please create a new one for any issues on the same.
