### ISSUE TITLE
karpenter: policy missing DeleteLaunchTemplate

### ISSUE THREAD

**Issue by otterley** [aws-quickstart/cdk-eks-blueprints#381]
### Describe the bug

The IAM role policy associated with the Karpenter pod needs to be able to call `DeleteLaunchTemplate`, per the following reported error:

```
2022-05-13T03:09:42.540Z        ERROR   controller.aws.launchtemplate   Unable to delete launch template, UnauthorizedOperation: You are not authorized to perform this operation.
```

### Expected Behavior

-

### Current Behavior

-

### Reproduction Steps

-

### Possible Solution

Add `ec2:DeleteLaunchTemplate` to the role policy

### CDK CLI Version

-

### Node.js Version

-

### Environment details (OS name and version, etc.)

-

**Comment by otterley** [comment]
The full set of required permissions can be found here: https://github.com/aws/karpenter/blob/main/website/content/en/v0.8.2/getting-started/getting-started-with-eksctl/cloudformation.yaml

**Comment by jyidiego** [comment]
@otterley hi, I have a PR that fixes this [https://github.com/aws-quickstart/cdk-eks-blueprints/pull/389](url).
