### ISSUE TITLE
AWS Node Termination Handler supports MngClusterProvider either

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#387]
### Describe the feature

I would like to use MngClusterProvider as a cluster provider to install AWS NTH but got following error.

```
    assert(asgCapacity && asgCapacity.length > 0, 'AWS Node Termination Handler is only supported for self-managed nodes');
```

The reason is that `AsgClusterProvider` does not allow to specify node capacity type

### Use Case

Use spot instance capacity for EKS nodegroups

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.20.0

### EKS Blueprints Version

2.20.0

### Node.js Version

v16.13.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by vumdao** [comment]
@shapirov103 you might misunderstand this issue. 
When I create EKS blueprint and add `MngClusterProvider` at the `clusterProvider`, it's ok with out NTH add-on, but not ok when include NTH add as it raises the error 
```
    assert(asgCapacity && asgCapacity.length > 0, 'AWS Node Termination Handler is only supported for self-managed nodes');
```

What I expect here is that we can use `MngClusterProvider` at the `clusterProvider` for all add-ons. Why is there condition check that muse use `AsgProvider` when inclunding NTH Add-on?

**Comment by vumdao** [comment]
@shapirov103 You still think that we install NTH just to manage auto scaling groups, we use NTH to support using Karpenter instead.

**Comment by shapirov103** [comment]
@vumdao I understand the issue, I believe we have a similar one in https://github.com/aws-quickstart/cdk-eks-blueprints/issues/441. We will address.
