### ISSUE TITLE
Request Getting Started Doc typo fix

### ISSUE THREAD

**Issue by maxHyeon** [aws-quickstart/cdk-eks-blueprints#390]
### Describe the documentation issue

There is a typo in the command in the document. Please fix it.

---
npm install -g aws-cdk@2.20.0 # may require sudo (Ubuntu) depending on configuration
cdk --**verson** # must produce 2.20.0 Fix to cdk --version
mkdir my-blueprints
cd my-blueprints
cdk init app --language typescript
---

### Links

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/ab1ef622792af61a3d04bf09edd01a230219f548/docs/getting-started.md?plain=1#L28

**Comment by shapirov103** [comment]
Fixed in #391

**Comment by shapirov103** [comment]
Closing as addressed, happy to reopen if anything was missed .
