### ISSUE TITLE
Support AWS CodeCommit as pipeline source repository

### ISSUE THREAD

**Issue by ybezsonov** [aws-quickstart/cdk-eks-blueprints#402]
### Describe the feature

GitHub is currently the only supported source repository type for pipeline-stack.
AWS CodeCommit support as pipeline source repository could be useful for customers who want to have pipeline objects in AWS Cloud and don't want to use external repositories.

### Use Case

I don't want to store pipeline related objects in external gitHub repository and want to use AWS CodeCommit.
Usage of AWS CodeCommit can simplify environment creation during EKS Blueprints workshops.
CodeCommit repository can be created using cdk.

### Proposed Solution

Introduce optional parameter codeCommitProps, which can be used to define repoName/branch for AWS CodeCommit instead of owner/repository for GitHub. It will make solution backward compatible with the current implementation.

blueprints.CodePipelineStack.builder()
      .name("eks-blueprints-workshop-pipeline")
      // .owner("gitHubUserName")
      // .repository({
      //     repoUrl: 'my-eks-blueprints',
      //     credentialsSecretName: 'github-token',
      //     targetRevision: 'main' // default is "main"
      // })
      .codeCommitProps({
          repoName: 'eks-blueprint-cc' // CodeCommit repository name, should be in the same region with pipeline-stack
          //, branch: 'master' // optional, default is "master"
          //, options: CodeCommitSourceOptions // optional
      })
      .wave({
        id: "envs",
        stages: [
          { id: "dev", stackBuilder: blueprint.clone('us-west-2').addOns(devBootstrapArgo)}
        ]
      })
      .build(scope, id+'-stack', props);

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.25.0

### EKS Blueprints Version

1.0.1

### Node.js Version

16.15.0

### Environment details (OS name and version, etc.)

Cloud9

**Comment by shapirov103** [comment]
@ybezsonov this has been release some time ago. Is there anything pending on this feature? It would be nice to add a pattern, however, if no technical tasks left against this repository, I am willing to mark it as done.

**Comment by ybezsonov** [comment]
Yes, let's close it.
I'm going to create pattern for using CodeCommit as a pipeline source and a workloads repositories source. I already have some scripts/code and will need to create a description in the next two weeks.
