### ISSUE TITLE
Support deployment on Outposts

### ISSUE THREAD

**Issue by chainhead** [aws-quickstart/cdk-eks-blueprints#404]
### Describe the feature

How do we deploy a EKS cluster with worker nodes on Outposts?

### Use Case

Need this for a Telecom customer who wants some of workload to reside on their premises.

### Proposed Solution

Perhaps, a blue print the steps in this [blog post](https://aws.amazon.com/blogs/containers/deploying-containerized-application-on-aws-outposts-with-amazon-eks/).

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

latest

### EKS Blueprints Version

latest

### Node.js Version

v16.15.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by elamaran11** [comment]
Currently we dont have in backlog to support Outpost with Blueprints. Good recommendation though. You can still deploy all addons via Argo installation and using this repo. https://github.com/aws-samples/eks-blueprints-add-ons

Please close this issue if you are ok. 
@shapirov103 Thoughts?
