### ISSUE TITLE
GenericClusterProps:managedNodeGroups desiredSize not matching in console

### ISSUE THREAD

**Issue by daveschmidt86** [aws-quickstart/cdk-eks-blueprints#411]
### Describe the bug

In my GenericClusterProviderProps I specified a desiredSize for my managedNodeGroups to 4. After deploying the EKS console shows 3 not 4 EC2 instances.

### Expected Behavior

The desiredSize should match in the EKS console

### Current Behavior

Currently the count of EC2 managed nodes are off by one.

### Reproduction Steps

const clusterProvider = new blueprints.GenericClusterProvider({
    version: KubernetesVersion.V1_21,
    serviceIpv4Cidr: "10.43.0.0/16"
    managedNodeGroups: [
        {
            id: "mng1",
            amiType: NodegroupAmiType.AL2_X86_64,
            instanceTypes: [new InstanceType('m5.2xlarge')],
            minSize: 1,
            maxSize: 10
            desiredSize: 4
        }
   ]
}

### CDK CLI Version

2.20

### EKS Blueprints Version

1.0.0

### Node.js Version

16

### Environment details (OS name and version, etc.)

MacOS

**Comment by shapirov103** [comment]
@daveschmidt86  thank you for submitting the issue. 
I was not able to reproduce it with the versions you specified. Tried with 1.0.0 and 1.0.1 and different CDK versions as well.
There may be an issue related to the project setup that we can review.

**Comment by shapirov103** [comment]
@daveschmidt86 were you able to reproduce this after the initial occurence?

**Comment by elamaran11** [comment]
@daveschmidt86 Closing this issue as we have not heard back in 4 months. We couldnt reproduce the issue, if you still face issues, reopen the ticket.
