### ISSUE TITLE
Add HostedZone and ExternalDNS to end-to-end tests

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#415]
### Describe the feature

Currently ExternalDNS add-on is not covered by e2e tests. This caused issues when customers discovered failures of which the team was unaware (e.g. helm chart version 5.x were removed from bitnami). 

### Use Case

Customers need External DNS and proper QA process to make sure it does not break in customer environments.

### Proposed Solution

Add hosted zone to the Isengard account where e2e tests run. 
Add external DNS add-on to the [example blueprint](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/examples/blueprint-construct/index.ts) that is used for e2e tests 

### Other Information

There may be other approaches to QA.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.25.0

### EKS Blueprints Version

1.0.1

### Node.js Version

16.13

### Environment details (OS name and version, etc.)

Ubuntu 20

**Comment by elamaran11** [comment]
@shapirov103 I see we this is already in e2e. Can we close this ticket?
