### ISSUE TITLE
(karpenter addon): error provisioning new nodes

### ISSUE THREAD

**Issue by tusharf5** [aws-quickstart/cdk-eks-blueprints#426]
### Describe the bug

Get this error when kapenter tries to launch a new node.

ERROR	controller.provisioning	Launching node, creating cloud provider machine, getting launch template configs, getting launch templates, neither spec.provider.instanceProfile nor --aws-default-instance-profile is specified	{"commit": "c115db3", "provisioner": "default"}

### Expected Behavior

Karpenter should be able to provision new nodes.

### Current Behavior

pods go into pending state forever waiting for karpenter to create new nodes,

### Reproduction Steps

Normal blueprint cluster with the following karpenter props.

```ts
const props = {
        provisionerSpecs: {
          "node.kubernetes.io/instance-type": ["m5.large"],
          "topology.kubernetes.io/zone": this.node.tryGetContext(
            `availability-zones:account=${account}:region=${'us-west-2'}`
          ),
          "kubernetes.io/arch": ["amd64"],
          "karpenter.sh/capacity-type": ["on-demand"],
        },
        subnetTags: {
          [`karpenter.sh/discovery/cluster`]: `${env}-${config.projectName}`,
        },
        securityGroupTags: {
          [`karpenter.sh/discovery/cluster`]: `${env}-${config.projectName}`,
        },
      }
```      

### CDK CLI Version

2.29.1

### EKS Blueprints Version

1.0.2

### Node.js Version

v16.14.2

### Environment details (OS name and version, etc.)

Linux

**Comment by youngjeong46** [comment]
@tusharf5 Thanks for submitting the issue. This likely rose from the latest release which removed manual Instance Profile naming and therefore the Instance Profile is not being assigned properly using Helm. This issue is being fixed as part of the next Karpenter PR coming shortly.

**Comment by tusharf5** [comment]
Thanks for the update @youngjeong46 Looking forward to trying out the fix.
