### ISSUE TITLE
load balancer controller: serviceaccounts "aws-load-balancer-controller" already exists

### ISSUE THREAD

**Issue by tusharf5** [aws-quickstart/cdk-eks-blueprints#430]
### Describe the bug

Received response status [FAILED] from custom resource. Message returned: Error: 'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "aws-load-balancer-controller" already exists'

These are the logs.

```text
Running command: ['aws', 'eks', 'update-kubeconfig', '--role-arn', 'arn:aws:iam::xxxxxxxxxxx:role/dev-dev-blueprint-devblueprintCreationRole4B7B7FBC-1322RLGXKWTQF', '--name', 'dev-capstone', '--kubeconfig', '/tmp/kubeconfig']
--
Added new context arn:aws:eks:us-west-2:xxxxxxxxxxx:cluster/dev-capstone to /tmp/kubeconfig
[INFO]	2022-07-01T07:46:56.341Z	b05e6045-8815-45c7-ab77-0d3ebcd889f8	manifest written to: /tmp/manifest.yaml
[INFO]	2022-07-01T07:46:56.341Z	b05e6045-8815-45c7-ab77-0d3ebcd889f8	Running command: ['kubectl', 'create', '--kubeconfig', '/tmp/kubeconfig', '-f', '/tmp/manifest.yaml', '--save-config']
[ERROR] Exception: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "aws-load-balancer-controller" already exists\n'Traceback (most recent call last):  File "/var/task/index.py", line 14, in handler    return apply_handler(event, context)  File "/var/task/apply/__init__.py", line 64, in apply_handler    kubectl('create', manifest_file, *kubectl_opts)  File "/var/task/apply/__init__.py", line 91, in kubectl    raise Exception(output)
```

### Expected Behavior

Not sure, it should just override existing service account or something but not fail.

### Current Behavior

It fails, if I delete the service account manually and then deploy. Then it works.

### Reproduction Steps

It doesn't happen the first time your create the cluster since there is no service account. But anytime it has to update the service account it fails.

### CDK CLI Version

2.29.1

### EKS Blueprints Version

1.0.4

### Node.js Version

16.14

### Environment details (OS name and version, etc.)

macOS

**Comment by elamaran11** [comment]
Could you be more specific on what update you made after the initial cluster creation ?

**Comment by tusharf5** [comment]
Creating a brand new cluster or even updating one with the following configuration fails with the above error.

```typescript

    const albAddon = new blueprints.addons.AwsLoadBalancerControllerAddOn({
      enableWaf: true,
      enableWafv2: true,
      enableShield: true,
    });

    const builder = blueprints.EksBlueprint.builder()
      .name(`${config.projectName}-cluster`)
      .clusterProvider(cluster)
      .account(account)
      .addOns(
        vpcCniAddOn,
        secretsStoreAddon,
        karpenterAddon,
        ebsCsiAddon,
        albAddon, // this addon fails
        argoAddon
      );
 ```

**Comment by elamaran11** [comment]
We tried to recreate the issue. We used `aws-cdk` version as `2.29.1`  and `@aws-quickstart/eks-blueprints` version as `1.0.4`. We installed a brand new cluster with basic `AwsLoadBalancerControllerAddOn` addon and then we tried to update the `enableWaf`, `enableWafv2` to `true` in the update and we never ran in to the above issue. We used both `generic-cluster-construct` and `multi-team-construct` patterns and we didn't face this issue. I would recommend to try these patterns new from scratch and try to update and let us know if you still face the issue. If not please proceed to closing the ticket.

**Comment by tusharf5** [comment]
I'll try to install it again and see if it works.

**Comment by tusharf5** [comment]
It still gives me the same error. 

Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "aws-load-balancer-controller" already exists\n

Happy to jump on a call if required since I am using it for AWS capstone project.

**Comment by elamaran11** [comment]
Would you be able to share us detailed step by step procedure you are following to get to this error. We recommend to start with one of our sample patterns such as `generic-cluster-construct` and `multi-team-construct` and try to update the `AwsLoadBalancerControllerAddOn` addon and let us know when you are facing this issue so that we can try to recreate. Most important part is having able to recreate the issue. We can fix the issue once we recreate it.

**Comment by elamaran11** [comment]
@tusharf5 Closing this issue as we have not heard back in 4 months. Please reach back or reopen the ticket if you still face this issue.
