### ISSUE TITLE
(VPC CNI Addon): (VPC CNI Addon not creating required IAM Roles and not annotating the Service Account for the plugin to work)

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#434]
### Describe the bug

VPC CNI Addon is not working as per the documentation https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html
1. It does create the required IAM roles for IRSA to work.
2. It does not annotate the SA with right IAM Role.
3. Currently the plugin is not working as expected.

### Expected Behavior

VPC CNI Plugin should work as expected in the documentation - https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

### Current Behavior

VPC CNI Addon is not working as per the documentation :
1. It does create the required IAM roles for IRSA to work.
2. It does not annotate the SA with right IAM Role.
3. Currently the plugin is not working as expected.

### Reproduction Steps

Stand up new cluster, specified k8 version 1.21, vpc-cni addon preferably use the https://github.com/aws-samples/cdk-eks-blueprints-patterns/tree/main/lib/multi-team-construct

### Possible Solution

Rework on the VPC CNI plugin to get the addon working as expected.

### CDK CLI Version

2.29.0

### EKS Blueprints Version

1.0.4

### Node.js Version

18.4.0

### Environment details (OS name and version, etc.)

Amazon Linux.

**Comment by Feder1co5oave** [comment]
Currently the VpcCni add-on in the library inherits the node role, which by default has the `AmazonEKS_CNI_Policy` managed policy attached.

https://github.com/aws/aws-cdk/blob/cb7367965608eb733f7ae03a06419bba4b21c713/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L378-389

**Comment by elamaran11** [comment]
@Feder1co5oave Please follow the PR #594 for a solution to this Issue.

**Comment by elamaran11** [comment]
@Feder1co5oave We had the release today and also this issue is fixed now and we have enhanced the VPC CNI with advanced configurations addon. Please try again and reach back to us with any issues.
