### ISSUE TITLE
EFS CSI Driver Add-on: Undefined ECR Repo for ap-southeast-3 region

### ISSUE THREAD

**Issue by hendryanw** [aws-quickstart/cdk-eks-blueprints#437]
### Describe the bug

When deploying CDK EKS Blueprint on ap-southeast-3 (Jakarta) region:
1. CDK complained that is is unable to find the load-balancer controller for ap-southeast-3 region. 
2. EFS CSI driver - efs-plugin container is having invalid image URI e.g. `undefinedeks/aws-efs-csi-driver:v1.3.6`

It looks like it may be caused by missing entry for ap-southeast-3 region in `lib/utils/registry-utils.ts`

### Expected Behavior

For deployment to ap-southeast-3
1. CDK is able to find the image for the load-balancer controller
2. EFS CSI driver - efs-plugin image URI is pointed to correct repository as specified in the official [documentation](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html)

### Current Behavior

1. CDK complained that is is unable to find the load-balancer controller for ap-southeast-3 region.  `Unable to get ECR repository for AWS Loadbalancer Controller for region ap-southeast-3`. Then proceed to use the image from the repo in `us-west-2` e.g. `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.1`
2. EFS CSI driver - efs-plugin container is having invalid image URI e.g. `undefinedeks/aws-efs-csi-driver:v1.3.6`

### Reproduction Steps

Deploy EKS using blueprint into ap-southeast-3. [Getting started reference](https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/)

### Possible Solution

Adding entry for ap-southeast-3 in `lib/utils/registry-utils.ts`

### CDK CLI Version

2.25.0

### EKS Blueprints Version

1.0.4

### Node.js Version

14.15.4

### Environment details (OS name and version, etc.)

MacOS Monterey 12.4

**Comment by hendryanw** [comment]
Hi team, I am planning to submit a pull request for the fix for this issue. I will follow the contributor's guide. Will appreciate any further guidance :)

**Comment by shapirov103** [comment]
@hendryanw great and thank you! no specific guidance in addition to the guide. We currently don't test against ap regions, so please attach a successful run results to the PR: e.g. blueprint configuration, provisioned cluster and state of all pods.

**Comment by shapirov103** [comment]
Were you able to validate the fix with the latest release @hendryanw? I assume we can close it now.

**Comment by hendryanw** [comment]
Yes the fix has been validated, closing the issue now, thanks @shapirov103 !
