### ISSUE TITLE
EKS AddOns should be independent with ClusterProvider

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#447]
### Describe the feature

I'm using `AsgClusterProvider` and want to switch to `MngClusterProvider` but it got following error
```
Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "ebs-csi-control
ler-sa" already exists\n'
Resource handler returned message: "Addon vpc-cni cannot be updated as it is currently in UPDATING state (Service: Eks, Status Code: 409, Request ID: 2acca979-f60f-498f-bee5-f0a30dbdd674)" (Re
questToken: 9cc78065-7d29-5bba-a374-993876d8a57d, HandlerErrorCode: AlreadyExists)
The stack named DevEksClusterselvcd1eksblueprintF8115751 failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [vpccniaddOn, selvcd1eksblueprintAwsAuthmanifestF8A303AB, selvcd1eksblueprintchartmetricsserverD3636660]. ): Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "ebs-csi-controller-sa" already exists\n'
    at async Runtime.handler (/var/task/cfn-response.js:1:1474) (RequestId: 14f89106-a37d-43ef-bd80-009b534a50c2), Resource handler returned message: "Addon vpc-cni cannot be updated as it is currently in UPDATING state (Service: Eks, Status Code: 409, Request ID: 2acca979-f60f-498f-bee5-f0a30dbdd674)" (RequestToken: 9cc78065-7d29-5bba-a374-993876d8a57d, HandlerErrorCode: AlreadyExists)
```

### Use Case

Switching between node group types such as `AsgClusterProvider` and `MngClusterProvider`

### Proposed Solution

The flow should be
1. Keep Current cluster provider `AsgClusterProvider`
2. Create new `MngClusterProvider`
3. Destroy the old one `AsgClusterProvider`

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.33.0

### EKS Blueprints Version

1.1.0

### Node.js Version

v16.13.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by elamaran11** [comment]
@vumdao We have updated the VPC CNI addon with advanced configurations totally revamped. Do you mid checking on this gain and let us know if you see this issue again.

**Comment by elamaran11** [comment]
@vumdao DO you still see the issue or we can close the issue.

**Comment by vumdao** [comment]
Thanks @elamaran11 I have new EKS with `MngClusterProvider` so not able to test this case now. I close this ticket
