### ISSUE TITLE
CloudWatch Xray Addon

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#453]
### Describe the feature

The AWS Distro for OpenTelemetry (ADOT) Collector can be deployed to receive OTLP metrics for export to Amazon CloudWatch.

### Use Case

This enables a simplified experience for instrumenting your applications running on Amazon EKS to send metric and trace data to multiple monitoring service options like [Amazon CloudWatch](https://console.aws.amazon.com/cloudwatch).

### Proposed Solution

New CloudWatch Addon to remote write metrics to CloudWatch console using ADOT Addon.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.33

### EKS Blueprints Version

1.1.0

### Node.js Version

18.6.0

### Environment details (OS name and version, etc.)

mac

**Comment by elamaran11** [comment]
PR #455

**Comment by youngjeong46** [comment]
Closing the issue as the feature is implemented as an addon.
