### ISSUE TITLE
Enhancing `CoreAddon` with Newer features.

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#454]
### Describe the feature

Enhancing CoreAddon to support Installation of New Addons with following :

Making Version Property Optional to support upcoming Addons Such as ADOT which does have a version number parameter. Also adding a logic to make sure addon creation works with or without version field.
Adding a new field saName to make sure CoreAddon does not populate the AddonName with SA Name. Some Addons require a separate saName for the addon to work perfectly.
Adding a new field namespace field to support creation of Service Accounts in required namespace. Today all Service Accounts needs by Addons are created in kube-system namespace.

### Use Case

Enables us to support new EKS Addons and Observability Addons such as AMP, CloudWatch, Xray.

### Proposed Solution

Enhancing CoreAddon to support Installation of New Addons with following :

Making Version Property Optional to support upcoming Addons Such as ADOT which does have a version number parameter. Also adding a logic to make sure addon creation works with or without version field.
Adding a new field saName to make sure CoreAddon does not populate the AddonName with SA Name. Some Addons require a separate saName for the addon to work perfectly.
Adding a new field namespace field to support creation of Service Accounts in required namespace. Today all Service Accounts needs by Addons are created in kube-system namespace.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.33

### EKS Blueprints Version

1.1.0

### Node.js Version

18.6.0

### Environment details (OS name and version, etc.)

mac

**Comment by shapirov103** [comment]
@elamaran11 I assume this has been addressed and published in 1.1.0 and 1.2.0, correct?

**Comment by elamaran11** [comment]
@shapirov103 Yes this is addressed now.

**Comment by elamaran11** [comment]
Closing this issue @shapirov103
