### ISSUE TITLE
Backstage Addon

### ISSUE THREAD

**Issue by blandes** [aws-quickstart/cdk-eks-blueprints#456]
### Describe the feature

This is a new feature to introduce Backstage Addon to AWS CDK EKS Blueprints.

This Addon deploys Backstage deployment with Aurora/Postgres. https://github.com/vinzscam/backstage-chart

### Use Case

This enables a developer experience for instrumenting your applications running on Amazon EKS. https://backstage.io/

### Proposed Solution

New Backstage Addon that implements a scalable Backstage deployment with Aurora/Postgres.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.33

### EKS Blueprints Version

1.10

### Node.js Version

18.6.0

### Environment details (OS name and version, etc.)

Mac

**Comment by elamaran11** [comment]
This addon is implemented already. Please reachout with a new issue, if you see problems with the addon. Also we will be having a pattern soon in patterns repo;
