### ISSUE TITLE
Broken links in EKS blueprints workshop

### ISSUE THREAD

**Issue by davidpc** [aws-quickstart/cdk-eks-blueprints#458]
### Describe the documentation issue

Links to external documentation for Teams, Applications, Add-ons, Pipelines... are broken

### Links

https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/010-introduction/1-what-is-eks-ssp/archdiagram

**Comment by youngjeong46** [comment]
@davidpc - I appreciate you submitting the issue.

The workshop team took a look and revised broken links as they appear on the main page. Please take a look and make sure we didn't miss anything. I can close the issues once you can confirm.

**Comment by davidpc** [comment]
@youngjeong46 - it looks ok now, thank you

**Comment by youngjeong46** [comment]
Closing the issue as resolved.
