### ISSUE TITLE
(Bastion Support)

### ISSUE THREAD

**Issue by tlindsay42** [aws-quickstart/cdk-eks-blueprints#459]
Reviving #41 to track interest in adding a bastion host add-on because a partner asked for this today. Please add a 👍 to this comment and describe your use case if you're interested in this feature.

**Comment by youngjeong46** [comment]
@tlindsay42 Thank you for submitting the issue. Is there a particular need or use case for using Bastion Host over managing the instances with SSM Agents? SSM is available via add-on.

**Comment by shapirov103** [comment]
SSM is also available with latest Amazon EKS AMIs. SSM add-on should be leveraged for custom AMI. Other than kubectl access which is possible with SSM and we describe [here](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/ssm-agent/#use-case-private-clusters) is any other use case that is not addressed?
