### ISSUE TITLE
Explain how to import and existing VPC

### ISSUE THREAD

**Issue by L-U-C-K-Y** [aws-quickstart/cdk-eks-blueprints#478]
### Describe the documentation issue

Hi all

I have been trying to deploy a new EKS cluster based on these amazing blueprints to replace our existing cluster that we have created through the regular CDK.

With the previous cluster, we have passed our private and public VPC as an argument and used it as a param while creating the cluster.
Now I am trying to achieve the same with the EKS builder/blueprints, but I am struggling to re-use existing vpc.

Would appreciate any help!

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/

**Comment by pflorek** [comment]
Had yesterday a similiar problem: https://github.com/aws-quickstart/cdk-eks-blueprints/issues/481

```typescript
blueprints.EksBlueprint.builder()
      .addOns(...addOns)
      .clusterProvider(clusterProvider)
      .resourceProvider(blueprints.GlobalResources.Vpc, new blueprints.VpcProvider(props.vpc.vpcId))
      .build(scope, id, props);
```

**Comment by shapirov103** [comment]
@L-U-C-K-Y  the solution provided by @pflorek is exactly right. However, if you want to provide a custom implementation of how VPC is either created or looked up you can use your own implementation of `ResourceProvider`. See more info [here](https://aws-quickstart.github.io/cdk-eks-blueprints/resource-providers/).

You can also leverage `DirectVpcProvider` and use a VPC provisioned in a different stack:

```typescript
blueprints.EksBlueprint.builder()
    //  Specify VPC for the cluster (if not set, a new VPC will be provisioned as per EKS Best Practices)
    .resourceProvider(GlobalResources.VPC, new blueprints.DirectVpcProvider(myVpc)
```

**Comment by L-U-C-K-Y** [comment]
@shapirov103 @pflorek  many thanks for your answers!

I just tried it out and I am getting the following error:

```typescript
Error: You cannot add a dependency from 'EKSStackPrd/EKSStackPrd/Role/Resource' (in the App) to 'VPCStackPrd/VPCStackPrd/Resource' (in the App): dependency cannot cross stage boundaries
```

With the following code:

```typescript
blueprints.EksBlueprint.builder()
      .account(this.account)
      .region(this.region)
      .addOns(...addOns)
      .resourceProvider(GlobalResources.Vpc, new blueprints.DirectVpcProvider(props.vpc))
      .build(app, `EKSStackPrd`);
````

Much appreciated!

**Comment by shapirov103** [comment]
@L-U-C-K-Y why do you need an EKSStackPrd? It should be the stack of its own. 

I was thinking:

```typescript
const app = new App();

const vpcStackPrd = new VPCStackPrd(
      app, // make sure you specify account and region here
);

blueprints.EksBlueprint.builder()
      .account(this.account)
      .region(this.region)
      .addOns(...addOns)
      .resourceProvider(GlobalResources.Vpc, new blueprints.DirectVpcProvider(vpcStackPrd.vpc))
      build(app, `EKSStackPrd`);
```
