### ISSUE TITLE
(cluster-providers): How to configure a cluster secrets encryption

### ISSUE THREAD

**Issue by pflorek** [aws-quickstart/cdk-eks-blueprints#482]
### Describe the bug

How do I configure a `SecretsEncryptionKey`in the scope of the EksBlueprint stack?

With the plain AWS CDK EKS module I did the following:

```typescript
    const secretsEncryptionKey = new kms.Key(stack, "Key", {
      removalPolicy: RemovalPolicy.RETAIN,
      alias: "my-cluster",
    });


    this.cluster = new eks.Cluster(stack, "Cluster", {
      secretsEncryptionKey: secretsEncryptionKey,
      ...
    });

```

What's the recommended way to do so?

### Expected Behavior

I can configure the `secretsEncryptionKey` in the scope of the EksBlueprint stack

### Current Behavior

I have to create another stack upfront, then pass the `secretEncryptionKey` to the ClusterProvider

### Reproduction Steps

```typescript
    const secretsEncryptionKey = new kms.Key(stack, "Key", {
      removalPolicy: RemovalPolicy.RETAIN,
      alias: "my-cluster",
    });


    this.cluster = new eks.Cluster(stack, "Cluster", {
      secretsEncryptionKey: secretsEncryptionKey,
      ...
    });

```

### Possible Solution

Create a resource provider?
Don't create a stack by `EksBlueprint.builder().build()`, instead create a construct

### CDK CLI Version

2.37.1

### EKS Blueprints Version

1.2.0

### Node.js Version

18.7.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by shapirov103** [comment]
@pflorek 
I will take a look at registering resource providers for resources that are either created or looked up for cluster creation. 

At the moment you can apply standard OO extension mechanism:

1. Create a custom cluster provider by extending GenericClusterProvider.  E.g. `EncryptedClusterProvider extends GenericClusterProvider (props: EncryptedClusterProviderProps extends GenericClusterProviderProps)`
2. Override method `internalCreateCluster`
3. Create a new clusterOptions object by cloning the `clusterOptions` parameter and setting the `secretEncryptionKey` to the desired value.  You can scope to look up or create new kms key. 

You can control the shape of your cluster entirely with this method, however agree with the premise for this issue and will address.

**Comment by pflorek** [comment]
```typescript
import * as blueprints from "@aws-quickstart/eks-blueprints";
import { RemovalPolicy } from "aws-cdk-lib";
import * as eks from "aws-cdk-lib/aws-eks";
import * as kms from "aws-cdk-lib/aws-kms";
import { Construct } from "constructs";

export class MngClusterProvider extends blueprints.MngClusterProvider {
  protected internalCreateCluster(scope: Construct, id: string, clusterOptions: any): eks.Cluster {
    clusterOptions.secretsEncryptionKey = new kms.Key(scope, "Key", {
      removalPolicy: RemovalPolicy.RETAIN,
      alias: "mender/cluster",
    });

    return super.internalCreateCluster(scope, id, clusterOptions);
  }
}
```
