### ISSUE TITLE
Workshop Still Requires Deployment to US-West-2 Only

### ISSUE THREAD

**Issue by atari1050** [aws-quickstart/cdk-eks-blueprints#492]
### Describe the documentation issue

According to this link: https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/020-setup/self-paced/1-create-workspace
Only the Oregon (us-west-2) is available for the CDK EKS Blueprints deployment.  However, developers report that it is available in all US regions now.  

Text box containing warning: 
This workshop was designed to run in the Oregon (us-west-2) region. Please don't run in any other region. Future versions of this workshop will expand region availability, and this message will be removed.

### Links

https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/020-setup/self-paced/1-create-workspace

**Comment by youngjeong46** [comment]
@atari1050 Yes - that is a specific language for AWS Event (as we have tested in those specific regions to ensure best quality event driven experience). One thing to note is that we have not tested all of the possible region combinations for pipelines - so for anyone running the workshop in their own machine/Cloud9, experiences can vary.

At the minimum, we will review and loosen up on the restrict language.

**Comment by youngjeong46** [comment]
This is in progress - we are currently testing the provisioning code in regards to region pipeline assignment for Workshop Studio.

**Comment by youngjeong46** [comment]
@atari1050 - per the requirements of Workshop Studio, at this time we are only able to select 1 region for deployment of our template (US-WEST-2). When the option is available to select multiple regions for deployment, we will revisit this issue. Closing it for now.
