### ISSUE TITLE
[KarpenterAddOn] Expose Karpenter InstanceProfile

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#494]
### Describe the documentation issue

EKS blueprints default create karpenter instance profile when adding Karpenter Add-on. How can we get the instance profile name so that we can include it in karpenter provisioner as `provider.instanceProfile` ?

### Links

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/docs/addons/karpenter.md

**Comment by youngjeong46** [comment]
@vumdao I am exposing the Instance Profile name as a CloudFormation output in the PR that I am working on. Will that resolve the issue?

**Comment by vumdao** [comment]
Hi @youngjeong46 Thanks for your commit, it turned out we need to expose the karpenter role name or at least set karpenter instance profile name same as role name, otherwise, we are not able to update the policy in the instance profile

**Comment by youngjeong46** [comment]
@vumdao That makes sense. Let me look into exposing the role name. Does Cfn Output as we have done before work?

**Comment by vumdao** [comment]
Thanks @youngjeong46 for your reply, I got following error when trying to import the instance profile
```
DevEksClustersind1deveksblueprintCA71CA65 |   0 | 5:06:29 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | DevEksClustersind1deveksblueprintCA71CA65 No export named KarpenterInstanceProfilename found
```

The code: `const karpenterInstanceProfile = Fn.importValue('KarpenterInstanceProfilename');`

**Comment by vumdao** [comment]
@youngjeong46 `Export name` must be defined in order to import the value

**Comment by youngjeong46** [comment]
@vumdao we have exposed the export name as `KarpenterNodeRoleName` and `KarpenterInstanceProfileName`. Please re-open the ticket if not resolved. Closing for now.
