### ISSUE TITLE
(addons aws-calico): Calico uses deprecated chart

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#495]
### Describe the bug

According to AWS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) and [eks-charts](https://github.com/aws/eks-charts/tree/master/stable/aws-calico) repo, the helm chart referenced by `calico` add-on has been deprecated and no longer maintained. 

### Expected Behavior

Use the recommended [Calico Operator](https://github.com/tigera/operator) instead.

### Current Behavior

N/A

### Reproduction Steps

N/A

### CDK CLI Version

any

### EKS Blueprints Version

latest

### Node.js Version

any

### Environment details (OS name and version, etc.)

any

**Comment by askulkarni2** [comment]
Also see https://github.com/aws-samples/eks-blueprints-add-ons/pull/78

**Comment by shapirov103** [comment]
Please see the above comment. The deprecated add-on will be removed in a few releases.
