### ISSUE TITLE
Node Exporter Addon.

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#498]
### Describe the feature

Node Exporter addon helps enhancing the observability of our EKS Cluster by measuing various node resources such as memory, disk and CPU utilization.

### Use Case

Node Exporter addon helps enhancing the observability of our EKS Cluster by measuing various node resources such as memory, disk and CPU utilization.

### Proposed Solution

New addon for Node Explorter

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.37

### EKS Blueprints Version

1.2.0

### Node.js Version

v18.7.0

### Environment details (OS name and version, etc.)

mac

**Comment by shapirov103** [comment]
Duplicate of #380
