### ISSUE TITLE
VPC properties customisation

### ISSUE THREAD

**Issue by hit0ri** [aws-quickstart/cdk-eks-blueprints#512]
### Describe the feature

It would be nice to have an option to adjust VPC properties that is being created by the blueprint

### Use Case

I have a customer that needs an EKS cluster in a VPC with a specific CIDR. Currently, I don't see an option to specify VPC properties

### Proposed Solution

Add a method (e.g. `EksBlueprint.withVpcProps`) that will pass properties to the `ec2.Vpc`

### Other Information

I'm fairly new to CDK and TypeScript, so please let me know if I somehow missed how to do it properly

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.43.1

### EKS Blueprints Version

1.3.0

### Node.js Version

v16.17.1

### Environment details (OS name and version, etc.)

macOS 12.6

**Comment by elamaran11** [comment]
Closing this ticket. This is already implemented.
