### ISSUE TITLE
(HelmAddOn): Open for deployment configuration

### ISSUE THREAD

**Issue by pflorek** [aws-quickstart/cdk-eks-blueprints#515]
### Describe the feature

Currently the [HelmChartProps](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-eks.HelmChart.html#construct-props) are split into `HelmAddOnUserProps` and `HelmChartDeployment`.  Add `HelmChartDeployment` to `HelmAddOnUserProps` and give the user the ability to configure the `HelmChartProps`

### Use Case

As a user I sometimes need to configure the HelmChartProps i.e. `wait: true` or `timeout: 15m`

### Proposed Solution

The `HelmChartDeployment` are internally used by `HelmAddOn.addHelmChart` on the `KubectlProvider` and closed for change.

As a user it would be great to pass all the HelmChartProps like using the plain EKS CDK module. So I can use the quickstart and gradually configure the AddOn fully to my needs.

### Other Information

There is a bug https://github.com/aws-quickstart/cdk-eks-blueprints/issues/509 where I forgot deployment configuration and I now forced to deploy in several deployment steps, because the `HelmChartProps` are not fully configurable from outside

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.37.1

### EKS Blueprints Version

1.3.0

### Node.js Version

18.7.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pflorek** [comment]
@Mr-istov maybe this could also help you

**Comment by Mr-istov** [comment]
> @Mr-istov maybe this could also help you

Yes, this feature would be amazing, I think other addons would benefit from it as well.
Thank you!
