### ISSUE TITLE
Deploy multiple clusters using NestedStack

### ISSUE THREAD

**Issue by praveenperera** [aws-quickstart/cdk-eks-blueprints#520]
### Describe the feature

I would like to have one stack for example: StagingStack, that contains two blueprint clusters (1 in us-east-1, 1 in europe). And have them both deploy as a single stack. I think if blueprints were NestedStacks instead of Stacks this could work?

### Use Case

Multi region cluster deployments

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.47

### Node.js Version

16.15

### Environment details (OS name and version, etc.)

macOS 12.6

**Comment by shapirov103** [comment]
@praveenperera Grouping of stacks for deployment pipeline is generally recommended with the waves feature of pipelines: https://aws-quickstart.github.io/cdk-eks-blueprints/pipelines/#adding-waves
With this you can define a staging wave and add two clusters to it.
Depending on the use case (is it for demo purposes or a real customer use case), I will think about approaches to implement this feature.

**Comment by praveenperera** [comment]
This is a real customer use case (production and staging clusters in multiple regions). i think the waves feature will work for me. I will try it out and let you know how it goes. I appreciate the help.

**Comment by praveenperera** [comment]
@shapirov103 

On second thought I'm not sure this would work. For the stacks, I create the VPC separately and pass it as a `DirectVpcProvider`. I do this because in some regions we only need 1 AZ for that region. 

It looks a little like this:

ProductionClusterSystemStack
 - 1 "master" cluster (us-east-1)
 - 1 "secondary" cluster (eu-central-1)
 - 1 "regional" (1 AZ) cluster (ap-northeast-3)
 - 1 "regional" (1 AZ) cluster (ap-south-1)
 
StagingClusterSystemStack
 - 1 "master" cluster (us-east-1)
 - 1 "secondary" cluster (eu-central-1)
 
 I'd like to deploy all the clusters fro Production as one stack and all the clusters for Staging as one stack. I think NestedStack would work for this.
