### ISSUE TITLE
eks: support for Kubernetes version 1.23

### ISSUE THREAD

**Issue by softmates** [aws-quickstart/cdk-eks-blueprints#523]
### Describe the feature

I want to upgrade eks cluster to 1.23. AWS_CDK has already fixed the issue please refer https://github.com/aws/aws-cdk/releases/tag/v2.49.0

### Use Case

Upgraded EKS cluster to latest 

### Proposed Solution

Please upgrade the dependent aws-cdk version from 2.43  to v2.49.0

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.43.0

### EKS Blueprints Version

1.3.0

### Node.js Version

v18.7.0

### Environment details (OS name and version, etc.)

mac os

**Comment by armujahid** [comment]
BTW. EKS [1.24](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/) is now available. Should we create a separate issue for its support or should we keep this issue open?

**Comment by shapirov103** [comment]
@armujahid current version of CDK does not have this support ootb. 

The approach that you could take is to pass the version as `KubernetesVersion.of("1.24")`.

We can apply a change to use 1.23 kubectl layer which I assume will be compatible after testing for all versions above 1.21. 

In the meanwhile you can subclass the GenericClusterProvider (or any other provider) and override the `protected getKubectlLayer(scope: Construct, version: eks.KubernetesVersion) : ILayerVersion | undefined` method to return something like `return new KubectlV23Layer(scope, "kubectllayer23");` if version is 1.24 and above.

**Comment by vumdao** [comment]
@shapirov103 CDK just supports EKS v1.24 in [v2.54.0](https://github.com/aws/aws-cdk/releases/tag/v2.54.0)
Is it possible to upgrade to EKS 1.24 using blueprints?

**Comment by armujahid** [comment]
@vumdao [issue related to blueprint v1.24 support ](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1177) is currently open and is in their roadmap.
