### ISSUE TITLE
npm build: typescript version wrong

### ISSUE THREAD

**Issue by tyyzqmf** [aws-quickstart/cdk-eks-blueprints#526]
### Describe the bug

reference: [https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/030-single-eks-cluster/031-create-a-cluster/1-create-a-cdk-project](https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/030-single-eks-cluster/031-create-a-cluster/1-create-a-cdk-project)

1. `npm run build` error
2. blueprints pipeline build stage also error

Error Info:
```
Admin:~/environment/my-eks-blueprints (master) $ npm run build

> my-eks-blueprints@0.1.0 build
> tsc

node_modules/@types/lodash/common/object.d.ts:1025:21 - error TS1110: Type expected.

1025         : K extends `${number}`
                         ~~~

node_modules/@types/lodash/common/object.d.ts:1026:19 - error TS1005: ':' expected.

1026             ? '0' extends keyof T
                       ~~~~~~~

node_modules/@types/lodash/common/object.d.ts:1026:33 - error TS1005: ';' expected.

1026             ? '0' extends keyof T
                                     ~

node_modules/@types/lodash/common/object.d.ts:1028:22 - error TS1005: ';' expected.

1028             : number extends keyof T
                          ~~~~~~~

node_modules/@types/lodash/common/object.d.ts:1028:36 - error TS1005: ';' expected.

1028             : number extends keyof T
                                        ~
```

### Expected Behavior

build

### Current Behavior

build error

### Reproduction Steps

```
mkdir my-eks-blueprints
cd my-eks-blueprints
cdk init app --language typescript
npm i @aws-quickstart/eks-blueprints
npm run build
```

### Possible Solution

`npm i typescript@latest`

### CDK CLI Version

2.43.0 (build 487870a)

### EKS Blueprints Version

1.3.0

### Node.js Version

v16.18.0

### Environment details (OS name and version, etc.)

cloud9(aws-cli/1.24.10 Python/3.6.12 Linux/4.14.294-150.533.amzn1.x86_64 botocore/1.26.10)

**Comment by youngjeong46** [comment]
@tyyzqmf Thank you for submitting the issue. I've replicated the issue (for single cluster deployment, pipelines are currently in test) and will investigate the issue ASAP.

**Comment by shapirov103** [comment]
@tyyzqmf  given that `cdk init` produces an incompatible version of typescript, this will be initially addressed with documentation. 
The current steps to install:

```typescript
npm install typescript@~4.8.4
cdk init app --language typescript
```

We will be addressing this issue in the long run by supplying a [GitHub template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) that we validate on our CI.

**Comment by youngjeong46** [comment]
@tyyzqmf we are working to document the workshop with what @shapirov103 mentioned above, and will test to ensure that it works correctly. I will let you know when that is finished so you can test it out.

**Comment by shapirov103** [comment]
Getting started is updated: https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/ 
@youngjeong46 we can close it out once the workshop instructions are fixed, unless there is a separate tracking for the workshop updates.

**Comment by youngjeong46** [comment]
The workshop instructions are fixed as shown [here](https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/030-single-eks-cluster/031-create-a-cluster/1-create-a-cdk-project#2.-install-the-dependencies) and [here](https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/040-multiple-clusters-pipelines/041-create-a-pipeline/1-create-a-cdk-project#2.-install-the-dependencies). Closing the issue for now. @tyyzqmf please re-open the issue if you see any lingering errors.
