### ISSUE TITLE
(external-secrets-addon): Wait for CRDs to be created

### ISSUE THREAD

**Issue by praveenperera** [aws-quickstart/cdk-eks-blueprints#529]
### Describe the bug

```
Received response status [FAILED] from custom resource. Message returned: Error: b'error: unable to recognize "/tmp/mani
fest.yaml": no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1beta1"\n'
```

Getting an error when I launch a cluster with a `ClusterSecretStore`. I am assuming this is because the `ClusterSecretStore` gets created before the external-secrets-addon is deployed with its CRDs.

### Expected Behavior

Deploy without errors.

### Current Behavior

Errors out and rollsback entire cluster

### Reproduction Steps

```typescript
    this.addOns = [
      new blueprints.addons.CalicoOperatorAddOn(),
      new blueprints.addons.MetricsServerAddOn(),
      new blueprints.addons.ClusterAutoScalerAddOn(),
      new blueprints.addons.AwsLoadBalancerControllerAddOn({
        enableWaf: false,
        createIngressClassResource: true,
      }),
      new blueprints.addons.VpcCniAddOn(),
      new blueprints.addons.CoreDnsAddOn("v1.8.7-eksbuild.2"),
      new blueprints.addons.KubeProxyAddOn(),
      new blueprints.addons.NginxAddOn(),
      new blueprints.addons.EbsCsiDriverAddOn(),
      new blueprints.addons.ExternalsSecretsAddOn({}),
      new CertManagerAddOn({
        installCRDs: true,
        createNamespace: true,
        serviceAccountPolicies: [iam.certManagerIAMPolicy(this)],
        values: { serviceAccount: { create: false, name: "cert-manager" } },
      }),
    ];

    const clusterProvider = new blueprints.MngClusterProvider({
      clusterName: clusterName,
      version: KubernetesVersion.V1_23,
    })

    this.blueprint = blueprints.EksBlueprint.builder()
      .clusterProvider(clusterProvider)
      .resourceProvider(
        blueprints.GlobalResources.Vpc,
        new blueprints.DirectVpcProvider(vpc)
      )
      .addOns(...this.addOns)
      .build(this, this.clusterName, { env: awsEnv });

    this.blueprint.getClusterInfo().cluster.addManifest("ClusterSecretStore", {
      apiVersion: "external-secrets.io/v1beta1",
      kind: "ClusterSecretStore",
      metadata: { name: "default" },
      spec: {
        provider: {
          aws: {
            service: "SecretsManager",
            region: this.config.region,
            auth: {
              jwt: {
                serviceAccountRef: {
                  name: "external-secrets-sa",
                  namespace: "external-secrets",
                },
              },
            },
          },
        },
      },
    });
```

### CDK CLI Version

2.50.0 (build 4c11af6)

### EKS Blueprints Version

1.4.0

### Node.js Version

v16.17.1

### Environment details (OS name and version, etc.)

MacOS 12.6 (21G115)

**Comment by shapirov103** [comment]
@praveenperera this is a common with CDK (as well as CloudFormation). When you add a manifest like that, the provisioning of this resources starts happening in parallel with the rest of the provisioning, unless you declare a dependency. 
You can declare a dependency on external secrets add-on using our dependency mechanism described here: https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#add-on-dependencies

The best approach is to create a simple private addon that will create ClusterSecretStore, e.g. something like described here: https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#private-extensions

You can also get the dependency info by using `.getClusterInfo().getProvisionedAddOn("ExternalDnsAddOn")` . This will return a construct that you can leverage with the manifest construct like
```
const manifest = cluster.addManifest(...);
manifest.node.addDependency(clusterInfo.getProvisionedAddOn("<addonname>");
```

**Comment by praveenperera** [comment]
@shapirov103 that makes sense thanks. Can `.getClusterInfo().getProvisionedAddOn("ExternalDnsAddOn")` be used after the blueprint build or can it only be used in an addon?

**Comment by praveenperera** [comment]
Alright I will do that, thanks
