### ISSUE TITLE
Xray AddOn using old apiVersion of ClusterRoleBinding 

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#534]
### Describe the bug

The daemonset manifest [xray-ds.yaml](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/xray/xray-ds.yaml) use `apiVersion: rbac.authorization.k8s.io/v1beta1` for creating `ClusterRoleBinding` which cause adding Xray AddOn in EKS v1.23 failed

```
Received response status [FAILED] from custom resource. Message returned: Error: b'daemonset.apps/xray-daemon created\nconfigmap/xray-config created\nservice/xray-service created\nerror: unable to recognize "/tmp/manifest.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"\n' 

Logs: /aws/lambda/DeployDev-sel-vc-d1-dev-eks-bluepr-Handler886CB40B-h954A8KfTkdY 
at invokeUserFunction (/var/task/framework.js:2:6) 
at processTicksAndRejections (internal/process/task_queues.js:95:5) 
at async onEvent (/var/task/framework.js:1:365) 
at async Runtime.handler (/var/task/cfn-response.js:1:1543)
```

### Expected Behavior

Adding Xray Addon successfully on EKS v1.23

### Current Behavior

Failed

### Reproduction Steps

Add Xray AddOn to EKS v1.23 builders()

### CDK CLI Version

2.50.0

### EKS Blueprints Version

1.4.0

### Node.js Version

v18.9.1

### Environment details (OS name and version, etc.)

macOS 13

**Comment by shapirov103** [comment]
@vumdao please consider migrating to the ADOT XRay add-on: https://aws-quickstart.github.io/cdk-eks-blueprints/addons/xray-adot-addon/

I will take a look at the DS issue, and potentially deprecate the xray add-on, however acknowledge the defect.

**Comment by elamaran11** [comment]
@vumdao Did you check on ADOT XRay addon. We will depracate XRay addon soon.

**Comment by elamaran11** [comment]
@vumdao XRay Addon is now refreshed with latest guidance. Please check the latest addon, try out and let us know if you have questions. Closing this issue.
