### ISSUE TITLE
code-pipline.js: "npm install" will fail in CodeBuild "INSTALL" stage, after npm upgrade to 9.1.1

### ISSUE THREAD

**Issue by bigben80** [aws-quickstart/cdk-eks-blueprints#535]
### Describe the bug

On Nov 9th, npm has new 9.1.1 available online. this new version is automatically populated into aws codebuild docker image(https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard).

Unfortunatelly, this new version of npm will cause failure when installing dependencies(executing command "npm install" after aws-cdk@2.43.0 be installed)

### Expected Behavior

Dependencies should be installed, codebuild should continue to execute "npm run build", "npx cdk synth", ....

### Current Behavior

After Nov 9th(npm latest version update to 9.1.1), in CodeBuild phase "INTALL", command "npm install" will fail. error message like below

_

> 22 | [Container] 2022/11/11 08:48:58 Entering execCommands
> 23 | [Container] 2022/11/11 08:48:58 Entering phase INSTALL
> 24 | [Container] 2022/11/11 08:48:58 Running command npm install --global npm
> 25 | /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> 26 | /usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
> 27 | + npm@9.1.1
> 28 | added 88 packages from 28 contributors, removed 303 packages and updated 134 packages in 14.16s
> 29 |  
> 30 | [Container] 2022/11/11 08:49:29 Running command npm install -g aws-cdk@2.43.0
> 31 |  
> 32 | added 1 package in 918ms
> 33 |  
> 34 | [Container] 2022/11/11 08:49:30 Running command npm install
> **35 | npm ERR! Invalid comparator: latest**
> 36 |  
> 37 | npm ERR! A complete log of this run can be found in:
> 38 | npm ERR!     /root/.npm/_logs/2022-11-11T08_49_31_165Z-debug-0.log
> 39 |  
> 40 | [Container] 2022/11/11 08:49:34 Command did not exit successfully npm install exit status 1
> 41 | [Container] 2022/11/11 08:49:34 Phase complete: INSTALL State: FAILED
> **42 | [Container] 2022/11/11 08:49:34 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install. Reason: exit status 1**

_

### Reproduction Steps

deploy eks-blueprint-pipeline-stack after Nov 9th

### Possible Solution

update buildspec.yaml, pin down npm to version 8.19.3

_

> {
>   "version": "0.2",
>   "phases": {
>     "install": {
>       "commands": [
>         "**npm install --global npm@8.19.3"**,
>         "npm install -g aws-cdk@2.43.0",
>         "npm install"
>       ]
>     },
>     "build": {
>       "commands": [
>         "npm run build",
>         "npx cdk synth"
>       ]
>     }
>   },
>   "artifacts": {
>     "base-directory": "cdk.out",
>     "files": "**/*"
>   }
> }

_

### CDK CLI Version

2.43.1

### EKS Blueprints Version

blueprints-1.3.0

### Node.js Version

v18.9.1

### Environment details (OS name and version, etc.)

Amazon Linux 2(amazon/amzn2-ami-kernel-5.10-hvm-2.0.20220805.0-x86_64-gp2)

**Comment by shapirov103** [comment]
Will revert the npm/node version to stable as opposed to latest. Latest node version is called out as unsupported for CDK as a whole, so node 18.12.1 and npm 8.19.2  will be used.

**Comment by bigben80** [comment]
Thank you! I think it should fix the problem.

**Comment by shapirov103** [comment]
Fixed in 1.4.1
