### ISSUE TITLE
Allow passing in `NodeRole` when creating managed node groups

### ISSUE THREAD

**Issue by praveenperera** [aws-quickstart/cdk-eks-blueprints#540]
### Describe the feature

Allow passing in a NodeRole or policies for the NodeRole for managed groups.

### Use Case

I need to give the nodes some extra access, and to do that I need to add some permissions to the nodeRole. 

However, when I try to pass in a nodeRole with the managedNodeGroups:

```
    const nodeRole = new aws_iam.Role(this, "NodeRole", {
      assumedBy: new aws_iam.ServicePrincipal("ec2.amazonaws.com"),
     ....
    });

    const clusterProvider = new blueprints.GenericClusterProvider({
      clusterName: clusterName,
      version: KubernetesVersion.V1_23,
      managedNodeGroups: {... nodeRole: nodeRole}
    });
```

I get an error:

```
<PARENT_STACK>/NodeRole should be defined in the scope of the <BLUEPRINTS_CLUSTER_STACK> stack to prevent circular dependencies
```

### Proposed Solution

I think what needs to be done is add the ability to pass in permissions to the nodeRole, or give me access to the nodeRole afterwards so I can add permissions after its created.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.50.0 (build 4c11af6)

### EKS Blueprints Version

1.4.1

### Node.js Version

v16.17.1

### Environment details (OS name and version, etc.)

MacOS 12.6.1 (21G217)

**Comment by shapirov103** [comment]
Similar to #435, please comments there. The approach use can be similar to https://docs.aws.amazon.com/cdk/api/v1/docs/aws-s3-readme.html#sharing-buckets-between-stacks

**Comment by praveenperera** [comment]
Thanks, if we could make the blueprints a NestedStack instead of Stack would this problem be solved?

**Comment by shapirov103** [comment]
You don't have to make it a nested stack. Just create a separate stack where you either provision or look up the role you need. create a variable in the stack and then pass it over to the blueprints in Mng or generic cluster provider as `nodeRole: myOtherStack.nodeRole`. Similar to the example with S3 above.

**Comment by praveenperera** [comment]
@shapirov103 I believe that's what I did above. But I get the error:

`<PARENT_STACK>/NodeRole should be defined in the scope of the <BLUEPRINTS_CLUSTER_STACK> stack to prevent circular dependencies

But I think the solution in the issue you linked should work. I'm looking forward to the new config passing solution.

**Comment by shapirov103** [comment]
Yeah, please don't use the approach like:

```
class MyCdkBlueprint extends Stack {
    constructor(...) {
        const myRole = ...;
        blueprints.builder.build();
    }
}
```

The above will produce a redundant outer stack and another stack for blueprints.

Instead you can use:

```
const app = new cdk.App();

class MyRoleStack extends Stack {
    public nodeRole;
    constructor()
}

const roleStack = new MyRoleStack(app, ...);

const clusterProvider = blueprints.MngClusterProvider( { nodeRole: roleStack.nodeRole}); 
blueprints.EksBlueprint.builder().clusterProvider(clusterProvider)...build()...
```

**Comment by praveenperera** [comment]
Ah I think doing it that way caused me a lot of issues. I did it this way because I needed to control the VPC better (less AZs for some clusters). But I think I'll find a different way to do that, I guess by creating a separate stack for VPCs.

**Comment by namjug-kim** [comment]
@shapirov103 

> Instead you can use:
>
> ``` 
> const app = new cdk.App();
> 
> class MyRoleStack extends Stack {
>     public nodeRole;
>     constructor()
> }
> 
> const roleStack = new MyRoleStack(app, ...);
> 
> const clusterProvider = blueprints.MngClusterProvider( { nodeRole: roleStack.nodeRole}); 
> blueprints.EksBlueprint.builder().clusterProvider(clusterProvider)...build()...
> ```

Thanks for your comment. 
I tried it with the sample code below.

```

class NodeGroupRoleStack extends cdk.Stack {
    public readonly nodeRole: iam.IRole

    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        this.nodeRole = iam.Role.fromRoleName(this, "123", "123")
    }
}
const roleStack = new NodeGroupRoleStack(app, ...);
const clusterProvider = blueprints.MngClusterProvider( { nodeRole: roleStack.nodeRole}); 
blueprints.EksBlueprint.builder().clusterProvider(clusterProvider)...build()...
```

`[NodeGroupRoleStackId] should be defined in the scope of the [EksBluprintStackId] stack to prevent circular dependencies`
An error occurred as a result of execution. Is there something wrong?

**Comment by shapirov103** [comment]
@namjug-kim I will need to run the example to tell for sure, however, based on what I observed, CDK is very sensitive to the envs being identical between the stacks. You can see more details [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resource_stack).
Have you tried setting account/region on both?

`builder.account("").region("")` and env for the NodeGroupRoleStack.

**Comment by namjug-kim** [comment]
Im not sure this is right purpose. but under code works for me :)

``` typescript
const stack = blueprints.EksBlueprint.builder() ...
    .build(app, id)

stack.getClusterInfo().nodeGroups?.at(0)?.role?.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName("AmazonSQSFullAccess"));
```

**Comment by praveenperera** [comment]
> Im not sure this is right purpose. but under code works for me :)
> 
> ```ts
> const stack = blueprints.EksBlueprint.builder() ...
>     .build(app, id)
> 
> stack.getClusterInfo().nodeGroups?.at(0)?.role?.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName("AmazonSQSFullAccess"));
> ```

Oh that’s very helpful and very easy. I’m going to do that.
