### ISSUE TITLE
[Karpenter Addon] Not able to upgrade karpenter to latest version

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#544]
### Describe the feature

Karpenter use new repo oci://public.ecr.aws/karpenter/karpenter since v0.17.0 so please help to support this repo
The current one is [repository: 'https://charts.karpenter.sh',](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/18f9f166461f63e0eb743f8dd4507f67bc2314a5/lib/addons/karpenter/index.ts#L94) still keep the old version v0.16.0 but latest version now is v0.19.2

### Use Case

Not able to upgrade karpenter to latest version

### Proposed Solution

Update karpenter helm chart repository

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.50.0

### EKS Blueprints Version

1.4.1

### Node.js Version

v18.9.1

### Environment details (OS name and version, etc.)

macOS Ventura 13.0.1

**Comment by youngjeong46** [comment]
@vumdao I'm currently working on an upgraded support to 0.19 (OCI helm charts). Will keep you updated on this.

**Comment by vumdao** [comment]
Hi @youngjeong46 , hope you're doing well, how is this issue so far?
