### ISSUE TITLE
ExternalDnsAddOn: Unable to start on ARM architecture

### ISSUE THREAD

**Issue by sylwit** [aws-quickstart/cdk-eks-blueprints#557]
### Describe the bug

ExternalDNSAddOn starts the bitnami docker image https://hub.docker.com/r/bitnami/external-dns/tags.

This image only exists for AMD architecture, hence the addon is deployed but the pod is unable to start on ARM based nodes

### Expected Behavior

ExternalDNSAddon should be compatible with both K8S architecture

### Current Behavior

The pod enters in a CrashLoopBackOff state

### Reproduction Steps

Create a managed node group with ARM_64 arch

```
    const clusterProvider = new blueprints.GenericClusterProvider({
        version: KubernetesVersion.V1_23,
        kubectlLayer: new KubectlV23Layer(kubectlLayerStack, "KubectlLayer"),
        managedNodeGroups: [
            {
                minSize: 1,
                maxSize: 3,
                id: "mng-main-group-1",
                amiType: NodegroupAmiType.AL2_ARM_64,
                instanceTypes: [new InstanceType("c7g.large")],
                diskSize: 50,
            },
        ],
    });
```

Simply use the ExternalDnsAddOn

```
    new blueprints.addons.ExternalDnsAddOn({
        hostedZoneResources: [GlobalResources.HostedZone]
    }),
```

### Possible Solution

- Use another docker image supporting multi arch not provided by bitnami. Kubernetes SIGs may be a good alternative ?
https://github.com/kubernetes-sigs/external-dns/
`docker pull --platform linux/arm64 us.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.13.1`

- Update the documentation to warn that this addon isn't compatible with ARM without overriding the default image.

### CDK CLI Version

2.56.0 (build 1485f48)

### EKS Blueprints Version

1.5.2

### Node.js Version

18.12.1

### Environment details (OS name and version, etc.)

alpine

**Comment by youngjeong46** [comment]
@sylwit Thank you for submitting the issue. As shown [here](https://github.com/bitnami/charts/issues/7305), lack of ARM support on helm charts appears to be a Bitnami-wide issue. 

Short term solution might be to document the lack of ARM support. As for the SIGs helm chart, we will investigate and take a look.

**Comment by sylwit** [comment]
Just posting my workaround in case it could help. Simply override the helm chart

```    
new blueprints.addons.ExternalDnsAddOn({
        hostedZoneResources: [GlobalResources.HostedZone],

        repository: 'https://kubernetes-sigs.github.io/external-dns/',
        version: '1.12.0',
}),
```

**Comment by shapirov103** [comment]
@elamaran11 is it is the case? Can we close it if later version of external DNS work with arm?

**Comment by elamaran11** [comment]
@shapirov103 This looks like repo change and version change. we are at 6.x with bitnami repo. I will work on testing it and update doc as well.

**Comment by elamaran11** [comment]
@sylwit Please track with #739 PR
