### ISSUE TITLE
EKS v1.23+ : PVC is in a pending state for more than 5 minutes and errors out

### ISSUE THREAD

**Issue by rameshv29** [aws-quickstart/cdk-eks-blueprints#561]
### Describe the bug

While deploying Kubecost addon and testing the blueprints, I can see the PVC's were in pending state. The cluster is Amazon EKS 1.23+ the error message appears as below:

```
kubectl get pvc -n kubecost                                          
NAME                                       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubecost-cost-analyzer                     Pending                                      gp2            9h
kubecost-cost-analyzer-prometheus-server   Pending                                      gp2            9h
```

```
kubectl describe pvc kubecost-cost-analyzer -n kubecost | grep "ebs.csi.aws.com"
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  Normal  ExternalProvisioning  2m7s (x2222 over 9h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

Due to which the pods were in pending state as well.

```
kubectl get pods -n kubecost
NAME                                                         READY   STATUS    RESTARTS   AGE
kubecost-cost-analyzer-5ddcf68947-dz7ql                      0/2     Pending   0          3h37m
kubecost-cost-analyzer-grafana-7b8785cc64-bjhf4              2/2     Running   0          9h
kubecost-cost-analyzer-kube-state-metrics-5647655787-5j6jt   1/1     Running   0          9h
kubecost-cost-analyzer-prometheus-node-exporter-7x9kg        1/1     Running   0          9h
kubecost-cost-analyzer-prometheus-server-5b6749d9d9-kxwf8    0/2     Pending   0          3h44m
```

### Expected Behavior

PVC's should be created and pods should be in running state.

### Current Behavior

```
kubectl describe pvc kubecost-cost-analyzer -n kubecost | grep "ebs.csi.aws.com"
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  Normal  ExternalProvisioning  2m7s (x2222 over 9h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

### Reproduction Steps

Deploy a cluster v1.23 or higher along with Kubecost using blueprints and you can see the pods are in pending state due to the PVC's (pending state).

### Possible Solution

You need to install the [AWS EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) because the Amazon EKS cluster version 1.23+ uses "ebs.csi.aws.com" provisioner and the AWS EBS CSI driver has not been installed.

### CDK CLI Version

2.59.0 (build b24095d)

### EKS Blueprints Version

1.5.2

### Node.js Version

v18.12.1

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by shapirov103** [comment]
@rameshv29 is it related to a particular pattern or do you think there is something missing in the EKS cluster provisioning with respect to the EBS storage? We do have ebs-csi driver add-on which can be just added to the blueprint to make the above scenario work.

**Comment by elamaran11** [comment]
@rameshv29 Please close this issue, if you still dont see this.
