### ISSUE TITLE
MngClusterProvider does not update launch template after upgrading to EKS v1.24

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#570]
### Describe the bug

The managed node group need manual update to apply latest AMI of the new EKS version

![image](https://user-images.githubusercontent.com/37215642/212468904-491f118c-18d8-425f-8108-99878f8918ee.png)

```
export function EksComponents(env: EnvironmentConfig) {
  const MngProvider = new MngClusterProvider({
    version: KubernetesVersion.V1_24,
    id: `${env.pattern}-vc-${env.stage}-Mng`,
    minSize: 2,
    maxSize: 2,
    instanceTypes: [
      InstanceType.of(InstanceClass.T3A, InstanceSize.MEDIUM),
      InstanceType.of(InstanceClass.T3, InstanceSize.MEDIUM),
    ],
    amiType: NodegroupAmiType.BOTTLEROCKET_X86_64,
    nodeGroupCapacityType: CapacityType.SPOT,
  });
  return MngProvider;
}
```

### Expected Behavior

Launch template of managed node group is updated automatically

### Current Behavior

Manual update

### Reproduction Steps

Upgrade EKS v1.23 to v1.24

### CDK CLI Version

2.60.0

### EKS Blueprints Version

1.5.4

### Node.js Version

v18.9.1

### Environment details (OS name and version, etc.)

MacOS 13.1

**Comment by shapirov103** [comment]
@vumdao is it still relevant? It was a miss to not respond sooner, please ping me directly if you see no progress on your issues. Please see [this](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/generic-cluster-provider/#upgrading-control-plane) doc page on data plane upgrade that should be coupled with the control plane upgrade. Look up of AMI will be required but there is no need to update individual node groups manually.
