### ISSUE TITLE
Getting Started Docs: Examples failing to deploy

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#574]
### Describe the bug

The getting started guide contains examples that use deprecated and unsupported add-ons which fail to deploy. 

CalicoAddOn fails with an error. 

XRayAddOn fails with an error. 

### Expected Behavior

Examples are expected to work ootb. 

### Current Behavior

Calico: Error: b'Release "blueprints-addon-calico" does not exist. Installing it now.\nError: failed to install CRD crds/crds.yaml: [resource mapping not found for name: "felixconfigurations.crd.projectcalico.org" namespace: "" from ""
 
XRay appears to need some yaml updating  Error: b'daemonset.apps/xray-daemon created\nconfigmap/xray-config created\nservice/xray-service created\nerror: unable to recognize "/tmp/manifest.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"\n'

### Reproduction Steps

Use getting started guide

### CDK CLI Version

2.60.0

### EKS Blueprints Version

1.5.4

### Node.js Version

18.12

### Environment details (OS name and version, etc.)

MacOS

**Comment by k-dahl** [comment]
Just a heads up that while XRay was removed from the getting started doc, it's still in the README.md example at the base of this repo (which is what most people, like myself, are going to try first).

The getting started doc also later refers to an XRay service being deployed, despite the removal from the example.
