### ISSUE TITLE
cdk-eks-blueprints: fails on Custom::AWSCDK-EKS-HelmChart

### ISSUE THREAD

**Issue by beamsies** [aws-quickstart/cdk-eks-blueprints#583]
### Describe the bug

Not sure yet if this is a bug on the cdk-eks-blueprints repo, but just following the [quickstart here](https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#project-setup), I get an error and can't get it to work. 

I'm not sure what the error means either. 

Everything works up until I try ```cdk deploy``` then it errors out and shows this error message in the console:
![image](https://user-images.githubusercontent.com/6827052/214729077-9fab8085-187c-4a9e-b5d2-c86c1c677e6d.png)

It appears to error out on the ```Custom::AWSCDK-EKS-HelmChart``` stage.

### Expected Behavior

I would expect the deploy to succeed when following the quickstart guide.

### Current Behavior

The ```cdk deploy``` command fails when following the quickstart guide here: 
https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#project-setup

### Reproduction Steps

I followed the steps in the quickstart guide found here:
https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#project-setup

### Possible Solution

I am not sure at this time, I need to figure out how to debug this scenario which I am working on now.

### CDK CLI Version

2.61.1 (build d319d9c)

### EKS Blueprints Version

1.5.4

### Node.js Version

v16.17.0

### Environment details (OS name and version, etc.)

WSL2 Ubuntu V2

**Comment by beamsies** [comment]
Note: I noticed I was supposed to be using aws-cdk@2.60.0 per the quickstart guide docs and I made sure I had that version and tried again and it still failed with the same error documented in the description.

**Comment by beamsies** [comment]
Closing as I opened an issue on aws-cdk repo.

**Comment by shapirov103** [comment]
@beamsies can you add reference to the CDK issue here in case someone runs into the same issue? We can also upvote your issue.
