### ISSUE TITLE
[Karpenter] Deploy fail when more than 2 eks

### ISSUE THREAD

**Issue by namjug-kim** [aws-quickstart/cdk-eks-blueprints#587]
### Describe the bug

If deploy more than 2 eks cluster with carpenter addon, an **"Export with name KarpenterInstanceProfileName is already exported by stack {cdk-eks-blueprints-id}"** error occurs.

### Expected Behavior

Deployment Successful

### Current Behavior

cloudformation stop with error **"Export with name KarpenterInstanceProfileName is already exported by stack {cdk-eks-blueprints-id}"**

### Reproduction Steps

```
const clusterA = blueprints.EksBlueprint.builder()
    .addOns(new blueprints.addons.KarpenterAddOn())
    .build(app, `cluster-a`);

const clusterB = blueprints.EksBlueprint.builder()
    .addOns(new blueprints.addons.KarpenterAddOn())
    .build(app, `cluster-b`);
```

deploy multiple cluster with karpenterAddOn

### CDK CLI Version

2.61.1 (build d319d9c)

### EKS Blueprints Version

1.5.4

### Node.js Version

v19.4.0

### Environment details (OS name and version, etc.)

mac m1

**Comment by youngjeong46** [comment]
@namjug-kim Thank you for submitting the issue yesterday. I have an open PR to address the issue at hand.

**Comment by youngjeong46** [comment]
@namjug-kim The latest npm release (1.6.0) should have this incorporated. Please test and re-open the issue if you still see it linger. Closing it for now.
