### ISSUE TITLE
CDK EKS Blueprints doc page for Graviton Support

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#591]
### Describe the feature

CDK EKS Blueprints doc page for Graviton Support

### Use Case

CDK EKS Blueprints doc page for Graviton Support

### Proposed Solution

CDK EKS Blueprints doc page for Graviton Support

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.61.1

### EKS Blueprints Version

1.5.4

### Node.js Version

v19.4.0

### Environment details (OS name and version, etc.)

Mac M1

**Comment by ratnopamc** [comment]
@elamaran11, please check https://github.com/aws-quickstart/cdk-eks-blueprints/pull/707 for this.
Thanks.

**Comment by elamaran11** [comment]
This is completed with #729
