### ISSUE TITLE
Use Generics to return EksBlueprint in class BlueprintBuilder to enable creation of custom EksBlueprints

### ISSUE THREAD

**Issue by jbhalla-godaddy** [aws-quickstart/cdk-eks-blueprints#599]
### Describe the feature

Currently, there is no direct way to create a custom cdk stack using class `EksBlueprint`, as it currently returns an object of class `EksBlueprint` (which is a `cdk.stack`) via class BlueprintBuilder using static method `builder()` in class `EksBlueprint`. 

As the build method in class `BlueprintBuilder` returns `EksBlueprint` - this tightly coupled type makes it hard for us to create custom `cdk.stack` wrapped with our internal governance logic.

In other words, we are looking to create our own company-specific blueprint (like class `GDEKSBlueprint`) that implements our internal interface to create a `cdk.stack`. This can be achieved easily if we return a generic class T instead of `EksBlueprint` (see the proposed solution below).

This will help everyone to directly create our own native `EksBlueprint` to return their native Stack (instead of AWS `EksBlueprint`) with additional native logic, practically extending the EKS Blueprint Library for wider adoption.

This will also help everyone to create custom EKS Blueprint stacks with custom logic without ignoring type checks (shown using `@ts-ignore`), which makes it easier to generate the code for other languages like Python and Java that have strong type checks.

### Use Case

If the code is changed to return generic class T instead of `EksBlueprint` then it opens up the ability to extend any custom `cdk.stack`. 

### Proposed Solution

We are looking to create our own company-specific blueprint (like class `GDEKSBlueprint`) that implements our internal interface to create a `cdk.stack`. 

**So to achieve that we are seeking to get the EKSBlueprints library updated with the following changes:**

1. Return generic class T instead of `EksBlueprint` for the following methods in class `BlueprintBuilder`:     

- `build(scope: Construct, id: string, stackProps?: cdk.StackProps): EksBlueprint;`
- `buildAsync(scope: Construct, id: string, stackProps?: cdk.StackProps): Promise<EksBlueprint>; `

2. Return generic class T instead of `BlueprintBuilder` for static method `builder()` in class `EksBlueprint`.
3. Return generic class T instead of `Promise<EksBlueprint>` for method `waitForAsyncTasks()` in class `EksBlueprint`.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.62.0

### EKS Blueprints Version

1.5.4

### Node.js Version

16.13.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by jbhalla-godaddy** [comment]
@shapirov103 As discussed in our meeting last week, we tried creating our own class `GDEksBlueprint` using the following code block which can be fixed if class `EksBlueprint` and class `BlueprintBuilder` use generics. Let me know if you need anything else. 

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/117107523/217358201-bd71fe61-ee07-49c7-acf5-d4cfe67bb771.png">

**Comment by jbhalla-godaddy** [comment]
CC'ing @rameshv29 @dsilbergleithcu-godaddy on this one

**Comment by shapirov103** [comment]
@jbhalla-godaddy I added changes [here](https://github.com/aws-quickstart/cdk-eks-blueprints/commit/b5721cf8e9ba7171e9d93f5ed73985a1a4e5102e), but I have not yet added a test case with your example to confirm that all of the paths will work with no warnings. Once you are ready, please let me know here, I will test and merge.

**Comment by jbhalla-godaddy** [comment]
@shapirov103 Yeah the changes look good. Let me know once you add our example as a test case, and then merge this. Looks great, thanks for adding these Mikhail!
