### ISSUE TITLE
refactor cluster control plane logging implementation

### ISSUE THREAD

**Issue by starchx** [aws-quickstart/cdk-eks-blueprints#603]
### Describe the feature

Currently the control plane logging is implemented using Custom Resource.

The CDK has provided support for [enabling the logging](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#clusterlogging).

### Use Case

Using the native method provided by CDK is better than CFN custom resource.

Besides that, I have seen issues with cluster creation when logging is enabled along with Fargate profiles creation:

`Received response status [FAILED] from custom resource. Message returned: Cannot LoggingUpdate because cluster xxx-nonprod currently has Fargate profile fargate-profile in status CREATING (RequestId: 4e0fbd5a-228a-48fa-834b-33a8eee6e478)`

I am not certain using CDK native way for logging will resolve the error above, but if it does, it will be cherry on top.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.6.0

### Node.js Version

v18.13.0

### Environment details (OS name and version, etc.)

NA

**Comment by Feder1co5oave** [comment]
The creation and management (including logging) of EKS cluster via custom resource was already and still is done by CDK internally.
The `ClusterResource` creates a custom resource `Custom::AWSCDK-EKS-Cluster` internally:

https://github.com/aws/aws-cdk/blob/f3fd18389fcb69d5a6fb6d2964afa21e1c7d01e3/packages/%40aws-cdk/aws-eks/lib/cluster-resource.ts#L71-L91

I think the issue with the fargate profile and logging update should be filed to the CDK repo.
The fargate profile is implemented as yet another custom resource, handled by the cluster-resource-handler.
Maybe a dependency between the fargate profile c.r. and the cluster c.r. can solve this?
