### ISSUE TITLE
Support for 1.24

### ISSUE THREAD

**Issue by k-dahl** [aws-quickstart/cdk-eks-blueprints#607]
### Describe the feature

Sorry for the format - the README suggests to post questions in issues, but the issues require a template to be used. If there's a more suitable place for discussion on these topics, please direct me to it - thanks!

Three questions:

Is support for EKS 1.24 coming to blueprints? 1.23 is EoL in 7 months time, and CDK will soon be supporting 1.25. There's already a very short time-span of support for EKS/k8s in general, and having blueprints support so far behind is making me wary of basing anything on it.

How about an example of how to set up VPC peering on the resulting VPC?

What is the best practice for upgrading a blueprints cluster from one k8s version to the next?

### Use Case

...

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.60

### EKS Blueprints Version

1.5.4

### Node.js Version

v16.17.0

### Environment details (OS name and version, etc.)

Darwin Kernel Version 22.2.0

**Comment by shapirov103** [comment]
@k-dahl it is the right place for such discussions.

Support for 1.24 is already available in the 1.5.4 now, with [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/cluster-providers/generic-cluster-provider.ts#L272) change. You should be able to create a cluster passing your version to the builder:

```typescript
import { KubernetesVersion } from 'aws-cdk-lib/aws-eks';
...
   blueprints.EksBlueprint.builder()
            .version(KubernetesVersion.V1_24)
            .addOns(...)
```
We will add support for 1.25 with the upcoming 1.6 release. In general, if a version of the target EKS version is not yet in the CDK, you can still pass it as `KubernetesVersion.of("1.25")` for example, and use the kubectl layer for the previous version which should be compatible for most cases. 

Cluster upgrades (in-place) simply requires passing the new version to the control plane. This won't handle the kubelet upgrade though, which will require passing correct `amiReleaseVersion` to the node group as desribed [here](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/generic-cluster-provider/#upgrading-control-plane).

VPC peering setup may be a good pattern. Potentially, you can achieve it by registering a custom VPC [resource provider](https://aws-quickstart.github.io/cdk-eks-blueprints/resource-providers/) that handles peering set up for the new VPC. This, however, would be a good pattern for us to add to the [patterns](https://github.com/aws-samples/cdk-eks-blueprints-patterns) repo. I can keep this issue to track it.

**Comment by k-dahl** [comment]
Thanks for the insights @shapirov103. Unfortunately I have not been able to get 1.25 working.

If I use `KubernetesVersion.of("1.25")` I receive this warning:

```
[Warning at /custom-eks-cluster/eks-blueprint/eks-blueprint] You created a cluster with Kubernetes Version 1.25 without specifying the kubectlLayer property. This may cause failures as the kubectl version provided with aws-cdk-lib is 1.20, which is only guaranteed to be compatible with Kubernetes versions 1.19-1.21. Please provide a kubectlLayer from @aws-cdk/lambda-layer-kubectl-v25.
```

If I try and use a generic provider and specify the 1.24 KubeCtlLayer I get this:

```
ERROR [main   printFatalErrorUponExit] Error: KubectlV24Layer at 'custom-eks-cluster/kubectllayer-v24' should be created in the scope of a Stack, but no Stack found
```

I can't find any example online of Generic Cluster Provider being used with KubectlV24Layer so I am not sure if this is just something I have configured incorrectly or a bug.

**Comment by shapirov103** [comment]
@k-dahl thank you for looking into this.
There was a fix to supply the 1.24 layer for any version above 1.24 [here](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/cluster-providers/generic-cluster-provider.ts#L282) which must have failed. This will be addressed and included in the next maintenance release.

**Comment by shapirov103** [comment]
@k-dahl please try with version 1.6.0 of Blueprints. I ran the tests for 1.25 and the only issue I discovered was kube-proxy addon was incompatible and required version upgrade to v1.24.10-eksbuild.2. You can specify the add-on version when you create them. 
The rest of the upgrades are here: https://github.com/aws-quickstart/cdk-eks-blueprints/pull/623

However, the cluster deployed fine with no code changes (only config for a couple of addons).

**Comment by shapirov103** [comment]
1.24, 1.25, 1.26 are all supported, however testing was performed on 1.24 and 1.25
