### ISSUE TITLE
Why is the VPC CNI a requirement for the Karpenter Addon?

### ISSUE THREAD

**Issue by danielloader** [aws-quickstart/cdk-eks-blueprints#625]
### Describe the documentation issue

I can't see why this is a requirement, and isn't when deploying via eksctl or terraform. 

Can anyone explain why it's a requirement?

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/

**Comment by youngjeong46** [comment]
@danielloader This change was pushed to release 1.6.1. Please verify that it is no longer required.
