### ISSUE TITLE
Karpenter: instance node role output always changes

### ISSUE THREAD

**Issue by Feder1co5oave** [aws-quickstart/cdk-eks-blueprints#630]
### Describe the bug

Every time I change anything in my CDK project, the outputs (Node Role name and Instance Profile name) of Karpenter addon change name, because of the change introduced in #595.

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/263da03a88724e55269084c4a2c90ce2c9f635be/lib/addons/karpenter/index.ts#L400-L413

The clusterHash is computed on the clusterName, which is a token that gets resolved only later. So, for example `${Token[TOKEN.907]}` gets hashed instead, and the token placeholders change often non-deterministically.

May I suggest using `Names.uniqueId(cluster)` for all outputs instead?
This returns a unique name from the cluster's node path, such as `eksblueprint85A195CC`.

### Expected Behavior

Output names should be more stable.

### Current Behavior

Deploy a blueprint with Karpenter addon, then change anything in the stack and run `cdk diff`.
It always returns
```json
[~] Output Karpenter Instance Node Role KarpenterInstanceNodeRole: {
  "Description":"Karpenter add-on Node Role name",
  "Value":{"Ref":"ekskarpenternoderole8897C336"},
  "Export":{"Name":"KarpenterNodeRoleName0aa68ce495587319d019d932d9f0f6ec"}
} to {
  "Description":"Karpenter add-on Node Role name",
  "Value":{"Ref":"ekskarpenternoderole8897C336"},
  "Export":{"Name":"KarpenterNodeRoleName0c2627510746e95b144ce7be3b090ff1"}
}
```

### Reproduction Steps

-

### CDK CLI Version

2.66.1

### Node.js Version

v16.19.1

### Environment details (OS name and version, etc.)

-

**Comment by youngjeong46** [comment]
@Feder1co5oave Thanks for submitting the issue. I'll test the `uniqueId` and implement it in the latest PR.

**Comment by rverma-nsl** [comment]
Yes, this is a big issue, in fact because of this the snapshot tests will not work

**Comment by youngjeong46** [comment]
@Feder1co5oave We pushed the PR into 1.6.1 release. Can you test and verify?

**Comment by Feder1co5oave** [comment]
@youngjeong46 I believe I've already tested this a couple of days ago when I upgraded to 1.6.1. Unfortunately because of #644 I decided to rollback until a fix is released so I can't double-check this right now.
Nonetheless, I trust that the fix works as intended, so we can close this.

**Comment by youngjeong46** [comment]
Closing as issue is addressed.
