### ISSUE TITLE
EKS: tags are not propagated to the cluster

### ISSUE THREAD

**Issue by Feder1co5oave** [aws-quickstart/cdk-eks-blueprints#631]
### Describe the bug

CDK EKS offers the possibility to add tags to the EKS cluster on cluster creation (modification is not yet supported: https://github.com/aws/aws-cdk/issues/19388)
via the `tags` property in the props passed to the `eks.Cluster(scope: Construct, id: string, props: ClusterProps)` constructor.

In the bluprint, the cluster is created in
`GenericClusterProvider.internalCreateCluster()` or
`FargateClusterProvider.internalCreateCluster()`,
which get passed either a 
`GenericClusterProviderProps extends eks.ClusterOptions` or a
`FargateClusterProviderProps extends eks.CommonClusterOptions` props. Neither of those has the `tags` property.

### Expected Behavior

There should be a way to tag the EKS cluster

### Current Behavior

Cluster gets created without any tags.
Even specifying `Tags.of(stack).add('tagKey', 'tagValue')` has no effect, because these tags do not make it into the cluster custom resource `Config`.

### Reproduction Steps

You cannot specify tags for a Blueprint EKS cluster

### Possible Solution

Would it be feasible to add a `tags?: { [key: string]: string }` property to `GenericClusterProviderProps` and 
`FargateClusterProviderProps` ?

### CDK CLI Version

2.66.1

### EKS Blueprints Version

1.6.0

### Node.js Version

v16.19.1

**Comment by Zetten** [comment]
I note it's not yet been triaged, but (entirely selfishly!) I'd suggest fairly high priority. Support for common tags through the stack would be vital for some common business use cases, e.g. for compliance with project/owner/cost allocation tagging requirements.

If I were to deploy an EKS cluster using this I'd have our cloud billing team complaining _very_ quickly that I haven't tagged resources appropriately :smile:

**Comment by elamaran11** [comment]
@Zetten @Feder1co5oave This issue is fixed now. Please check from your end using latest release and let us know if you have any questions. Please close the PR if all is well.
