### ISSUE TITLE
Can you run this cluster with a single NAT gateway for development clusters?

### ISSUE THREAD

**Issue by danielloader** [aws-quickstart/cdk-eks-blueprints#632]
### Describe the documentation issue

The documentation has no information on running a cluster in a single NAT gateway mode for cross AZ access, is this possible?

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/

**Comment by shapirov103** [comment]
@danielloader we included this in the docs. Please see "Example implementations" [here](https://aws-quickstart.github.io/cdk-eks-blueprints/resource-providers/#contracts). 

I am closing it now, please reopen in case of any issues.
