### ISSUE TITLE
pipelines: Ability to add synth stage

### ISSUE THREAD

**Issue by jagadeeshmaneri** [aws-quickstart/cdk-eks-blueprints#633]
### Describe the bug

Currently, we take the approach of writing cdk code alongside the application code. 

```
repository
  -- .github
  -- app
  -- cdk
  -- docs
  -- package.json
  -- package-lock.json
  -- .gitignore
  -- README.md
  -- tsconfig.json

```

The cdk code is organized to be a subfolder of the GitHub repository root folder, and all the `/bin`, `/lib`, `cdk.json`, etc., are actually not inside the root folder of the repo. With the `synth` step defined with an assumption of `cdk.json` to be the repository's root folder in EKS Blueprints, the `build` stage in the pipeline fails with issues like below 

- `build` script not defined in `package.json`
- `--app` is required either in command-line, in cdk.json or in `~/.cdk.json`  

### Expected Behavior

It will be a good option to let developers define the `synth` step behavior, so we write the commands that are required for the pipeline to execute (along with `npx cdk synth`) before getting into `Assets` or other stages.

### Current Behavior

With default `installCommands` and `commands` already defined by the CodePipleine's `build` method, multiple issues (mentioned above) are encountered.

### Reproduction Steps

Create a pipeline with CDK code that is part of the subfolder inside the repository's root folder.

### Possible Solution

Update the `build` method to return the `cdkpipelines.CodePipeline` with developer-defined `PipelineProps` for the `synth` stage.

### CDK CLI Version

2.64.0

### EKS Blueprints Version

1.5.4

### Node.js Version

16.16.0

### Environment details (OS name and version, etc.)

MacOS, 13

**Comment by elamaran11** [comment]
This is addressed, closing the issue.
