### ISSUE TITLE
Generic Cluster Provider to enable IMDSv2 by default

### ISSUE THREAD

**Issue by orps** [aws-quickstart/cdk-eks-blueprints#643]
### Describe the feature

IMDSv2 enforcement is a security best practice. All AWS provided open-source projects should be secure by default and implement best practices. This project does not provide options to enable the setting of the `requireImdsv2` property for the Generic Cluster Provider's `launchTemplate`.

### Use Case

I want to provision and manage secure EKS clusters, and without the option to configure my instances to use IMDSv2 I am open to the vulnerabilities detailed in https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/ 

### Proposed Solution

The Generic Cluster Provider's `launchTemplate` could include an `requireImdsv2` option, which if not specified, will default to `true`.

Potential updates include:

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/cluster-providers/types.ts

```typescript
/**
 * Configuration options for the custom AMI.
 */
export interface LaunchTemplateProps {
    /**
     * The custom AMI for the node group.
     */
    machineImage?: ec2.IMachineImage;

    /**
     * The userData for worker node when using custom AMI. Only applicable when customAmi is used.
     */
    userData?: ec2.UserData;

    /**
     * Custom Tags for launch template which will propogate to worker nodes.
     */
    customTags?: {
        [key: string]: string;
    };
   
    /**
     * Whether IMDSv2 should be required on worker nodes.
     * @default true
     */
    requireImdsv2?: boolean;
}
```

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/da641bd9b930dde52d49bd9f9e688bdd0fd4ee9b/lib/cluster-providers/generic-cluster-provider.ts

```typescript
const requireImdsv2 = nodeGroup.launchTemplate?.requireImdsv2 ?? true;
const lt = new ec2.LaunchTemplate(cluster, `${nodeGroup.id}-lt`, {
                machineImage: nodeGroup.launchTemplate?.machineImage,
                userData: nodeGroup.launchTemplate?.userData,
                requireImdsv2: requireImdsv2
            });
```

### Other Information

This feature has been implemented in the [terraform-aws-eks-blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) (see https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/284) 

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.72.1

### EKS Blueprints Version

1.6.1

### Node.js Version

v18.15.0

### Environment details (OS name and version, etc.)

macOS 13.3

**Comment by Feder1co5oave** [comment]
Good thing to know that Karpenter already applies a safer default IMDS settings to the provisioned instances:
https://github.com/aws/karpenter/blob/v0.27.1/website/content/en/v0.27.0/concepts/node-templates.md#specmetadataoptions

**Comment by orps** [comment]
Thanks for the heads up on that. 

Just taking a look at the Karpenter best practices and it recommends that the Karpenter controller should run on Fargate or a node group: https://aws.github.io/aws-eks-best-practices/karpenter/#run-the-karpenter-controller-on-eks-fargate-or-on-a-worker-node-that-belongs-to-a-node-group.

This suggests, that even when utilising Karpenter, there would still be a need for this feature.

**Comment by Feder1co5oave** [comment]
AFAIK IMDS is not accessible from Fargate, so you can schedule Karpenter on EKS Fargate by adding a fargate profile like so:
```ts
getClusterInfo().cluster.addFargateProfile('karpenter-fargate-profile', {
  fargateProfileName: 'karpenter',
  selectors: [{ namespace: "karpenter" }]
})
```
(It becomes quite a bit more involved if you want to enable log forwarding from Fargate to Cloudwatch)
On a Karpenter deployment with 2 replicas, 250m cpu and 250Mi memory requests, this costs around $0.50 per day to run.

I believe your feature request is still valid of course, I'm just spreading the upsides of relying on Karpenter and forget about node groups altogether.

**Comment by robertcurcio** [comment]
What's querying the metadata? I'd prefer it to be disabled.
