### ISSUE TITLE
Generic Cluster Provider: Security group does not work, if it is defined in the separate Stack 

### ISSUE THREAD

**Issue by LogvinovIvanIDT** [aws-quickstart/cdk-eks-blueprints#648]
### Describe the bug

Hi Team
 
We are using 1.6.1cdk-eks-blueprint and 2.7.2 aws-cdk-lib. We implemented EKS cluster and security group for provider in different stacks.
![image](https://user-images.githubusercontent.com/45661415/231868929-dd09c350-d572-441a-ba99-68665b639afe.png)

**SG:**

```
export class SvpSecurityGroupStack extends cdk.Stack {
    public readonly securityGroupWeb: ec2.ISecurityGroup;

    constructor(scope: App, id: string, vpc: ec2.Vpc) {
        super(scope, id);

        const sgWeb = new ec2.SecurityGroup(this, 'service-sg-web', {
            vpc,
            securityGroupName: 'sg-web',
            description: 'Shared CDK-managed Security Group for HTTP(S) traffic'
        });

        // Allow HTTP(S) from PROD VPN and bastions ...
        sgWeb.connections.allowFrom(ec2.Peer.ipv4('169.132.88.0/22'), ec2.Port.tcp(443), 'Allow HTTPS connections from internal network');

        this.securityGroupWeb = sgWeb;
    }
}
``` 

```
Eks cluster Provider

       const clusterProvider = new GenericClusterProvider({
            clusterName: this.addPrefix('cluster-dev'),
            vpc: this.props.vpc,
            placeClusterHandlerInVpc: true,
            version: KubernetesVersion.V1_24,
            securityGroup: this.sg,
            endpointAccess: EndpointAccess.PRIVATE,
            albController: {
                version: AlbControllerVersion.V2_4_1
            },
           ...
        });
```

When we run` cdk synth`, we receive the following error.

C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:39
            if (stage_1.Stage.isStage(c) || !_scope) throw new Error(`${construct.constructor?.name ?? "Construct"} at '${constructs_1.Node.of(construct).path}' should be created in the scope of a Stack, but no Stack found`);
                                                           ^
Error: SecurityGroup at 'sg/service-sg-web' should be created in the scope of a Stack, but no Stack found
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:39:60)
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:40:20)
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:40:20)
    at Function.of (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:27:27)
    at differentStacks (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:2494)
    at SecurityGroup.determineRuleScope (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:2025)
    at SecurityGroup.addIngressRule (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:1130)
    at SecurityGroup.addIngressRule (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:6549)
    at C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\connections.js:1:2449
    at ReactiveList.forEachAndForever (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\connections.js:1:5789)

### Expected Behavior

The synth command should be executed

### Current Behavior

Error: SecurityGroup at 'sg/service-sg-web' should be created in the scope of a Stack, but no Stack found
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:39:60)
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:40:20)
    at _lookup (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:40:20)
    at Function.of (C:\Users\infrastructure\node_modules\aws-cdk-lib\core\lib\stack.js:27:27)
    at differentStacks (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:2494)
    at SecurityGroup.determineRuleScope (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:2025)
    at SecurityGroup.addIngressRule (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:1130)
    at SecurityGroup.addIngressRule (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\security-group.js:1:6549)
    at C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\connections.js:1:2449
    at ReactiveList.forEachAndForever (C:\Users\infrastructure\node_modules\aws-cdk-lib\aws-ec2\lib\connections.js:1:5789)

### Reproduction Steps

Provided in the description

### Possible Solution

Seems the following code in eks-blueprint-stack.ts replaces "@aws-cdk/core.Stack" field to "stack":
![image](https://user-images.githubusercontent.com/45661415/231871142-311c1090-993a-4d9a-9b6e-69b06ca7153b.png)

Therefore this check failed in the Stack;
```
static isStack(x) {
        return x !== null && typeof x == "object" && STACK_SYMBOL in x
    }
```

### CDK CLI Version

2.72.0

### EKS Blueprints Version

1.6,1

### Node.js Version

v16.16.0

### Environment details (OS name and version, etc.)

Windows

**Comment by shapirov103** [comment]
@LogvinovIvanIDT I will take a look at the resolveDynamicProxies you pointed out (thank you for that) - references that are not proxies are expected to be copied as is. 

However, you don't need an outer stack or separate stack to create resources like this SG. This maybe a good use case for resource providers, you can read more info [here](https://aws-quickstart.github.io/cdk-eks-blueprints/resource-providers/#using-resource-providers-with-cdk-constructs). 

Depending on whether the SG is reused or not you can either use named or anonymous resource provider, e.g. (pseudo code):

```typescript
const clusterProvider = new blueprints.GenericClusterProvider({
    version: KubernetesVersion.V1_24,
    securityGroup: blueprints.getResource(context => { 
        const sgWeb = new ec2.SecurityGroup(this, 'service-sg-web', {
            vpc,
            securityGroupName: 'sg-web',
            description: 'Shared CDK-managed Security Group for HTTP(S) traffic'
        });

        // Allow HTTP(S) from PROD VPN and bastions ...
        sgWeb.connections.allowFrom(ec2.Peer.ipv4('169.132.88.0/22'), ec2.Port.tcp(443), 'Allow HTTPS connections from internal network');
        return sg;
    }),
```
I can provide more info if needed, e.g. you can register your VPC through the resource provider and register

**Comment by LogvinovIvanIDT** [comment]
Thank you. I will check

**Comment by shapirov103** [comment]
Based on the guidelines for sharing resources across stacks outlined [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resource_stack:~:text=cluster%3A%20cluster%20%7D%29%3B-,Referencing%20resources%20in%20a%20different%20stack,-You%20can%20refer) (chrome reference, see section "Referencing resources in a different stack") I created the following example:

```typescript

class OtherStack extends Stack {

    public readonly vpc: Vpc;
    public readonly securityGroupWeb: ec2.ISecurityGroup;

    constructor() {
        super(app, "other-stack", {
            env: {
                account: process.env.CDK_DEFAULT_ACCOUNT,
                region: process.env.CDK_DEFAULT_REGION
            }
        });
        this.vpc = new Vpc(this, "central-vpc");
        this.securityGroupWeb = new ec2.SecurityGroup(this, 'service-sg-web', {
            vpc: this.vpc,
            securityGroupName: 'sg-web',
            description: 'Shared CDK-managed Security Group for HTTP(S) traffic'
        });
    }
}

const otherStack = new OtherStack();

builder()
    .clusterProvider(new bp.MngClusterProvider({
        ...publicCluster,
        securityGroup: otherStack.securityGroupWeb 
    }))
    .resourceProvider(bp.GlobalResources.Vpc, new DirectVpcProvider(otherStack.vpc))
    .account(process.env.CDK_DEFAULT_ACCOUNT)
    .region(process.env.CDK_DEFAULT_REGION)
    .build(app, "cross-stack-ref-blueprint");

```

`$ cdk synth cross-stack-ref-blueprint ` works fine with the above. 

Please note that nesting blueprint creation inside another stack is an anti-pattern.

**Comment by shapirov103** [comment]
Closing the issue, please reopen if you see any issues.
