### ISSUE TITLE
Support version checking for OCI charts and core addons

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#655]
### Describe the feature

At the moment helm version checking is not available for OCI charts and core add-ons. 
That creates a maintenance burden for oci: based add-on, in particular ACK, Grafana Operator, etc. 

This issue is to come up with an automated (or semi-automated) approach to discover newer chart versions for oci: charts and core add-ons. 

### Use Case

When running blueprints customers need to know whether there are newer versions of add-ons (helm addons) that can be upgraded. 

They also need to know if there are newer or better suited versions of core EKS addons. 

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.60

### EKS Blueprints Version

1.6.1

### Node.js Version

18.12

### Environment details (OS name and version, etc.)

MacOS

**Comment by elamaran11** [comment]
Thanks for creating this @shapirov103 . This is a must appreciate anyone can contribute to this.
