### ISSUE TITLE
Documentation on External DNS Add-on is not up to date

### ISSUE THREAD

**Issue by m0rt3z4gh** [aws-quickstart/cdk-eks-blueprints#686]
### Describe the documentation issue

The `hostedZoneProviders` In external-dns document does not exists anymore. Looks like it has changed to `hostedZoneResources`  in PR #206 

https://github.com/aws-quickstart/cdk-eks-blueprints/pull/206/commits/5a77afeb73e744a802627d0a92e632515cac9991

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/external-dns/

**Comment by shapirov103** [comment]
Addressed in #721
