### ISSUE TITLE
(ResourceProvider): No Documentations on some resource providers

### ISSUE THREAD

**Issue by youngjeong46** [aws-quickstart/cdk-eks-blueprints#688]
### Describe the documentation issue

It will be nice if we can have usage doc for some of the specific resource providers. For example, there is a `CreateEfsFileSystemProvider`, but not much explanation on what is needed to create the file system (i.e. one needs to carefully inspect the code to know that there needs to be a VPC context).

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/resource-providers/

**Comment by MarciaRieferJohnston** [comment]
It looks like this request has been fulfilled, so I'm closing this issue.
