### ISSUE TITLE
Upgrade Container Insights Addon 

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#692]
### Describe the feature

Either use https://github.com/aws-observability/aws-otel-helm-charts/tree/main/charts/adot-exporter-for-eks-on-ec2
or https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-EKS-otel.html to upgrade. 

The `CloudWatchMonitoringConstruct` in the patterns should also be changed to show an example that only is using CloudWatch. 

### Use Case

Customer is using CloudWatch exclusively for monitoring and needs to get all the metrics. 

### Proposed Solution

Start with the helm chart and then deviate if it has an issue.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.79

### Node.js Version

18

### Environment details (OS name and version, etc.)

Linux

**Comment by elamaran11** [comment]
This is blocked with an issue in ADOT-FOR-EC2 Helm chart. https://github.com/aws-observability/aws-otel-helm-charts/issues/99

**Comment by elamaran11** [comment]
#704 Implemented
