### ISSUE TITLE
Fluentbit Log forwarding to CloudWatch

### ISSUE THREAD

**Issue by shapirov103** [aws-quickstart/cdk-eks-blueprints#693]
### Describe the feature

Currently we have aws fluentbit addon. However, customers and convenient method to send logs to CloudWatch. 
The `CloudWatchMonitoringConstruct` pattern in the patterns repo also needs to be updated with fluentbit addon forwarding to cloudwatch. 

### Use Case

Customers that are all in on CloudWatch need a consistent solution to use CW for node, k8s and app metrics as well as logs. 
As a customer I want to have an addon that I can just add to the blueprints and with minor customization (e.g. just specifying the log group) it will forward all my logs from the cluster, including application logs, to CloudWatch. 

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.79

### Node.js Version

18

### Environment details (OS name and version, etc.)

Linux

**Comment by elamaran11** [comment]
pr #701
