### ISSUE TITLE
KarpenterAddOn: Add support for amiSelector in KarpenterAddOnProps 

### ISSUE THREAD

**Issue by AbhiKulkarniLatitude** [aws-quickstart/cdk-eks-blueprints#726]
### Describe the feature

Karpenter Support specify the ami to override the selection using "amiSelector" . https://karpenter.sh/preview/concepts/node-templates/#specamiselector
However KarpenterAddOnProps only supports amiFamily and not amiSelector 

### Use Case

Our organisation (most) have pre-baked Golden AMI to follow security guidelines. So we need a capability to override the selection of AMI

### Proposed Solution

Add support of amiSelector 
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/karpenter/index.ts#L153

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.0.0

### Node.js Version

18

### Environment details (OS name and version, etc.)

AmazonLinux

**Comment by javydekoning** [comment]
It's likely better to just load the manifests from yaml.  

The current `interface KarpenterAddOnProps` implementation is lacking functionality and will always lag behind new Karpenter features. Next to your example, the `requirements.op` only supports `In|NotIn` and is missing `Gt`,`Lt` etc and there is obviously many other options missing. 

Instead of trying to mimic Karpenters `awsnodetemplates` and `provisioners` schema in the Quickstart AddOn interface I think we should just make it easier to load those as yaml manifest.

Something like:

```ts
    new blueprints.addons.KarpenterAddOn({
      manifests: blueprints.utils.readYamlDocument('/karpenter.manifests.yaml')
    }),
```

You can already do it today like this, but it's a lot more difficult for users to implement:

```ts
class MyKarpenterManifestsAddOn implements blueprints.ClusterAddOn {
  @blueprints.utils.dependable(blueprints.addons.KarpenterAddOn.name)
  deploy(clusterInfo: blueprints.ClusterInfo): void | Promise<Construct> {
    const cluster = clusterInfo.cluster;
    const docArray = blueprints.utils.readYamlDocument(__dirname + '/karpenter.manifests.yaml')
    const manifest = docArray.split("---").map(e => blueprints.utils.loadYaml(e));
    const karpenterManifest = new eks.KubernetesManifest(cluster.stack, "karpenter-manifests", {
      cluster,
      manifest,
      overwrite: true,
    });
    return Promise.resolve(karpenterManifest);
  }
}

new blueprints.BlueprintBuilder()
  .addOns(
    new blueprints.addons.KarpenterAddOn(),
    new MyKarpenterManifestsAddOn()

...
```

**Comment by youngjeong46** [comment]
@AbhiKulkarniLatitude We will take a look to add the parameter. Going forward, we will look to take a different approach, similar to what @javydekoning have recommended.

**Comment by kulkarni-1983** [comment]
@youngjeong46 , Thanks for marking changes. I see lot of ticks for the PR. Can this be merged :)

**Comment by AbhiKulkarniLatitude** [comment]
@youngjeong46 , Thanks for marking changes. I see lot of ticks for the PR. Can this be merged :)

**Comment by youngjeong46** [comment]
@AbhiKulkarniLatitude This should have been included as part of the last release. Can you confirm? If so, we can then close the issue. If it persists, please let us know!
