### ISSUE TITLE
Override default EbsCsiDriverAddOnProps props values 

### ISSUE THREAD

**Issue by ILunie** [aws-quickstart/cdk-eks-blueprints#745]
### Describe the feature

Exposed EbsCsiDriverAddOnProps to override the default values

### Use Case

Created a custom construct based on a blueprint where all I need is to pass the values from the stack. 

### Proposed Solution

From: 
```typescript
interface EbsCsiDriverAddOnProps {
    /**
     * Version of the driver to deploy
     */
    version?: string;
    /**
     * List of KMS keys to be used for encryption
     */
    kmsKeys?: kms.Key[];
}
```

To:
```typescript
export interface EbsCsiDriverAddOnProps {
    /**
     * Version of the driver to deploy
     */
    version?: string;
    /**
     * List of KMS keys to be used for encryption
     */
    kmsKeys?: kms.Key[];
}
```

### Other Information

New version still don't exposed the props values
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/78790752cd5361ee1271374852d38a25308e6521/lib/addons/ebs-csi-driver/index.ts#L10 

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.84.0 (build f7c792f)

### EKS Blueprints Version

1.8.1

### Node.js Version

18.16.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by shapirov103** [comment]
@ILunie the from and to snippets that you attached appear to be identical. 

We are using the [core EKS add-on for the EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html). Are you referring to the configuration values support with the add-on? Can you point to the add-on version and available configuration values of this add-on on EKS?

**Comment by shapirov103** [comment]
Ahh - I see, it is a miss/bug. this will be in shortly.
