### ISSUE TITLE
ArgoCDAddon: Admin password name uses default profile only

### ISSUE THREAD

**Issue by wrexbe** [aws-quickstart/cdk-eks-blueprints#746]
### Describe the bug

I passed cdk deploy --profile someprofile, and everything worked, except ArgoCDAddon tried to use the default profile to get the secret manager key instead of profile.

### Expected Behavior

--profile something
gets the secret using the credentials from the profile account

### Current Behavior

used the credentials from the default account, instead of the one I specified, wasting a bunch of time trying to figure out if it was a permission, or format issue with the name.

### Reproduction Steps

const prodBootstrapArgo = new ArgoCDAddOn({
  adminPasswordSecretName: 'argocd-admin-eks-password',
  bootstrapRepo: {
      ...bootstrapRepo,
      path: 'envs/prod',
  }
});

Put the secret in a different profile then default, and run cdk deploy with the different profile

### CDK CLI Version

2.85.0 (build 4e0d726)

### EKS Blueprints Version

1.9.1

### Node.js Version

v18.16.1

### Environment details (OS name and version, etc.)

Mac M1 Max, Ventura 13.4 (22F66)

### Other information

I have multiple profiles

**Comment by elamaran11** [comment]
@wrexbe We fixed it. Please see if this works so we can close.
