### ISSUE TITLE
fluxcd: bootstrap Git repository manifest missing secrets

### ISSUE THREAD

**Issue by plumdog** [aws-quickstart/cdk-eks-blueprints#748]
### Describe the bug

Unable to pass all options to the git repository for FluxCD in https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/fluxcd/gitrepository.ts.

I'm considering this a bug, as currently not able to set `secretRef` so can't use this with a private bootstrap repository.

### Expected Behavior

To be able to configure the options for the custom resource. The full set of options are:
```
$ kubectl explain gitrepository.spec
KIND:     GitRepository
VERSION:  source.toolkit.fluxcd.io/v1

RESOURCE: spec <Object>

DESCRIPTION:
     GitRepositorySpec specifies the required configuration to produce an
     Artifact for a Git repository.

FIELDS:
   ignore	<string>
     Ignore overrides the set of excluded patterns in the .sourceignore format
     (which is the same as .gitignore). If not provided, a default will be used,
     consult the documentation for your version to find out what those are.

   include	<[]Object>
     Include specifies a list of GitRepository resources which Artifacts should
     be included in the Artifact produced for this GitRepository.

   interval	<string> -required-
     Interval at which to check the GitRepository for updates.

   recurseSubmodules	<boolean>
     RecurseSubmodules enables the initialization of all submodules within the
     GitRepository as cloned from the URL, using their default settings.

   ref	<Object>
     Reference specifies the Git reference to resolve and monitor for changes,
     defaults to the 'master' branch.

   secretRef	<Object>
     SecretRef specifies the Secret containing authentication credentials for
     the GitRepository. For HTTPS repositories the Secret must contain
     'username' and 'password' fields for basic auth or 'bearerToken' field for
     token auth. For SSH repositories the Secret must contain 'identity' and
     'known_hosts' fields.

   suspend	<boolean>
     Suspend tells the controller to suspend the reconciliation of this
     GitRepository.

   timeout	<string>
     Timeout for Git operations like cloning, defaults to 60s.

   url	<string> -required-
     URL specifies the Git repository URL, it can be an HTTP/S or SSH address.

   verify	<Object>
     Verification specifies the configuration to verify the Git commit
     signature(s).
```

### Current Behavior

Can only set `interval`, `url` and `ref.branch`.

### Reproduction Steps

See above.

### CDK CLI Version

2.83.1

### EKS Blueprints Version

1.9.1

### Node.js Version

v16.20.1

### Environment details (OS name and version, etc.)

Linux

**Comment by elamaran11** [comment]
@plumdog This is not a bug but we dont support it today. But we will add it to our backlog.

**Comment by plumdog** [comment]
@elamaran11 I appreciate that if it's not a supported feature it isn't a bug, but I doubt there are very many AWS customers who want their flux bootstrap repository to be public, so I think this feature being missing renders this addon unusable.

**Comment by plumdog** [comment]
Ok understood.

Is there a way I can determine which Blueprint AddOns are positioned only for use with AWS's open source samples and which are usable by AWS customers running production systems?

Eg https://aws-quickstart.github.io/cdk-eks-blueprints/addons/fluxcd/ doesn't document this intention, which perhaps it - and other such addons that aren't positioned for production customers - could.

**Comment by shapirov103** [comment]
@plumdog your feature request is definitely needed. The add-on in general is not positioned for public repos only, that is just the current state of it. What @elamaran11 meant, was that public repos was the scope addressed for the initial MVPs and it was a conscious decision. 

Acknowledge that lack of the feature detrimentally affects usability of the add-on for real customer use cases. We will work to address and thank you for creating this issue. I am counting that the community will react/upvote as well.

**Comment by plumdog** [comment]
@shapirov103 At a minimum, I think any decisions made about what features aren't supported or the intended usage of an addon should be documented.

Whether that's a general "this addon is only intended for use with AWS's samples, use with caution" that applies to possibly many addons, or "the fluxcd addon doesn't support private source repositories", it would help me to understand which addons are usable.

**Comment by shapirov103** [comment]
@plumdog agree, it is was a miss and that does qualify as a defect. There should be a section like "known limitations" in the docs that calls out lack of private repo support atm.

**Comment by elamaran11** [comment]
@plumdog We did miss to call out in the doc that "FluxCD Addon does not support Flux respository today" but this still does not qualify for a bug. Good news is, we have a PR in flight #749 which will add the feature requested to add `secretRef` stay tuned.
