### ISSUE TITLE
[feat]-[addons] - add `createNamespace` support for metrics-server

### ISSUE THREAD

**Issue by tsahiduek** [aws-quickstart/cdk-eks-blueprints#772]
### Describe the feature

I would like to be able to let metrics-server addon create a custom namespace

### Use Case

Running metrics-server in a namespace that doesn't exists (like `kube-system` or `default`)

### Proposed Solution

add support in the code

### Acknowledgements

- [x] I may be able to implement this feature request

### CDK version used

2.83.1 (build 006b542)

### EKS Blueprints Version

1.10.0

### Node.js Version

v20.2.0

### Environment details (OS name and version, etc.)

MacOS Ventura 13.4

**Comment by elamaran11** [comment]
Closing this issue. This is already implemented.
