### ISSUE TITLE
OpenTelemetryCollector customisation for AmpAddOn

### ISSUE THREAD

**Issue by freschri** [aws-quickstart/cdk-eks-blueprints#783]
### Describe the feature

AmpAddOn enhancement to enable the user to provide their own OpenTelemetryCollector

### Use Case

e.g. configure additional prometheus scrape_configs

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.82.0

### Node.js Version

v20.4.0

### Environment details (OS name and version, etc.)

Mac

**Comment by elamaran11** [comment]
This is complete with `openTelemetryCollector` support is added.
