### ISSUE TITLE
How do I add more CfnOutput to the blueprint stack

### ISSUE THREAD

**Issue by AbhiKulkarniLatitude** [aws-quickstart/cdk-eks-blueprints#788]
### Describe the feature

Its more of a question than the feature request. 
With Blueprint [documentation](https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/), I would like to know how add more CFN outputs (using CDK CfnOutput class) to the blueprints stack.  

### Use Case

Would like to export cluster properties ( IDP issuer url, etc) as CFN output variables

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.87.0

### EKS Blueprints Version

blueprints-1.10.0

### Node.js Version

18

### Environment details (OS name and version, etc.)

AmazonLinux

**Comment by choco-nishant** [comment]
You can add CFN outputs to your blueprints stack like this:

```
   import { CfnOutput } from "aws-cdk-lib";

   const stack = blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .addOns()
    .teams()
    .build(scope, id+'-stack');
  }
  
  const clusterInfo = blueprint.getClusterInfo();

  new CfnOutput(stack, "clusterName", {
      value: `${clusterInfo.cluster.clusterName}`,
  });
  
  new CfnOutput(stack, "oidcIssuer", {
      value: `${clusterInfo.cluster.openIdConnectProvider.openIdConnectProviderIssuer}`,
  });
  
```
