### ISSUE TITLE
Version Field as Optional Field in GenericClusterProvider which defaults to latest EKS Version

### ISSUE THREAD

**Issue by smrutiranjantripathy** [aws-quickstart/cdk-eks-blueprints#792]
### Describe the feature

We would need the version parameter in GenericClusterProvider to be optional. Just like without mentioning provider it launches with the latest available EKS Cluster Version. This would help to create cluster with the latest version which has access to a specific role or an existing IAM Role.

```
const clusterProvider = new blueprints.GenericClusterProvider({
    version: eks.KubernetesVersion.V1_27,  ----> Optional
    mastersRole: blueprints.getResource(context => {
        return iam.Role.fromRoleName(context.scope, "my-role", "Role Name")})
    });
```
    
### Use Case

We are offering a sample blueprint to a customer as a use case of leveraging the EKS Cluster with certain Workloads.
This will be a sample blueprint which will be used by Customer and we don't want to update that blueprint time and again by coding the version. If the version is optional this will remove the pain of updating the version every time with certain workloads.

### Proposed Solution

Don't have a way to implement this. Will have to do a deep dive on the code to figure out a way to do that.

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.88.0

### EKS Blueprints Version

1.10.1

### Node.js Version

v14.17.3

### Environment details (OS name and version, etc.)

OSX 13.4

**Comment by shapirov103** [comment]
The implementation should align with the following logic:

blueprintbuilder will have an opt-in method to always use latest, e.g. builder().version("auto"). If version is set to auto then cluster provider should not require version. If builder.version is set to an explicit value then cluster provider should also not force the version to be specified. 
If customer did not set the version at the blueprint level, and did not opt in to use latest "auto", then clusterprovider must require version to be set. 
@elamaran11 if you have a candidate for this please let me know (e.g. Zach).

**Comment by elamaran11** [comment]
@shapirov103 Zach would be able to turn this out quick. Let me ask him.

**Comment by shapirov103** [comment]
Completed with https://github.com/aws-quickstart/cdk-eks-blueprints/pull/793
