### ISSUE TITLE
[Bug] Karpenter add-on: interruption handling partially enabled by default

### ISSUE THREAD

**Issue by otterley** [aws-quickstart/cdk-eks-blueprints#799]
By default, the `interruptionHandling` attribute for a Karpenter add-on is set to `undefined` (i.e., `false`) but the global configuration has it enabled, leading to errors like:

```
2023-08-02T04:15:03.603Z        ERROR   controller.interruption getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
```

Here's what the ConfigMap looks like:

```
$ kubectl -n karpenter get configmap karpenter-global-settings -o yaml
apiVersion: v1
data:
  aws.interruptionQueueName: <stack-name>
  [snip]
```

If `interruptionHandling` is enabled, this key should not be set in the ConfigMap.

Separately, I wonder why  `interruptionHandling` is disabled by default. It should probably be enabled by default, as that would be a better customer experience.

**Comment by youngjeong46** [comment]
@otterley Thank you for catching on the bug - I will push a quick fix to resolve this issue. As for your other request - we will discuss and probably incorporate it as part of the fast follow (to incorporate 0.29)

**Comment by youngjeong46** [comment]
@otterley - this fix is merged, closing the ticket for now. Let us know if the issue persists on your end.
