### ISSUE TITLE
Karpenter: detect default security group and subnet tags from VPC and cluster

### ISSUE THREAD

**Issue by otterley** [aws-quickstart/cdk-eks-blueprints#800]
### Describe the feature

If the VPC and EKS cluster were created by the Blueprint builder, the relevant context and state needed to configure Karpenter are known, and should be passed automatically to the add-on implementation. This will make the add-on much easier to use because the customer won't need to research (at best) or guess (at worst) to determine what the proper values are.

### Use Case

This will greatly improve the overall UX of using the Karpenter add-on.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.88.0

### Node.js Version

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by BradenM** [comment]
For what its worth, this is the solution I landed on:

```ts
import * as blueprints from '@aws-quickstart/eks-blueprints'
import { type IAnyProducer, type IResolveContext, Stack } from 'aws-cdk-lib'
import { Lazy } from 'aws-cdk-lib'

/**
 * Create a producer with cluster info.
 * @param fn resolver to execute on provide with cluster info and context.
 */
export function lazyClusterInfo<T>(
	fn: (clusterInfo: blueprints.ClusterInfo, context: IResolveContext) => T,
): IAnyProducer {
	let value: T | undefined = undefined
	return {
		produce(context: IResolveContext): T {
			if (value) return value
			const stack = Stack.of(context.scope) as blueprints.stacks.EksBlueprint
			value = fn(stack.getClusterInfo(), context)
			return value
		},
	}
}

// Karpenter helper
export const buildKarpenter = (clusterName?: string, subnetNames?: string) => {
  // lazily resolve tag key if not provided
	const sgTag =
		clusterName ??
		Lazy.uncachedString(
			lazyClusterInfo(
				(clusterInfo) =>
					`${Label.CLUSTER_DISCOVERY}/${clusterInfo.cluster.clusterName}}`,
			),
		)

  // lazily resolve subnets if not provided
	const subnetTags =
		subnetNames ??
		Lazy.uncachedString(
			lazyClusterInfo((clusterInfo) =>
				clusterInfo.cluster.vpc.privateSubnets
					.map((sn) => sn.node.path)
					.join(','),
			),
		)

	return new blueprints.KarpenterAddOn({
		version: 'v0.29.2',
		requirements: [
			{ key: Label.ARCH, op: 'In', vals: ['arm64'] },
			{ key: Label.CAPACITY_TYPE, op: 'In', vals: ['spot', 'on-demand'] },
			{ key: Label.INSTANCE_CATEGORY, op: 'In', vals: ['c', 'm', 'r', 't'] },
			{ key: Label.INSTANCE_HYPERVISOR, op: 'In', vals: ['nitro'] },
		],
		subnetTags: {
			Name: subnetTags,
		},
		securityGroupTags: {
			[sgTag]: 'owned',
		},
		amiFamily: 'AL2',
		consolidation: { enabled: true },
		interruptionHandling: true,
		namespace: 'karpenter',
		values: {
			settings: {
				aws: {
					// informs karpenter to expect prefix delegation.
					enableENILimitedPodDensity: false,
				},
			},
		},
		// refresh nodes at least every 30 days
		ttlSecondsUntilExpired: 2592000,
	})
}

```

Basically just uses `Lazy` to find the cluster info since `blueprints.getResource` doesn't support scalar return types.

**Comment by youngjeong46** [comment]
@otterley We will implement this as part of the 0.29 update. It may take some refactoring.

**Comment by otterley** [comment]
I don't think we need anything as complicated as what @BradenM came up with (clever solution, though!).

The subnet and security group IDs can be provided directly to the `AWSNodeTemplate`'s `securityGroupSelector` and `subnetSelector` attributes via the `aws-ids` sub-attributes. For example:

```
spec:
  securityGroupSelector:
    aws-ids: sg-xxxxxx
  subnetSelector:
    aws-ids: subnet-yyyyy,subnet-zzzz
```

The add-on gets passed the `Cluster` construct via a `ClusterInfo` argument to the `deploy` method. And the `Cluster` construct has both the Cluster Security Group and VPC as accessible attributes. So I don't think it's super complicated to determine the ID values and fill in the manifest with them.

**Comment by shapirov103** [comment]
The subnet and SG selectors were added to the addon. I assume the issue is addressed, please comment if you see any deficiency now and we will reopen.
