### ISSUE TITLE
Config-driven definion for the EKS blueprint CDK

### ISSUE THREAD

**Issue by haofeif** [aws-quickstart/cdk-eks-blueprints#805]
### Describe the feature

The current way of deploying EKS cluster via bluerpint has to have the CDK knowledge. From specifying the subnets of the eks, specifying the node group size and instance type, and fargate profile. 

However, for some of the users, particularly in a self-service fashion, all of these could be configuration like YAML or JSON. The users/application team who request for an EKS cluster only need to know what information to put in as a configuration, instead of knowing the details of the CDK code.

Therefore, we recommend providing examples/features that is config-driven via YAML/JSON to specify the configuration details of the EKS cluster without the need to know CDK.

### Use Case

This is for a platform team who has multiple EKS clusters for each application team, each application team has its own dedicated EKS cluster. But a lot of them do not have to understand cdk, as all they need is an EKS cluster. The config driven definition could give them the opportunity to request a new EKS cluster with the configuration they need following the documentation provided to them without the need to know CDK

### Proposed Solution

The solution can be an example or a dedicated module that convert the config (yaml /json) into CDK code that deploy the EKS cluster via the EKS blueprint 

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

v2.89

### Node.js Version

latest version

### Environment details (OS name and version, etc.)

Mac OS

**Comment by gyalai-aws** [comment]
+1

**Comment by jsamuel1** [comment]
This would be useful for many enterprise platform scenarios.
