### ISSUE TITLE
[TASK] - Amazon EKS SSP Quickstart Workshop

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/cdk-eks-blueprints#81]
AWS workshops are tools that provide customers with a guided learning experiences for various AWS services our solutions. 

https://workshops.aws/

In addition to our documentation site, the EKS SSP workshop will provide customers with self-service training on how to leverage the `Amazon EKS SSP Quickstart` project.

**Comment by youngjeong46** [comment]
Workshop is now live - https://catalog.workshops.aws/eks-blueprints-terraform/en-US
