### ISSUE TITLE
[HelmAddOn]: Cannot apply HelmAddOn

### ISSUE THREAD

**Issue by cao-minh-duc** [aws-quickstart/cdk-eks-blueprints#816]
### Describe the bug

Every add-ons which implement HelmAddOn is not apply. It's always "There were no differences" after add or delete and `cdk diff`

<img width="1370" alt="image" src="https://github.com/aws-quickstart/cdk-eks-blueprints/assets/17726941/157f3e37-ca70-48e6-bc9e-f93770ab98a4">
<img width="1358" alt="image" src="https://github.com/aws-quickstart/cdk-eks-blueprints/assets/17726941/26303831-f3ae-4504-8fab-ffd1e32fd095">

### Expected Behavior

Add-ons which implement HelmAddOn should be apply

### Current Behavior

Nothing. Only "There were no differences"

### Reproduction Steps

```
import { Construct } from 'constructs';
import * as eks from 'aws-cdk-lib/aws-eks';
import * as blueprints from '@aws-quickstart/eks-blueprints';
import * as team from '../teams';

export interface ClusterConstructProps {
    account?: string,
    region?: string,

}
export default class ClusterConstruct {
    constructor (scope: Construct, id: string, props: ClusterConstructProps) {
        const platformTeam = new team.TeamPlatform(props.account ?? "");
        const stackID = `${id}-cluster`;
        const clusterProvider = new blueprints.FargateClusterProvider({
            version: eks.KubernetesVersion.V1_27,
        });

        const addOns: Array<blueprints.ClusterAddOn> = [
            new blueprints.VpcCniAddOn,
                new blueprints.AwsLoadBalancerControllerAddOn,
                new blueprints.AppMeshAddOn,
                new blueprints.NginxAddOn,
                new blueprints.ArgoCDAddOn({
                    namespace: "default"
                }),
                // new blueprints.MetricsServerAddOn,
        ];

        const stack = blueprints.EksBlueprint.builder()
            .account(props.account)
            .region(props.region)
            .clusterProvider(clusterProvider)
            .teams(platformTeam)
            .enableGitOps(blueprints.GitOpsMode.APP_OF_APPS)
            .addOns(...addOns)
            .name(stackID)
            .build(scope, stackID);
    }


}
```

### CDK CLI Version

2.88.0 (build 5d497f9)

### EKS Blueprints Version

1.10.1

### Node.js Version

v18.16.0

### Environment details (OS name and version, etc.)

MacOS M1 13.2.1 (22D68)

**Comment by shapirov103** [comment]
@cao-minh-duc you are using `enableGitOps` with APP_OF_APPS mode. In this mode all helm apply calls are intercepted and it requires a naming convention between your gitops repository and the blueprint. Please see the following section: https://aws-quickstart.github.io/cdk-eks-blueprints/addons/argo-cd/#gitops-for-eks-blueprints-addons

The reason why it was implemented this was is to enable provisioning of AWS specific resources (such as IRSA and service accounts) that are needed for some addons, while the actual deployment of the addon helm charts is handled through the GitOps repo. 

You can also use enableGitOps with APPLICATION mode - in that case deployment of each addon will produce an ArgoXCD application for it. 

If you need to apply the helm charts from the IaC code and deployment through a GitOps repo is not your intention, then please remove `enableGitOps` call to the builder. Happy to answer more questions, I potentially see that we need more documentation on the subject to make it clear.

**Comment by shapirov103** [comment]
@cao-minh-duc please let me know if the supplied approach works for you. I will be closing this soon unless I hear back from you.

**Comment by elamaran11** [comment]
Closing this issue. Please comeback if you are still facing this issue.
