### ISSUE TITLE
Increase amount of pods using VPC CNI with managed cluster

### ISSUE THREAD

**Issue by AsimPoptani** [aws-quickstart/cdk-eks-blueprints#832]
### Describe the documentation issue

I am using a MngClusterProvider to create a T3.medium however I am running out of ips so following the [guide](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html) I enabled VpcCNI and switched on VpcCNI. 

```typescript
new blueprints.addons.VpcCniAddOn({
        enablePrefixDelegation: true,
        warmPrefixTarget: 1,
        warmIpTarget: 1,
        minimumIpTarget:1,
    }),
```

However, there does not seem to be a way to set the max pods as on the managed group. Is it possible to do this as it is not shown in the documentation? 

```typescript
MngClusterProviderProps = {
    amiReleaseVersion: "1.27.3-20230816",
    amiType: NodegroupAmiType.AL2_X86_64,
    desiredSize: 1,
    instanceTypes: [InstanceType.of(InstanceClass.T3, InstanceSize.MEDIUM)],
    maxSize: 1,
    minSize: 1,
    nodeGroupCapacityType: CapacityType.ON_DEMAND,
    version: KubernetesVersion.V1_27,
    diskSize:20,
}
```

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/vpc-cni/

**Comment by shapirov103** [comment]
@AsimPoptani the documentation states that max pods value is automatically calculated for managed node groups if the VPC CNI is preconfigured properly based on this [doc](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html#:~:text=Without%20a%20launch%20template%20or%20with%20a%20launch%20template%20without%20an%20AMI%20ID%20specified%20%E2%80%93%20Complete%20the%20procedure%20in%20Creating%20a%20managed%20node%20group.%20Managed%20node%20groups%20automatically%20calculates%20the%20Amazon%20EKS%20recommended%20max%2Dpods%20value%20for%20you.)(chrome link).

However, the doc specifies that you need to use nitro instances for this to work and t3 is not nitro. Could you try it with M5?

An alternative approach is to use a launchtemplate with the custom AMI (could be stock AMI for EKS) and specify user data and bootstrap commands.

**Comment by AsimPoptani** [comment]
Hmm, I thought t3 was a nitro based instance (link)[https://aws.amazon.com/ec2/instance-types/t3/#Built_on_the_AWS_Nitro_System]. If so it should just be calculated automatically. 

The custom AMI is a shout I will have a look into that.

**Comment by AsimPoptani** [comment]
17 - pods. Which makes sense as the 1 - ip is for the actual node. Will try changing the mng see if that helps.

**Comment by AsimPoptani** [comment]
Yep, it looks like a race issue, I think the only way to avoid this is to have some sort of dependency resolution, I have skimmed CDK and it seems there is some implementation of one?

Thanks for your help @shapirov103 , I wonder if this should live the documentation somewhere?

**Comment by AsimPoptani** [comment]
This issue is resolved, thanks for your help.
