### ISSUE TITLE
provide example of how we are expected to add a team or users

### ISSUE THREAD

**Issue by techlunacy** [aws-quickstart/cdk-eks-blueprints#837]
### Describe the documentation issue

using example provided in the getting started you need to use the "root" user of the account
can we add or expand the example to add IAM users?

### Links

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/docs/getting-started.md

**Comment by shapirov103** [comment]
@techlunacy using "root" user for what specifically? 

As a rule, I don't use  root users for anything, all the development of blueprints is done through IAM and assumption of roles in the target accounts. 

Can you be more specific, where IAM user example will help?

**Comment by techlunacy** [comment]
@shapirov103  i dont want to use the default "root" permissions.
but using the example that is the only permission given to manage the eks cluster. to use a non root user i had to do this:
```
export class TeamAwesome extends PlatformTeam {
  constructor(app: App) {
      super({
          name: "team-awesome",
          users: [
              new ArnPrincipal(`arn:aws:iam::${account}:user/username`),  
              ]

      });
  }
}


const stack = blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .addOns(...addOns)
    .version(KubernetesVersion.V1_27).teams(new TeamAwesome(app))
    .build(app, 'eks-speedy');
```

without the team defined it only let the root user administer/deploy to the cluster.
took me a while to figure that one out.

so i was hoping the documentation in the blueprints would show the way.
