### ISSUE TITLE
Change Instance Type

### ISSUE THREAD

**Issue by RaphaelHerd** [aws-quickstart/cdk-eks-blueprints#854]
### Describe the documentation issue

Dear, I'm currently using AWS eks blueprints cdk and i was digging into the documentation. I was also able to setup a cluster in aws. 

Now i have to change the ec2 instance type from m5 instance to another type. How can I do that? I was not able to find anything in the documentation. If I google, I find a blog post from AWS but the content is von 2022 and is not working anymore (outdated).

Thanks for your help

Raphael

### Links

no link

**Comment by shapirov103** [comment]
@RaphaelHerd the simplest option is to set "eks.default.instance-type" to whatever value you desire in your [cdk context](https://docs.aws.amazon.com/cdk/v2/guide/context.html). 

Example cdk context (e.g. cdk.json):

```json
"context": {
        "eks.default.vpc": null,
        "eks.default.min-size": 1,
        "eks.default.max-size": 2,
        "eks.default.desired-size": 1,
        "eks.default.private-cluster": "false",
        "eks.default.instance-type": "t3.xlarge"
    }
```

More advanced cases, such as registering a group of instance types (e.g. for spot) or multiple node groups can be done using cluster providers, e.g. [Generic cluster provider](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/generic-cluster-provider/)  allows registering multiple node groups and set instance types for them.

Here is an [example](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/generic-cluster-construct/index.ts) and you can use the [patterns repo ](https://github.com/aws-samples/cdk-eks-blueprints-patterns) to check for other examples if needed.
