### ISSUE TITLE
addOns: External Secrets Cluster Secret Store causes rollback

### ISSUE THREAD

**Issue by jwilms1971** [aws-quickstart/cdk-eks-blueprints#864]
### Describe the bug

If I deploy the following it generates the error message as shown below. 

```ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as bcrypt from 'bcrypt';
import * as cdk from 'aws-cdk-lib';
import * as blueprints from '@aws-quickstart/eks-blueprints';
import { ArgoCDAddOnProps } from "@aws-quickstart/eks-blueprints";
import { AwsLoadBalancerControllerProps } from '@aws-quickstart/eks-blueprints';
import { KubernetesManifest, KubernetesVersion, NodegroupAmiType } from 'aws-cdk-lib/aws-eks';
import { InstanceType } from 'aws-cdk-lib/aws-ec2';
import { AckAddOnProps, AckServiceName } from '@aws-quickstart/eks-blueprints';

const app = new cdk.App();

const clusterName = 'foobar';
const account = '999999999999';
const region = 'ap-southeast-1';

const clusterProvider = new blueprints.MngClusterProvider({
    version: KubernetesVersion.V1_27,
    desiredSize: 1,
    instanceTypes: [new InstanceType('m5.large')],
    amiType: NodegroupAmiType.BOTTLEROCKET_X86_64,
    minSize: 1,
    maxSize: 4,
    diskSize: 50,
});

const argoCDAddonProps: ArgoCDAddOnProps = {
    adminPasswordSecretName: 'argocd-admin',
};

const ackAddOnProps: AckAddOnProps = {
    id: "rds-ack",
    serviceName: AckServiceName.RDS,
    name: "rds-chart",
    chart: "rds-chart",
    version: "v0.1.1",
    release: "rds-chart",
    repository: "oci://public.ecr.aws/aws-controllers-k8s/rds-chart",
    managedPolicyName: "AmazonRDSFullAccess",
    createNamespace: true,
    saName: "rds-chart",
};

const addOns: Array<blueprints.ClusterAddOn> = [
    new blueprints.addons.ArgoCDAddOn(argoCDAddonProps),
    new blueprints.addons.ExternalsSecretsAddOn(),
    new blueprints.addons.MetricsServerAddOn(),
    new blueprints.addons.ClusterAutoScalerAddOn(),
    new blueprints.addons.EbsCsiDriverAddOn(),
    new blueprints.addons.AwsLoadBalancerControllerAddOn(),
    new blueprints.addons.AckAddOn(ackAddOnProps),
    new blueprints.addons.VpcCniAddOn(),
    new blueprints.addons.CoreDnsAddOn(),
    new blueprints.addons.KubeProxyAddOn(),
];

const blueprint = blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .addOns(...addOns)
    .clusterProvider(clusterProvider)
    .useDefaultSecretEncryption(true)
    .build(app, clusterName);

const cluster = blueprint.getClusterInfo().cluster;

const clusterSecretStore = new KubernetesManifest(cluster.stack, "ClusterSecretStore", {
    cluster: cluster,
    manifest: [
        {
            apiVersion: "external-secrets.io/v1beta1",
            kind: "ClusterSecretStore",
            metadata: {name: "default"},
            spec: {
                provider: {
                    aws: {
                        service: "SecretsManager",
                        region: region,
                        auth: {
                            jwt: {
                                serviceAccountRef: {
                                    name: "external-secrets-sa",
                                    namespace: "external-secrets",
                                },
                            },
                        },
                    },
                },
            },
        },
    ],
});
```

Error message:

5:48:21 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | ClusterSecretStore0D1876F4
Received response status [FAILED] from custom resource. Message returned: Error: b'error: resource mapping not found for name: "default" namespace: "" from "/tmp/manifest.yaml": no matches for kind "ClusterSecretStore" in version "extern
al-secrets.io/v1beta1"\nensure CRDs are installed first\n'

Logs: /aws/lambda/foobar-awscdkawseksKubectlProvider-Handler886CB40B-zpzcDNB0ZIq7

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 2515799c-7b98-4fd8-ae38-435829597143)

Now, if I comment out the lines starting with const clusterSecretStore = new KubernetesManifest, the cluster gets created. If I then uncomment the same line and redeploy the ClusterSecretStore gets added to the existing cluster.

### Expected Behavior

I would like to be able to run the cluster creation and creation of the ClusterSecretStore together. It seems to me there needs to be a wait introduced between the cluster build and creation of additional manifests that rely upon the CRDs being in place.

### Current Behavior

As per above

### Reproduction Steps

As per above

### CDK CLI Version

2.99.1

### EKS Blueprints Version

1.12.0

### Node.js Version

18.18.2

### Environment details (OS name and version, etc.)

Fedora Release 38

### Other information

I am new to CDK and EKS Blueprints so please be as detailed as possible in any response.

**Comment by jwilms1971** [comment]
@shapirov103 thank you for explaining the options. The blueprints are a great tool that I hope to use extensively.

**Comment by thpham** [comment]
@shapirov103 

I'm facing the same issue with external-secrets ClusterSecretStore being installed too quickly
after the ExternalSecretAddons made the CRDs ready (even with @dependable annotation).
[exemple inspiration with backstage here.](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/backstage-construct/backstage-secret-addon.ts#L32)

I tried to apply your suggestion with `someotherconstruct.node.addDependency`, but I'm facing the problem that it is always "undefined". Do you have any other idea ?

<img width="1123" alt="image" src="https://github.com/aws-quickstart/cdk-eks-blueprints/assets/224674/d7480d6d-8282-49ff-bedf-482773787f0c">
