### ISSUE TITLE
ADOT Addon: Not respecting the "ordered" metadata

### ISSUE THREAD

**Issue by Falco152** [aws-quickstart/cdk-eks-blueprints#869]
### Describe the bug

I have additional configurations that must be deployed to the cluster prior before the ADOT Addon gets deployed 

Sample Code:
PreloadConfigAdotAddon has the "ordered", true metadata 
```
Reflect.defineMetadata("ordered", true, addons.AdotCollectorAddOn);
const addOns: ClusterAddOn[] = [
        new PreloadConfigAdotAddon(),
        ....
        new addons.CertManagerAddOn(),
        new AdotCollectorAddOn({
          version: "v0.80.0-eksbuild.2",
          namespace: "adot-collector",
          policyDocumentProvider: adotPolicyDocumentProvider,
        }),
]
```

### Expected Behavior

PreloadConfigAdotAddon get deployed first before AdotCollectorAddOn

### Current Behavior

AdotCollectorAddOn gets deployed before PreloadConfigAdotAddon

### Reproduction Steps

A simple namespace change would be enough to break AdotCollectorAddOn deployment on a clean deployment of eks-blueprints. And create a new addon pattern that all it does is to create a new namespace. 

### Additional Information/Context

Current workaround is to deploy with the bare minimal of addons and then deploy the rest. 

### CDK CLI Version

2.104.0

### EKS Blueprints Version

1.12.0

### Node.js Version

v20.9.0

### Environment details (OS name and version, etc.)

Ventura 13.6

### Other information

Inspecting the generated template, looks like the deployment of the k8s manifest of the service account has no dependency except for kubectl ready barrier

**Comment by shapirov103** [comment]
@Falco152  You are using imperative `@Reflect.defineMetadata` as opposed to metadata and you are defining this metadata on the Adot as opposed to your addon. 

Please add `@Reflect.metadata("ordered", true)` at the class level to your  `PreloadConfigAdotAddon` similar to [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/ack/index.ts#L54).

**Comment by elamaran11** [comment]
@Falco152 As discussed, namespace order is not blueprints specific issue, thats how the addons work so you have to create namespace ahead of EKS addon for ADOT. You are doing the same right with `PreloadConfigAdotAddon` but not sure we can say its right without having visibility to your code. Please share your `PreloadConfigAdotAddon` class to take a look. Also long term we can add support for ADOT addon to allow custom namespace.

**Comment by elamaran11** [comment]
@Howlla Will work on Adding Namespace support for ADOT addon.
