### ISSUE TITLE
VPC: Missing VPC config options for existing VPCs

### ISSUE THREAD

**Issue by muckelba** [aws-quickstart/cdk-eks-blueprints#879]
### Describe the bug

Hey, i'm trying to replicate our current EKS cluster with blueprints and I've stumbled across two missing configuration options (at least i think they are missing):

### subnets

It seems like blueprints always uses the egress- and if `privateCluster` is false, also the ingress-subnets. I don't see an option to specify the subnets to use.

### securitygroups 
I'm also missing the option to specify or modify one or multiple securityGroups. I can specify one (not multiple) in the nodegroups, but nothing for the control plane.

### Expected Behavior

VPC options for subnets and securitygroups just like when using the aws CLI:
```bash
aws eks create-cluster --resources-vpc-config "subnetIds=$SUBNET1,$SUBNET2,securityGroupIds=$CLUSTER_SG_ID" 
```

### Current Behavior

I'm able to import the VPC by specifying its ID, but nothing more

### Reproduction Steps

```ts
const clusterProvider = new blueprints.GenericClusterProvider({
  version: k8sVersion,
  role: [...],
  mastersRole: [...],
  managedNodeGroups: [bootstrapNG()],
  privateCluster: true,
});

const vpc = new blueprints.VpcProvider("redacted");

const blueprint = blueprints.EksBlueprint.builder()
  .resourceProvider("vpc", vpc)
  .resourceProvider("node-role", nodeRole)
  .clusterProvider(clusterProvider)
  .account(account)
  .region(region)
  .addOns(...addOns)
  .useDefaultSecretEncryption(true)
  .teams(adminTeam)
  .build(app, clusterName);
```

### CDK CLI Version

2.99.1 (build b2a895e)

### EKS Blueprints Version

1.12.0

### Node.js Version

v18.15.0

### Environment details (OS name and version, etc.)

Ubuntu Linux in WSL

**Comment by shapirov103** [comment]
@muckelba we are using the CDK constructs underneath and we expose all the attributes available to use from CDK. 

For example,  `GenericClusterProvider` allows specifying a securitygroup. It is singular SG for the control plane based on the [eks.Cluster specification](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#securitygroup) from CDK.

NodeGroup allows specifying `ec2.SubnetSelection` in its `nodeGroupSubnets` attribute. 

Example: 

```ts
    const clusterProvider = new blueprints.GenericClusterProvider({
...
            vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS }],
            securityGroup: blueprints.getNamedResource("my-sg") as ec2.ISecurityGroup, // control plane group
            managedNodeGroups: [
                {
                    id: "mng-ondemand",
                    amiType: eks.NodegroupAmiType.AL2_X86_64,
                    instanceTypes: [new ec2.InstanceType('m5.2xlarge')],
                    nodeGroupSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS 
                }
```

Hope this helps.

**Comment by shapirov103** [comment]
@muckelba we did have requests to support local chart files, however, given the current approach used in the helm provider, one solution is to upload the chart to S3 and get a presigned URL for it. You could also use ECR to upload helm charts. 
Please let me know if there is anything missing for this issue to be closed.

**Comment by muckelba** [comment]
Hey, @shapirov103 we've settled on using ECR and wrote a helm chart syncer job to push all required chart from the interntet into ECR. Closing this issue
