### ISSUE TITLE
Update CDK to 2.109.0, addon versions upgrades, core addon upgrades

### ISSUE THREAD

**Issue by cristianmagana** [aws-quickstart/cdk-eks-blueprints#880]
### Describe the feature

Similar to #853

aws-cdk and aws-cdklib@2.109.0 finally have EKS V1.28 available. Can we upgrade the package.json, helm chart addons, and core addons to allow version compatibility between libraries?

 

### Use Case

Upgrading EKS clusters to V1.28

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.109.0

### EKS Blueprints Version

1.12.0

### Node.js Version

18.17.0

### Environment details (OS name and version, etc.)

linux

**Comment by shapirov103** [comment]
@cristianmagana at this point it is most likely will be early December. Customers should consider upgrading their CDK version locally using overrides as shown [here](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/package.json#L48).
Will be included in the next release and tested out on 1.28.

**Comment by cristianmagana** [comment]
Ok, I had pulled down the project and created a similar branch to #853 but was unable to push it. Feels like a waste to delete. Would it be more work to allow the push to a feature branch `task/1.13.0-release-prep` then having someone re-sweep to helm chart updates?
