### ISSUE TITLE
Support Container Logs Collector Configuration for ADOT add-on (update version)

### ISSUE THREAD

**Issue by arron-shin** [aws-quickstart/cdk-eks-blueprints#881]
### Describe the feature

New Container Logs Collector Configuration for ADOT. Here is the blog post for [Container Logs Collector Configuration](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-container-logs/) reference.

### Use Case

New Container Logs Collector Configuration for ADOT. Here is the blog post for [Container Logs Collector Configuration](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-container-logs/) reference.

### Proposed Solution

Update version to `v0.80.0-eksbuild.2` to `v0.88.0-eksbuild.1`.
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/6ec2a2403ef34052c7d898f6d72a436b50fd589b/lib/addons/adot/index.ts#L18

ref docs: https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/add-on-v88-migration

### Acknowledgements

- [x] I may be able to implement this feature request

### CDK version used

2.99

### Node.js Version

20.0.0

### Environment details (OS name and version, etc.)

Mac

**Comment by arron-shin** [comment]
If there are no issues with this issue, I'll create a PR.

**Comment by elamaran11** [comment]
@arron-shin Yes please. PR will be Awesome.

**Comment by elamaran11** [comment]
@arron-shin ADOT Logs is implemented with [CDK Observability Accelerator OSS Pattern](https://github.com/aws-observability/cdk-aws-observability-accelerator/pull/141). You can refer this for opinionated patter with Customized Configurations. Feel free to close this ticket or you can submit a PR with Addon up to you!

**Comment by elamaran11** [comment]
Closing this issue. This support is provided now!
