### ISSUE TITLE
EBS-CSI addon should default to gp3

### ISSUE THREAD

**Issue by fbscarel** [aws-quickstart/cdk-eks-blueprints#896]
### Describe the feature

Currently it seems to me like upon installing the EBS-CSI addon it defaults to the `gp2` StorageClass. As far as I've checked there seems to be no easy way to change this default on the addon installation, neither is it documented or in any existing issues. One workaround I've adapted from here (https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/986#issuecomment-1258064937) is doing this post cluster provisioning:

```typescript
        // Remove default tag from gp2 StorageClass volumes
        new eks.KubernetesPatch(this, `${clusterName}-SCGP2-RemoveDefault`, {
            cluster: eksCluster.getClusterInfo().cluster,
            resourceName: "storageclass/gp2",
            applyPatch: {
                metadata: {
                    annotations: {
                        'storageclass.kubernetes.io/is-default-class': 'false',
                    },
                },
            },
            restorePatch: {
                metadata: {
                    annotations: {
                        'storageclass.kubernetes.io/is-default-class': 'true',
                    },
                },
            },
        });

        // Create and set gp3 StorageClass as cluster-wide default
        new eks.KubernetesManifest(this, `${clusterName}-SCGP3-SetDefault`, {
            cluster: eksCluster.getClusterInfo().cluster,
            manifest: [
                {
                    apiVersion: 'storage.k8s.io/v1',
                    kind: 'StorageClass',
                    metadata: {
                        name: 'gp3',
                        annotations: {
                            'storageclass.kubernetes.io/is-default-class': 'true',
                        },
                    },
                    provisioner: 'ebs.csi.aws.com',
                    reclaimPolicy: 'Delete',
                    volumeBindingMode: 'WaitForFirstConsumer',
                    parameters: {
                        type: 'gp3',
                        fsType: 'ext4',
                        encrypted: 'true',
                    },
                },
            ],
        });
```

Ideally, there should be an option passed to the addon that would install the `gp3` SC as default, without needing to patch resources like above.

### Use Case

Utilize the newer GP3 EBS volume type.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.115.0

### EKS Blueprints Version

1.13.1

### Node.js Version

v18.19.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04 x86_64

**Comment by shapirov103** [comment]
@elamaran11 let's review and assign.

**Comment by elamaran11** [comment]
Sounds good @shapirov103 We can plan to have someone work on this.

**Comment by elamaran11** [comment]
@nrajb Has show interest to work on  this issue.
