### ISSUE TITLE
[Karpenter Add-on] blockDeviceMappings[0].ebs.volumeSize defined as number instead of string

### ISSUE THREAD

**Issue by Cryoware** [aws-quickstart/cdk-eks-blueprints#899]
### Describe the documentation issue

Example usage code not working because when specifying the volume size you must enter a number but it seems karpenter is expecting a string like `20Gi` instead of just `20`.

Getting the below error when deploying. Complains about validation failed **expected 1G <= 20 <= 64T**
```
Error from server (BadRe
quest): error when creating "/tmp/manifest.yaml": admission webhook "validation.webhook.karpenter.k8s.aws" denied the request: validation failed: expected 1G <= 20 <= 64T: spec.provider.blockDeviceMappings[0].ebs.volumeSize
```
I've tried different versions of packages and currently running.
```
    "@aws-quickstart/eks-blueprints": "^1.13.1",
    "aws-cdk-lib": "2.115.1",

cdk version: 2.115.0 (build 58027ee)
```
Seems code was merged 3 weeks ago, so am I missing something from docs or is this a bug?
Thanks

### Example blueprint usage
https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/#usage

### [karpenter-provider-aws] VolumeSize in `Gi`, `G`, etc.
https://github.com/aws/karpenter-provider-aws/blob/466da568081bae8eb70d17fec060d208ab7fafbc/pkg/apis/v1beta1/ec2nodeclass.go#L276

### [cdk-eks-blueprints] volumeSize?: number;
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/0e27d32c94b8734097a8016ee2650dcc5bc488b3/lib/addons/karpenter/index.ts#L29C9-L29C9

**Comment by youngjeong46** [comment]
Issue has been resolved. Closing it for now, but please re-open if it persists.
