### ISSUE TITLE
(CoreDNS Addon) Support for MAP to support version based on Kubernetes version.

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#900]
### Describe the feature

(CoreDNS Addon) Support for MAP to support version based on Kubernetes version. This addon should be update as like KubeProxy addon based on MAP of versions.

### Use Case

This addon should be updated as like KubeProxy addon based on MAP of versions per K8s version of EKS cluster.

### Proposed Solution

(CoreDNS Addon) Support for MAP to support version based on Kubernetes version. This addon should be update as like KubeProxy addon based on MAP of versions.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.100.1

### EKS Blueprints Version

1.13.1

### Node.js Version

20.x.x

### Environment details (OS name and version, etc.)

Mac

**Comment by Howlla** [comment]
This command will help 
`eksctl utils describe-addon-versions --kubernetes-version 1.28 --name coredns | grep AddonVersion`

**Comment by elamaran11** [comment]
This is already implemented and should be shipped in next release.
