### ISSUE TITLE
Add MSK/Kafka support to the ACK list

### ISSUE THREAD

**Issue by calliope7** [aws-quickstart/cdk-eks-blueprints#901]
### Describe the feature

Kafka ACK version 0.0.1 appears to be available now but it is not accessible from Ack-addons in the serviceMappings.ts file.  The feature would add Kafka as an Ack-addon to enable control of Managed Kafka from a K8s cluster.

### Use Case

I'm trying to prove out a framework which needs to run on K8s but could well benefit from leveraging AWS managed services.  The framework leverages Kafka.   Leveraging the CDK-EKS blueprints looks like a good way to build stable K8s environments within the AWS environment and this represents a good opportunity to let AWS do the undifferentiated heavy lifting!

### Proposed Solution

The aws-controller-k8s team has already build the required MSK controller.. Thus this looks more or less like a plumbing job to connect the dots from the CDK-EKS blueprints framework.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.99.1 (build b2a895e)

### EKS Blueprints Version

1.13.1

### Node.js Version

v20.10.0

### Environment details (OS name and version, etc.)

Windows 10 Pro - version 22H2 - OS build 19045.3803

**Comment by elamaran11** [comment]
@calliope7 We will add this to our next blueprints release.

**Comment by calliope7** [comment]
Nice one.  I'll test it when the blueprints release is done.
