### ISSUE TITLE
Support for EKS Version 1.29

### ISSUE THREAD

**Issue by RyanDevlin** [aws-quickstart/cdk-eks-blueprints#912]
### Describe the feature

[EKS version 1.29 was just released this past Tuesday](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-29/) (Jan. 23rd). We would like support for this version to be added into EKS Blueprints so we can rebuild all of our clusters with the latest version.

### Use Case

I work for an internal AWS team building large Kubernetes clusters for a new service we are launching soon. I would like to launch with the latest version of EKS. Because we use Blueprints to build our clusters, we are limited by the Blueprint version for building a cluster with the latest version.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

1.203

### EKS Blueprints Version

1.12.0

### Node.js Version

18.x

### Environment details (OS name and version, etc.)

Running CDK on AL2, deploying EKS with both AL2 and Bottlerocket hosts.

**Comment by shapirov103** [comment]
@RyanDevlin  our CDK version is 2.115, we have been off the 1.x version of CDK for a long time (just making sure there is no lib conflict). 
We will add explicit support for 1.29 and make a default version, however you should be able to use 1.29 now:

```typescript
           EksBlueprint.builder()
                 ...
                .version(KubernetesVersion.of('1.29'))
```

We have not tested it yes, so interested in any feedback wrt migration to 1.29. Some core addons may require explicit version set to match the target version.

**Comment by RyanDevlin** [comment]
Fair point about our CDK version, I think we have to upgrade to V2 anyway so that's no issue. As for deploying 1.29 in the way you mentioned, I don't think we want to put in the work to rebuild until it's fully supported and tested with all AddOns (we use several). Do you have a rough timeline for when it will be fully supported and tested?

**Comment by tdalbo92** [comment]
Chiming in here - ideally we'd get 1.29 support well in advance of November 26th later this year, when it goes out of standard support and starts costing me extra money in extended support.

**Comment by shapirov103** [comment]
we will add support directly but you should be able to provision EKS clusters v 1.29 and 1.30 using `eks.KubernetesVersion.of('1.29')`
