### ISSUE TITLE
karpenter:  ebs volumeSize should be string

### ISSUE THREAD

**Issue by ttirtawi** [aws-quickstart/cdk-eks-blueprints#914]
### Describe the bug

When trying to use configure `KarpenterAddOn` with CDK (to create EKS v1.28), specifically with the `blockDeviceMappings` below:

```
    blockDeviceMappings: [{
      deviceName: "/dev/xvda",
      ebs: {
        volumeSize: 100,
        volumeType: ec2.EbsDeviceVolumeType.GP3,
        deleteOnTermination: true,
        throughput: 250,
        iops: 3000,
      },
    }]
```

I got the following error complaining about the invalid data type.

```
 error when patching "/tmp/manifest.yaml": admission webhook "validation.webhook.karpenter.k8s.aws" denied the request: validation failed: expected 1G <= 100 <= 64T: spec.provider.blockDeviceMappings[0].ebs.volumeSize\n'
```

Apparently in the `https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/karpenter/index.ts#L29`, `volumeSize` set to number. While Karpenter specification use string as shown in [this documentation](https://karpenter.sh/v0.31/concepts/node-templates/#examples-1).

This prevent us to specify the custom block device size in the Karpenter Adds On.

### Expected Behavior

Volume size in the `blockDeviceMapping` should be number as per [EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html).

### Current Behavior

We cannot specify `blockDeviceMapping` when configuring KarpenterAddOn.

### Reproduction Steps

Create CDK Blueprint for EKS with Karpenter AddsOn contain custom `blockDeviceMapping` as shown in the example below:

```
new blueprints.addons.KarpenterAddOn({
    requirements: [
        { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
        { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['on-demand']},
        { key: 'topology.kubernetes.io/zone', op: 'In', vals: ['ap-southeast-3a', 'ap-southeast-3b', 'ap-southeast-3c']}
    ],
    subnetTags: {
      "aws-cdk:subnet-type": "Private",
      "aws:cloudformation:stack-name": "CdkEKSDemoClusterVpcStack"
    },
    securityGroupTags: {
      "kubernetes.io/cluster/demoCluster": "owned",
    },
    consolidation: { enabled: true },
    ttlSecondsUntilExpired: 2592000,
    weight: 90,
    interruptionHandling: true,
    tags: {
      schedule: 'always-on'
    },
    blockDeviceMappings: [{
      deviceName: "/dev/xvda",
      ebs: {
        volumeSize: 100,
        volumeType: ec2.EbsDeviceVolumeType.GP3,
        deleteOnTermination: true,
        throughput: 250,
        iops: 3000,
      },
    }]
  })
];
```

### Possible Solution

Change the `https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/karpenter/index.ts#L29`, `volumeSize` to string.

### CDK CLI Version

2.115.0

### EKS Blueprints Version

1.13.1

### Node.js Version

v18.16.0

### Environment details (OS name and version, etc.)

EKS v1.28

**Comment by Cryoware** [comment]
Related https://github.com/aws-quickstart/cdk-eks-blueprints/issues/899

**Comment by youngjeong46** [comment]
Issue has been resolved. Closing it for now, but please re-open if it persists.
