### ISSUE TITLE
When creating an argocd secret to use SSH auth I needed all the \n to be escaped as \\n to get things to work

### ISSUE THREAD

**Issue by ray-kaminski** [aws-quickstart/cdk-eks-blueprints#938]
### Describe the documentation issue

The documentation describes this awk

```awk
awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}'  <path-to-your-cert>
```
I had to change it to this

```awk
awk 'NF {sub(/\r/, ""); printf "%s\\\\n",$0;}' ssh.pem
```
to get things to work.

So in the example shown in the doc I need {
    "sshPrivateKey": "-----BEGIN THIS IS NOT A REAL PRIVATE KEY-----\nb3B

To be 
{
    "sshPrivateKey": "-----BEGIN THIS IS NOT A REAL PRIVATE KEY-----\\\nb3B

I created a template using argocd directly and it had \\\n and worked my way backwards to this.

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/argo-cd/

**Comment by shapirov103** [comment]
@ray-kaminski if it is an issue that needs to be addressed then we can keep it open until we get a merged PR. Please advise.

The doc also states 
> A convenience script to create the JSON structure for SSH private key can be found [here](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/scripts/create-argocd-ssh-secret.sh).

However, if the command above is wrong, then it is a clear defect.
