### ISSUE TITLE
(CloudWatchInsights Addon): (Auto doesnt work with picking latest version and Unable to override version, it picks default "auto")

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#948]
### Describe the bug

(CloudWatchInsights Addon): `auto` doesnt work with picking latest version and unable to override version, it picks default "auto" as a version and send it to CloudFormation.

### Expected Behavior

`auto` should pick the latest version using aws sdk call. Also the addon should support version passed.

### Current Behavior

`auto` doesnt work with picking latest version and unable to override version, it picks default "auto" as a version and send it to CloudFormation.

### Reproduction Steps

Pass version to CloudWatchInsights Addon.

### Possible Solution

The Addon should use `CreateNamespace` and `CreateSA` overrides to create namespace and SA but should not directly invoke `cfn.addon` but rather use the core-addon features for deploy so that version issues is taken care.

### CDK CLI Version

2.130.0

### EKS Blueprints Version

1.14.0

### Node.js Version

20.x.x

### Environment details (OS name and version, etc.)

Mac

**Comment by 5herlocked** [comment]
I will be picking this up

**Comment by a-bigelow** [comment]
I ran into this yesterday, and was surprised that the addon's `version` prop had been overwritten to only allow changes to the version of the cloudwatch agent itself, whereas every other addon I'm familiar with allows you to pass `version` as an override for the addon's default props.

For improved dx, can we:
- Look at migrating the cloudwatch agent property to `cloudWatchAgentVersion`, OR
- Supply an override variable for the version of the addon, so users don't need to wait for a patch release to get around bugs like this.

**Comment by elamaran11** [comment]
This issue is fixed now. Closing this issue.
