### ISSUE TITLE
[eks-blueprints 1.14.0] Getting auto version of EKS AddOns caused CDK pipeline failed

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#951]
### Describe the bug

![image](https://github.com/aws-quickstart/cdk-eks-blueprints/assets/37215642/56b8978a-4ef4-4114-a82e-68dab7aa5655)

### Expected Behavior

Pipeline deploys successfully

### Current Behavior

Failed

### Reproduction Steps

Trigger CDK pipeline with eks-blueprints 1.14.0

### CDK CLI Version

2.132.1

### EKS Blueprints Version

1.14.0

### Node.js Version

v18.18.2

### Environment details (OS name and version, etc.)

Linux

**Comment by shapirov103** [comment]
@elamaran11 the failure above is for version look up of a core addon, this is the specific condition that was supposed to be addressed - failure on API invocation should not cause the failure and we fall back to the version map for version look up in such as a case. 

@vumdao the workaround atm is to apply DEFAULT_BUILD_POLICIES to the codebuild portion of the pipeline that has the [right permission](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/pipelines/code-pipeline.ts#L207) defined.

Please refer to the [Handling Build Time Access ](https://aws-quickstart.github.io/cdk-eks-blueprints/pipelines/#handling-build-time-access) section of the pipeline to add the policies to your codebuild project.
