### ISSUE TITLE
(addons/CloudWatchInsights): Does not create Service Account

### ISSUE THREAD

**Issue by Falco152** [aws-quickstart/cdk-eks-blueprints#971]
### Describe the bug

When deploying addon/CloudWatchInsights, the service account IAM mapping related for the addon does not get created.

Since the IAM mapping is not created, the addon fails to send logs

`
"eventTime": "2024-03-31T17:19:32Z",
"eventSource": "logs.amazonaws.com",
"eventName": "CreateLogStream",
"userAgent": "aws-fluent-bit-plugin-container-insights",
"errorCode": "AccessDenied",
`

### Expected Behavior

Service Account get created with an IAM role mapping to the Managed Policies: CloudWatchAgentServerPolicy, AWSXrayWriteOnlyAccess

### Current Behavior

No Service Account with IAM role mapping

### Reproduction Steps

`
new blueprints.addons.CloudWatchInsights(),
`

### CDK CLI Version

2.134.0

### EKS Blueprints Version

1.14.1

### Node.js Version

v20.12.0

### Environment details (OS name and version, etc.)

mac 14.3.1

### Other information

There was a change from 1.13 to 1.14 for this addon.

**CreateServiceAccount** method does not get invoked due to missing prerequisites

**Comment by elamaran11** [comment]
@5herlocked Please check on this issue.

**Comment by 5herlocked** [comment]
Looking into it. Expect response around ~4/5 or a few days after that.

**Comment by elamaran11** [comment]
@5herlocked Updates on this PR?

**Comment by elamaran11** [comment]
Issue is fixed, closing this.
