### ISSUE TITLE
(addon/AdotCollectorAddOn): Avoiding CoreAddonProps to be filled

### ISSUE THREAD

**Issue by Falco152** [aws-quickstart/cdk-eks-blueprints#972]
### Describe the bug

If using CoreAddonProps, requires **version** to be filled

### Expected Behavior

If want to use the default _auto_, version could be omitted 

### Current Behavior

`
Argument of type '{ namespace: string; }' is not assignable to parameter of type 'AdotCollectorAddOnProps'.
  Property 'version' is missing in type '{ namespace: string; }' but required in type 'Omit<CoreAddOnProps, "saName" | "addOnName">'.
`

### Reproduction Steps

`
new blueprints.addons.AdotCollectorAddOn({
  namespace: "adot-collector",
}),
`

### CDK CLI Version

2.134.0

### EKS Blueprints Version

1.14.1

### Node.js Version

v20.12.0

### Environment details (OS name and version, etc.)

mac 14.3.1

**Comment by elamaran11** [comment]
@Falco152 Thankyou for submitting this issue. Its a minor fix like [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/01a78dcc2f5b54a41fe708fc4eaf862d07ad4a56/lib/addons/cloud-watch-insights/index.ts#L21), Do you mind testing and submitting a PR. We will patch this.

**Comment by elamaran11** [comment]
Issue is fixed.
