### ISSUE TITLE
ACKAddOn ARM64 Support

### ISSUE THREAD

**Issue by dwright20** [aws-quickstart/cdk-eks-blueprints#974]
### Describe the feature

Per the [Supported Add-ons](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/#supported-add-ons), ACKAddOn doesn't support arm64, but it looks like ACK has rolled out arm64 support: https://github.com/aws-controllers-k8s/community/issues/138#issuecomment-1917776240. Can we get the [ACKAddOn supports](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/ack/index.ts#L60) tag updated?

### Use Case

I'd like to be able to deploy ACK in an EKS cluster with ARM compute

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.133

### Node.js Version

20.11.1

### Environment details (OS name and version, etc.)

Mac

**Comment by elamaran11** [comment]
@dwright20 MemoryDB still does not support ARM64. Making this ARM64 Addon will make few deployments on non supported charts to fail. Please let us know if you have a need to support ARM64 with ACK.

**Comment by dwright20** [comment]
I do -- I have a CDK app that deploys multiple baseline clusters that will have applications deployed onto them that will need to create AWS resources from the cluster. Ideally the baseline cluster has the bulk, if not all, of the addons/external charts needed. S3, DynamoDB, SQS, API GW v2 are the immediate ones that come to mind.

Probably a bit hacky, but could we do something like this:
```
export interface ServiceAckAddOnProps extends Omit<AckAddOnProps, "serviceName">{}

@supportsALL
export class S3AckAddOn extends AckAddOn{
    constructor(props?: ServiceAckAddOnProps) {
        const serviceOptions = { ...props, serviceName: AckServiceName.S3 }
        super(serviceOptions);
    }
}

@supportsX86
export class MemoryDBAckAddOn extends AckAddOn{
    constructor(props?: ServiceAckAddOnProps) {
        const serviceOptions = { ...props, serviceName: AckServiceName.MEMORYDB }
        super(serviceOptions);
    }
}
```

It's not the end all be all if getting this added into the blueprint isn't feasible (for whatever reason), but happy to implement the feature if it's something as "light" as ^

**Comment by elamaran11** [comment]
@dwright20 Thankyou for the clarity. I think the above hacky approach might work for interim but we will see if we can find a way to implement this in upcoming release. The code is one line in change in the addon but testing it across different combinations of ACK support charts we have takes time. We will keep you posted. That said, we are also happy and will be so much welcoming if you are looking to contribute.
