### ISSUE TITLE
AddOns: Amp addon does not deploy the right cluster role when Daemonset deployment mode is used

### ISSUE THREAD

**Issue by arunvthangaraj** [aws-quickstart/cdk-eks-blueprints#990]
### Describe the bug

When using Amp Addon with a Daemonset deployment mode, the cluster role required for the otel collector to describe services, namespaces and pods is not created. Only when the deployment mode Deployment creates the correct cluster role.

### Expected Behavior

Even when DaemonSet deployment mode is used, the right cluster role should be deployed so that otel collector can describe pods, services and namespaces.

### Current Behavior

When using Amp Addon with a Daemonset deployment mode, the cluster role required for the otel collector to describe services, namespaces and pods is not created.

### Reproduction Steps

Deploy AmpAddon using Daemonset deployment mode

### CDK CLI Version

2.133.0

### Node.js Version

20.11.0

### Environment details (OS name and version, etc.)

MacOs

**Comment by elamaran11** [comment]
Thankyou for the PR on this @arunvthangaraj
