### ISSUE TITLE
FluxCD Github example uses unsupported Bearer token auth

### ISSUE THREAD

**Issue by JamesMcMahon** [aws-quickstart/cdk-eks-blueprints#999]
### Describe the documentation issue

The example in the FluxCD Addon documentation is incorrect. FluxCD does not support bearer token auth with Github due to limitations in the Github API.

Specifically this secret will not work:
```ts
const externalSecret = new eks.KubernetesManifest(clusterInfo.cluster.stack, "ExternalSecret", {
    cluster: cluster,
    manifest: [
        {
            apiVersion: "external-secrets.io/v1beta1",
            kind: "ExternalSecret",
            metadata: {
                name: "git-admin-credentials",
                namespace: "flux-system"
            },
            spec: {
                secretStoreRef: {
                    name: "secret-manager-store",
                    kind: "ClusterSecretStore",
                },
                target: {
                    name: "repository-creds"
                },
                data: [
                    {
                        secretKey: "bearerToken",
                        remoteRef: {
                            key: "bearer-token-auth"
                        },
                    },
                ],
            },
        },
    ],
});
externalSecret.node.addDependency(secretStore);
return Promise.resolve(secretStore);
}
```

Instead [Basic access authentication](https://fluxcd.io/flux/components/source/gitrepositories/#basic-access-authentication) is needed.

FluxCD References:

* https://fluxcd.io/flux/components/source/gitrepositories/#bearer-token-authentication

> Note: If you are looking to use OAuth tokens with popular servers (e.g. [GitHub](https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#authenticating-with-a-token-generated-by-an-app), [Bitbucket](https://support.atlassian.com/bitbucket-cloud/docs/using-access-tokens/), [GitLab](https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html#clone-using-a-token)), you should use basic access authentication instead. These servers use basic HTTP authentication, with the OAuth token as the password. Check the documentation of your Git server for details.

* [Issue to add the above note to documenton](https://github.com/fluxcd/flux2/issues/3668)
* [Confirmation of Github limitation by Flux maintainer](https://github.com/fluxcd/flux2/discussions/4741#discussioncomment-9214447)

### Links

* https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/docs/addons/fluxcd.md
* https://aws-quickstart.github.io/cdk-eks-blueprints/addons/fluxcd/

**Comment by shapirov103** [comment]
@elamaran11 do you mind triaging this one?

**Comment by elamaran11** [comment]
@shapirov103 Sure.

**Comment by JamesMcMahon** [comment]
If you are open to it I can put a PR together with a fix

**Comment by elamaran11** [comment]
@JamesMcMahon If you can put a PR, that will be Awesome. We can review it and get it merged sooner.

**Comment by JamesMcMahon** [comment]
@elamaran11 - PR is up at https://github.com/aws-quickstart/cdk-eks-blueprints/pull/1000

**Comment by JamesMcMahon** [comment]
PR merged, closed
